class AnkletRunner {
    public static void main(String[] args) {
// default constructor
        Anklet a1 = new Anklet();
        a1.material = "Gold";
        Anklet a2 = new Anklet();
        a2.material = "Silver";
        Anklet a3 = new Anklet();
        a3.material = "Platinum";
        Anklet a4 = new Anklet();
        a4.material = "Bronze";
        Anklet a5 = new Anklet();
        a5.material = "Copper";
        Anklet a6 = new Anklet();
        a6.material = "Beads";
        Anklet a7 = new Anklet();
        a7.material = "Pearl";
        Anklet a8 = new Anklet();
        a8.material = "Leather";
        Anklet a9 = new Anklet();
        a9.material = "Thread";
        Anklet a10 = new Anklet();
        a10.material = "Nylon";
        Anklet a11 = new Anklet();
        a11.material = "Titanium";
        Anklet a12 = new Anklet();
        a12.material = "Brass";
        Anklet a13 = new Anklet();
        a13.material = "Steel";
        Anklet a14 = new Anklet();
        a14.material = "Silk";
        Anklet a15 = new Anklet();
        a15.material = "Cotton";
        Anklet a16 = new Anklet();
        a16.material = "Ruby";
        Anklet a17 = new Anklet();
        a17.material = "Emerald";
        Anklet a18 = new Anklet();
        a18.material = "Sapphire";
        Anklet a19 = new Anklet();
        a19.material = "Jade";
        Anklet a20 = new Anklet();
        a20.material = "Coral";
        Anklet a21 = new Anklet();
        a21.material = "Amber";
        Anklet a22 = new Anklet();
        a22.material = "Onyx";
        Anklet a23 = new Anklet();
        a23.material = "Opal";
        Anklet a24 = new Anklet();
        a24.material = "Topaz";
        Anklet a25 = new Anklet();
        a25.material = "Quartz";

        System.out.println("Anklet material : " + a1.material);
        System.out.println("Anklet material : " + a2.material);
        System.out.println("Anklet material : " + a3.material);
        System.out.println("Anklet material : " + a4.material);
        System.out.println("Anklet material : " + a5.material);
        System.out.println("Anklet material : " + a6.material);
        System.out.println("Anklet material : " + a7.material);
        System.out.println("Anklet material : " + a8.material);
        System.out.println("Anklet material : " + a9.material);
        System.out.println("Anklet material : " + a10.material);
        System.out.println("Anklet material : " + a11.material);
        System.out.println("Anklet material : " + a12.material);
        System.out.println("Anklet material : " + a13.material);
        System.out.println("Anklet material : " + a14.material);
        System.out.println("Anklet material : " + a15.material);
        System.out.println("Anklet material : " + a16.material);
        System.out.println("Anklet material : " + a17.material);
        System.out.println("Anklet material : " + a18.material);
        System.out.println("Anklet material : " + a19.material);
        System.out.println("Anklet material : " + a20.material);
        System.out.println("Anklet material : " + a21.material);
        System.out.println("Anklet material : " + a22.material);
        System.out.println("Anklet material : " + a23.material);
        System.out.println("Anklet material : " + a24.material);
        System.out.println("Anklet material : " + a25.material);

// parameterized constructor
        Anklet p1 = new Anklet("Gold Chain");
        Anklet p2 = new Anklet("Silver Chain");
        Anklet p3 = new Anklet("Platinum Band");
        Anklet p4 = new Anklet("Bronze Ring");
        Anklet p5 = new Anklet("Copper Wire");
        Anklet p6 = new Anklet("Glass Beads");
        Anklet p7 = new Anklet("Pearl Strand");
        Anklet p8 = new Anklet("Brown Leather");
        Anklet p9 = new Anklet("Red Thread");
        Anklet p10 = new Anklet("Black Nylon");
        Anklet p11 = new Anklet("Titanium Band");
        Anklet p12 = new Anklet("Brass Links");
        Anklet p13 = new Anklet("Stainless Steel");
        Anklet p14 = new Anklet("Blue Silk");
        Anklet p15 = new Anklet("White Cotton");
        Anklet p16 = new Anklet("Ruby Set");
        Anklet p17 = new Anklet("Emerald Set");
        Anklet p18 = new Anklet("Sapphire Set");
        Anklet p19 = new Anklet("Jade Beads");
        Anklet p20 = new Anklet("Coral Beads");
        Anklet p21 = new Anklet("Amber Stone");
        Anklet p22 = new Anklet("Onyx Stone");
        Anklet p23 = new Anklet("Opal Set");
        Anklet p24 = new Anklet("Topaz Set");
        Anklet p25 = new Anklet("Rose Quartz");

        System.out.println("Material of Anklet 1 : " + p1.material);
        System.out.println("Material of Anklet 2 : " + p2.material);
        System.out.println("Material of Anklet 3 : " + p3.material);
        System.out.println("Material of Anklet 4 : " + p4.material);
        System.out.println("Material of Anklet 5 : " + p5.material);
        System.out.println("Material of Anklet 6 : " + p6.material);
        System.out.println("Material of Anklet 7 : " + p7.material);
        System.out.println("Material of Anklet 8 : " + p8.material);
        System.out.println("Material of Anklet 9 : " + p9.material);
        System.out.println("Material of Anklet 10 : " + p10.material);
        System.out.println("Material of Anklet 11 : " + p11.material);
        System.out.println("Material of Anklet 12 : " + p12.material);
        System.out.println("Material of Anklet 13 : " + p13.material);
        System.out.println("Material of Anklet 14 : " + p14.material);
        System.out.println("Material of Anklet 15 : " + p15.material);
        System.out.println("Material of Anklet 16 : " + p16.material);
        System.out.println("Material of Anklet 17 : " + p17.material);
        System.out.println("Material of Anklet 18 : " + p18.material);
        System.out.println("Material of Anklet 19 : " + p19.material);
        System.out.println("Material of Anklet 20 : " + p20.material);
        System.out.println("Material of Anklet 21 : " + p21.material);
        System.out.println("Material of Anklet 22 : " + p22.material);
        System.out.println("Material of Anklet 23 : " + p23.material);
        System.out.println("Material of Anklet 24 : " + p24.material);
        System.out.println("Material of Anklet 25 : " + p25.material);
    }
}