class AntRunner {
    public static void main(String[] args) {
// default constructor
        Ant a1 = new Ant();
        a1.species = "Fire Ant"; 
		a1.color = "Red"; 
		a1.size = 0.5;
        Ant a2 = new Ant();
        a2.species = "Carpenter Ant"; 
		a2.color = "Black"; 
		a2.size = 1.2;
        Ant a3 = new Ant();
        a3.species = "Leafcutter Ant"; 
		a3.color = "Brown"; 
		a3.size = 0.8;
        Ant a4 = new Ant();
        a4.species = "Army Ant"; 
		a4.color = "Dark Brown"; 
		a4.size = 0.9;
        Ant a5 = new Ant();
        a5.species = "Bullet Ant"; 
		a5.color = "Black"; 
		a5.size = 2.5;
        Ant a6 = new Ant();
        a6.species = "Weaver Ant"; 
		a6.color = "Green"; 
		a6.size = 0.8;
        Ant a7 = new Ant();
        a7.species = "Harvester Ant"; 
		a7.color = "Red"; 
		a7.size = 0.7;
        Ant a8 = new Ant();
        a8.species = "Pavement Ant"; 
		a8.color = "Brown"; 
		a8.size = 0.3;
        Ant a9 = new Ant();
        a9.species = "Odorous Ant"; 
		a9.color = "Black"; 
		a9.size = 0.3;
        Ant a10 = new Ant();
        a10.species = "Argentine Ant"; 
		a10.color = "Light Brown"; 
		a10.size = 0.3;
        Ant a11 = new Ant();
        a11.species = "Ghost Ant"; 
		a11.color = "Pale Yellow"; 
		a11.size = 0.15;
        Ant a12 = new Ant();
        a12.species = "Pharaoh Ant"; 
		a12.color = "Yellow"; 
		a12.size = 0.2;
        Ant a13 = new Ant();
        a13.species = "Crazy Ant"; 
		a13.color = "Reddish Brown"; 
		a13.size = 0.3;
        Ant a14 = new Ant();
        a14.species = "Velvet Ant"; 
		a14.color = "Orange"; 
		a14.size = 1.5;
        Ant a15 = new Ant();
        a15.species = "Black Garden Ant"; 
		a15.color = "Black"; 
		a15.size = 0.4;
        Ant a16 = new Ant();
        a16.species = "Yellow Meadow Ant"; 
		a16.color = "Yellow"; 
		a16.size = 0.4;
        Ant a17 = new Ant();
        a17.species = "Red Wood Ant"; 
		a17.color = "Red"; 
		a17.size = 0.6;
        Ant a18 = new Ant();
        a18.species = "Driver Ant"; 
		a18.color = "Brown"; 
		a18.size = 1.3;
        Ant a19 = new Ant();
        a19.species = "Trap-jaw Ant"; 
		a19.color = "Black"; 
		a19.size = 1.0;
        Ant a20 = new Ant();
        a20.species = "Acrobat Ant"; 
		a20.color = "Brown"; 
		a20.size = 0.3;
        Ant a21 = new Ant();
        a21.species = "Bigheaded Ant"; 
		a21.color = "Red"; 
		a21.size = 0.45;
        Ant a22 = new Ant();
        a22.species = "Rover Ant"; 
		a22.color = "Dark Brown"; 
		a22.size = 0.15;
        Ant a23 = new Ant();
        a23.species = "Formica Ant"; 
		a23.color = "Black"; 
		a23.size = 0.7;
        Ant a24 = new Ant();
        a24.species = "Lasius Ant"; 
		a24.color = "Brown"; 
		a24.size = 0.4;
        Ant a25 = new Ant();
        a25.species = "Camponotus Ant"; 
		a25.color = "Black"; 
		a25.size = 1.5;

        System.out.println("Ant species : " + a1.species + ", color : " + a1.color + ", size : " + a1.size);
        System.out.println("Ant species : " + a2.species + ", color : " + a2.color + ", size : " + a2.size);
        System.out.println("Ant species : " + a3.species + ", color : " + a3.color + ", size : " + a3.size);
        System.out.println("Ant species : " + a4.species + ", color : " + a4.color + ", size : " + a4.size);
        System.out.println("Ant species : " + a5.species + ", color : " + a5.color + ", size : " + a5.size);
        System.out.println("Ant species : " + a6.species + ", color : " + a6.color + ", size : " + a6.size);
        System.out.println("Ant species : " + a7.species + ", color : " + a7.color + ", size : " + a7.size);
        System.out.println("Ant species : " + a8.species + ", color : " + a8.color + ", size : " + a8.size);
        System.out.println("Ant species : " + a9.species + ", color : " + a9.color + ", size : " + a9.size);
        System.out.println("Ant species : " + a10.species + ", color : " + a10.color + ", size : " + a10.size);
        System.out.println("Ant species : " + a11.species + ", color : " + a11.color + ", size : " + a11.size);
        System.out.println("Ant species : " + a12.species + ", color : " + a12.color + ", size : " + a12.size);
        System.out.println("Ant species : " + a13.species + ", color : " + a13.color + ", size : " + a13.size);
        System.out.println("Ant species : " + a14.species + ", color : " + a14.color + ", size : " + a14.size);
        System.out.println("Ant species : " + a15.species + ", color : " + a15.color + ", size : " + a15.size);
        System.out.println("Ant species : " + a16.species + ", color : " + a16.color + ", size : " + a16.size);
        System.out.println("Ant species : " + a17.species + ", color : " + a17.color + ", size : " + a17.size);
        System.out.println("Ant species : " + a18.species + ", color : " + a18.color + ", size : " + a18.size);
        System.out.println("Ant species : " + a19.species + ", color : " + a19.color + ", size : " + a19.size);
        System.out.println("Ant species : " + a20.species + ", color : " + a20.color + ", size : " + a20.size);
        System.out.println("Ant species : " + a21.species + ", color : " + a21.color + ", size : " + a21.size);
        System.out.println("Ant species : " + a22.species + ", color : " + a22.color + ", size : " + a22.size);
        System.out.println("Ant species : " + a23.species + ", color : " + a23.color + ", size : " + a23.size);
        System.out.println("Ant species : " + a24.species + ", color : " + a24.color + ", size : " + a24.size);
        System.out.println("Ant species : " + a25.species + ", color : " + a25.color + ", size : " + a25.size);

// parameterized constructor
        Ant p1 = new Ant("Fire Ant", "Red", 0.5);
        Ant p2 = new Ant("Carpenter Ant", "Black", 1.2);
        Ant p3 = new Ant("Leafcutter Ant", "Brown", 0.8);
        Ant p4 = new Ant("Army Ant", "Dark Brown", 0.9);
        Ant p5 = new Ant("Bullet Ant", "Black", 2.5);
        Ant p6 = new Ant("Weaver Ant", "Green", 0.8);
        Ant p7 = new Ant("Harvester Ant", "Red", 0.7);
        Ant p8 = new Ant("Pavement Ant", "Brown", 0.3);
        Ant p9 = new Ant("Odorous Ant", "Black", 0.3);
        Ant p10 = new Ant("Argentine Ant", "Light Brown", 0.3);
        Ant p11 = new Ant("Ghost Ant", "Pale Yellow", 0.15);
        Ant p12 = new Ant("Pharaoh Ant", "Yellow", 0.2);
        Ant p13 = new Ant("Crazy Ant", "Reddish Brown", 0.3);
        Ant p14 = new Ant("Velvet Ant", "Orange", 1.5);
        Ant p15 = new Ant("Black Garden Ant", "Black", 0.4);
        Ant p16 = new Ant("Yellow Meadow Ant", "Yellow", 0.4);
        Ant p17 = new Ant("Red Wood Ant", "Red", 0.6);
        Ant p18 = new Ant("Driver Ant", "Brown", 1.3);
        Ant p19 = new Ant("Trap-jaw Ant", "Black", 1.0);
        Ant p20 = new Ant("Acrobat Ant", "Brown", 0.3);
        Ant p21 = new Ant("Bigheaded Ant", "Red", 0.45);
        Ant p22 = new Ant("Rover Ant", "Dark Brown", 0.15);
        Ant p23 = new Ant("Formica Ant", "Black", 0.7);
        Ant p24 = new Ant("Lasius Ant", "Brown", 0.4);
        Ant p25 = new Ant("Camponotus Ant", "Black", 1.5);

        System.out.println("Species of Ant 1 : " + p1.species + ", color : " + p1.color + ", size : " + p1.size);
        System.out.println("Species of Ant 2 : " + p2.species + ", color : " + p2.color + ", size : " + p2.size);
        System.out.println("Species of Ant 3 : " + p3.species + ", color : " + p3.color + ", size : " + p3.size);
        System.out.println("Species of Ant 4 : " + p4.species + ", color : " + p4.color + ", size : " + p4.size);
        System.out.println("Species of Ant 5 : " + p5.species + ", color : " + p5.color + ", size : " + p5.size);
        System.out.println("Species of Ant 6 : " + p6.species + ", color : " + p6.color + ", size : " + p6.size);
        System.out.println("Species of Ant 7 : " + p7.species + ", color : " + p7.color + ", size : " + p7.size);
        System.out.println("Species of Ant 8 : " + p8.species + ", color : " + p8.color + ", size : " + p8.size);
        System.out.println("Species of Ant 9 : " + p9.species + ", color : " + p9.color + ", size : " + p9.size);
        System.out.println("Species of Ant 10 : " + p10.species + ", color : " + p10.color + ", size : " + p10.size);
        System.out.println("Species of Ant 11 : " + p11.species + ", color : " + p11.color + ", size : " + p11.size);
        System.out.println("Species of Ant 12 : " + p12.species + ", color : " + p12.color + ", size : " + p12.size);
        System.out.println("Species of Ant 13 : " + p13.species + ", color : " + p13.color + ", size : " + p13.size);
        System.out.println("Species of Ant 14 : " + p14.species + ", color : " + p14.color + ", size : " + p14.size);
        System.out.println("Species of Ant 15 : " + p15.species + ", color : " + p15.color + ", size : " + p15.size);
        System.out.println("Species of Ant 16 : " + p16.species + ", color : " + p16.color + ", size : " + p16.size);
        System.out.println("Species of Ant 17 : " + p17.species + ", color : " + p17.color + ", size : " + p17.size);
        System.out.println("Species of Ant 18 : " + p18.species + ", color : " + p18.color + ", size : " + p18.size);
        System.out.println("Species of Ant 19 : " + p19.species + ", color : " + p19.color + ", size : " + p19.size);
        System.out.println("Species of Ant 20 : " + p20.species + ", color : " + p20.color + ", size : " + p20.size);
        System.out.println("Species of Ant 21 : " + p21.species + ", color : " + p21.color + ", size : " + p21.size);
        System.out.println("Species of Ant 22 : " + p22.species + ", color : " + p22.color + ", size : " + p22.size);
        System.out.println("Species of Ant 23 : " + p23.species + ", color : " + p23.color + ", size : " + p23.size);
        System.out.println("Species of Ant 24 : " + p24.species + ", color : " + p24.color + ", size : " + p24.size);
        System.out.println("Species of Ant 25 : " + p25.species + ", color : " + p25.color + ", size : " + p25.size);
    }
}