class BankExecutor {
    public static void main(String[] args) {
        Bank bank1 = new Bank();
        bank1.setBankName("State Bank of India");
        bank1.setBranch("New Delhi Main");
        bank1.setIfscCode("SBIN0000691");
        bank1.setAccountHolder("Rahul Kumar");
        bank1.setAccountType("Savings");
        bank1.setBalance(45000.50);
        bank1.setContactNumber("9810012345");
        System.out.println("Bank Name: " + bank1.getBankName());
        System.out.println("Branch: " + bank1.getBranch());
        System.out.println("IFSC Code: " + bank1.getIfscCode());
        System.out.println("Account Holder: " + bank1.getAccountHolder());
        System.out.println("Account Type: " + bank1.getAccountType());
        System.out.println("Balance: " + bank1.getBalance());
        System.out.println("Contact Number: " + bank1.getContactNumber());

        Bank bank2 = new Bank();
        bank2.setBankName("HDFC Bank");
        bank2.setBranch("Mumbai");
        bank2.setIfscCode("HDFC0000001");
        bank2.setAccountHolder("Suresh Prabhu");
        bank2.setAccountType("Current");
        bank2.setBalance(120000.00);
        bank2.setContactNumber("9920055443");
        System.out.println("Bank Name: " + bank2.getBankName());
        System.out.println("Branch: " + bank2.getBranch());
        System.out.println("IFSC Code: " + bank2.getIfscCode());
        System.out.println("Account Holder: " + bank2.getAccountHolder());
        System.out.println("Account Type: " + bank2.getAccountType());
        System.out.println("Balance: " + bank2.getBalance());
        System.out.println("Contact Number: " + bank2.getContactNumber());

        Bank bank3 = new Bank();
        bank3.setBankName("ICICI Bank");
        bank3.setBranch("Bangalore - Rajajinagar");
        bank3.setIfscCode("ICIC0001234");
        bank3.setAccountHolder("Ananya Rao");
        bank3.setAccountType("Savings");
        bank3.setBalance(85000.75);
        bank3.setContactNumber("9448001122");
        System.out.println("Bank Name: " + bank3.getBankName());
        System.out.println("Branch: " + bank3.getBranch());
        System.out.println("IFSC Code: " + bank3.getIfscCode());
        System.out.println("Account Holder: " + bank3.getAccountHolder());
        System.out.println("Account Type: " + bank3.getAccountType());
        System.out.println("Balance: " + bank3.getBalance());
        System.out.println("Contact Number: " + bank3.getContactNumber());

        Bank bank4 = new Bank();
        bank4.setBankName("Axis Bank");
        bank4.setBranch("Chennai - Adyar");
        bank4.setIfscCode("UTIB0000456");
        bank4.setAccountHolder("Karthik S");
        bank4.setAccountType("Salary");
        bank4.setBalance(62000.00);
        bank4.setContactNumber("9840112233");
        System.out.println("Bank Name: " + bank4.getBankName());
        System.out.println("Branch: " + bank4.getBranch());
        System.out.println("IFSC Code: " + bank4.getIfscCode());
        System.out.println("Account Holder: " + bank4.getAccountHolder());
        System.out.println("Account Type: " + bank4.getAccountType());
        System.out.println("Balance: " + bank4.getBalance());
        System.out.println("Contact Number: " + bank4.getContactNumber());

        Bank bank5 = new Bank();
        bank5.setBankName("Punjab National Bank");
        bank5.setBranch("Amritsar - Hall Gate");
        bank5.setIfscCode("PUNB0123400");
        bank5.setAccountHolder("Harpreet Singh");
        bank5.setAccountType("Savings");
        bank5.setBalance(31000.20);
        bank5.setContactNumber("9872012345");
        System.out.println("Bank Name: " + bank5.getBankName());
        System.out.println("Branch: " + bank5.getBranch());
        System.out.println("IFSC Code: " + bank5.getIfscCode());
        System.out.println("Account Holder: " + bank5.getAccountHolder());
        System.out.println("Account Type: " + bank5.getAccountType());
        System.out.println("Balance: " + bank5.getBalance());
        System.out.println("Contact Number: " + bank5.getContactNumber());

        Bank bank6 = new Bank();
        bank6.setBankName("Canara Bank");
        bank6.setBranch("Hubli Main");
        bank6.setIfscCode("CNRB0000789");
        bank6.setAccountHolder("Ganesh Hegde");
        bank6.setAccountType("Joint");
        bank6.setBalance(150000.00);
        bank6.setContactNumber("9900115566");
        System.out.println("Bank Name: " + bank6.getBankName());
        System.out.println("Branch: " + bank6.getBranch());
        System.out.println("IFSC Code: " + bank6.getIfscCode());
        System.out.println("Account Holder: " + bank6.getAccountHolder());
        System.out.println("Account Type: " + bank6.getAccountType());
        System.out.println("Balance: " + bank6.getBalance());
        System.out.println("Contact Number: " + bank6.getContactNumber());

        Bank bank7 = new Bank();
        bank7.setBankName("Bank of Baroda");
        bank7.setBranch("Ahmedabad - Alkapuri");
        bank7.setIfscCode("BARB0SURAT");
        bank7.setAccountHolder("Pritesh Patel");
        bank7.setAccountType("Current");
        bank7.setBalance(250000.00);
        bank7.setContactNumber("9724011223");
        System.out.println("Bank Name: " + bank7.getBankName());
        System.out.println("Branch: " + bank7.getBranch());
        System.out.println("IFSC Code: " + bank7.getIfscCode());
        System.out.println("Account Holder: " + bank7.getAccountHolder());
        System.out.println("Account Type: " + bank7.getAccountType());
        System.out.println("Balance: " + bank7.getBalance());
        System.out.println("Contact Number: " + bank7.getContactNumber());

        Bank bank8 = new Bank();
        bank8.setBankName("Kotak Mahindra Bank");
        bank8.setBranch("Pune - FC Road");
        bank8.setIfscCode("KKBK0000958");
        bank8.setAccountHolder("Neha Deshpande");
        bank8.setAccountType("Savings");
        bank8.setBalance(42000.00);
        bank8.setContactNumber("9822012345");
        System.out.println("Bank Name: " + bank8.getBankName());
        System.out.println("Branch: " + bank8.getBranch());
        System.out.println("IFSC Code: " + bank8.getIfscCode());
        System.out.println("Account Holder: " + bank8.getAccountHolder());
        System.out.println("Account Type: " + bank8.getAccountType());
        System.out.println("Balance: " + bank8.getBalance());
        System.out.println("Contact Number: " + bank8.getContactNumber());

        Bank bank9 = new Bank();
        bank9.setBankName("IndusInd Bank");
        bank9.setBranch("Hyderabad - Banjara Hills");
        bank9.setIfscCode("INDB0000123");
        bank9.setAccountHolder("Rajesh Reddy");
        bank9.setAccountType("Savings");
        bank9.setBalance(96000.00);
        bank9.setContactNumber("9949011223");
        System.out.println("Bank Name: " + bank9.getBankName());
        System.out.println("Branch: " + bank9.getBranch());
        System.out.println("IFSC Code: " + bank9.getIfscCode());
        System.out.println("Account Holder: " + bank9.getAccountHolder());
        System.out.println("Account Type: " + bank9.getAccountType());
        System.out.println("Balance: " + bank9.getBalance());
        System.out.println("Contact Number: " + bank9.getContactNumber());

        Bank bank10 = new Bank();
        bank10.setBankName("Union Bank of India");
        bank10.setBranch("Lucknow Main");
        bank10.setIfscCode("UBIN0531234");
        bank10.setAccountHolder("Amit Srivastava");
        bank10.setAccountType("Salary");
        bank10.setBalance(55000.00);
        bank10.setContactNumber("9415012345");
        System.out.println("Bank Name: " + bank10.getBankName());
        System.out.println("Branch: " + bank10.getBranch());
        System.out.println("IFSC Code: " + bank10.getIfscCode());
        System.out.println("Account Holder: " + bank10.getAccountHolder());
        System.out.println("Account Type: " + bank10.getAccountType());
        System.out.println("Balance: " + bank10.getBalance());
        System.out.println("Contact Number: " + bank10.getContactNumber());

        Bank bank11 = new Bank();
        bank11.setBankName("IDBI Bank");
        bank11.setBranch("Patna - Boring Road");
        bank11.setIfscCode("IBKL0000456");
        bank11.setAccountHolder("Manoj Bajpayee");
        bank11.setAccountType("Savings");
        bank11.setBalance(15000.00);
        bank11.setContactNumber("9934011223");
        System.out.println("Bank Name: " + bank11.getBankName());
        System.out.println("Branch: " + bank11.getBranch());
        System.out.println("IFSC Code: " + bank11.getIfscCode());
        System.out.println("Account Holder: " + bank11.getAccountHolder());
        System.out.println("Account Type: " + bank11.getAccountType());
        System.out.println("Balance: " + bank11.getBalance());
        System.out.println("Contact Number: " + bank11.getContactNumber());

        Bank bank12 = new Bank();
        bank12.setBankName("Federal Bank");
        bank12.setBranch("Kochi - Aluva");
        bank12.setIfscCode("FDRL0001234");
        bank12.setAccountHolder("Thomas Kutty");
        bank12.setAccountType("Savings");
        bank12.setBalance(78000.00);
        bank12.setContactNumber("9447012345");
        System.out.println("Bank Name: " + bank12.getBankName());
        System.out.println("Branch: " + bank12.getBranch());
        System.out.println("IFSC Code: " + bank12.getIfscCode());
        System.out.println("Account Holder: " + bank12.getAccountHolder());
        System.out.println("Account Type: " + bank12.getAccountType());
        System.out.println("Balance: " + bank12.getBalance());
        System.out.println("Contact Number: " + bank12.getContactNumber());

        Bank bank13 = new Bank();
        bank13.setBankName("South Indian Bank");
        bank13.setBranch("Thrissur Main");
        bank13.setIfscCode("SIBL0000001");
        bank13.setAccountHolder("Mary Joseph");
        bank13.setAccountType("Savings");
        bank13.setBalance(12000.00);
        bank13.setContactNumber("9847011223");
        System.out.println("Bank Name: " + bank13.getBankName());
        System.out.println("Branch: " + bank13.getBranch());
        System.out.println("IFSC Code: " + bank13.getIfscCode());
        System.out.println("Account Holder: " + bank13.getAccountHolder());
        System.out.println("Account Type: " + bank13.getAccountType());
        System.out.println("Balance: " + bank13.getBalance());
        System.out.println("Contact Number: " + bank13.getContactNumber());

        Bank bank14 = new Bank();
        bank14.setBankName("Yes Bank");
        bank14.setBranch("Gurgaon - Sector 44");
        bank14.setIfscCode("YESB0000001");
        bank14.setAccountHolder("Vikram Oberoi");
        bank14.setAccountType("Current");
        bank14.setBalance(500000.00);
        bank14.setContactNumber("9811012345");
        System.out.println("Bank Name: " + bank14.getBankName());
        System.out.println("Branch: " + bank14.getBranch());
        System.out.println("IFSC Code: " + bank14.getIfscCode());
        System.out.println("Account Holder: " + bank14.getAccountHolder());
        System.out.println("Account Type: " + bank14.getAccountType());
        System.out.println("Balance: " + bank14.getBalance());
        System.out.println("Contact Number: " + bank14.getContactNumber());

        Bank bank15 = new Bank();
        bank15.setBankName("RBL Bank");
        bank15.setBranch("Kolhapur Main");
        bank15.setIfscCode("RATN0000001");
        bank15.setAccountHolder("Sanjay Jadhav");
        bank15.setAccountType("Savings");
        bank15.setBalance(22000.00);
        bank15.setContactNumber("9422012345");
        System.out.println("Bank Name: " + bank15.getBankName());
        System.out.println("Branch: " + bank15.getBranch());
        System.out.println("IFSC Code: " + bank15.getIfscCode());
        System.out.println("Account Holder: " + bank15.getAccountHolder());
        System.out.println("Account Type: " + bank15.getAccountType());
        System.out.println("Balance: " + bank15.getBalance());
        System.out.println("Contact Number: " + bank15.getContactNumber());

        Bank bank16 = new Bank();
        bank16.setBankName("UCO Bank");
        bank16.setBranch("Kolkata - Salt Lake");
        bank16.setIfscCode("UCBA0000123");
        bank16.setAccountHolder("Subhash Chatterjee");
        bank16.setAccountType("Pension");
        bank16.setBalance(8500.00);
        bank16.setContactNumber("9830012345");
        System.out.println("Bank Name: " + bank16.getBankName());
        System.out.println("Branch: " + bank16.getBranch());
        System.out.println("IFSC Code: " + bank16.getIfscCode());
        System.out.println("Account Holder: " + bank16.getAccountHolder());
        System.out.println("Account Type: " + bank16.getAccountType());
        System.out.println("Balance: " + bank16.getBalance());
        System.out.println("Contact Number: " + bank16.getContactNumber());

        Bank bank17 = new Bank();
        bank17.setBankName("Indian Bank");
        bank17.setBranch("Chennai - Mylapore");
        bank17.setIfscCode("IDIB000M123");
        bank17.setAccountHolder("Lakshmi Narayan");
        bank17.setAccountType("Savings");
        bank17.setBalance(44000.00);
        bank17.setContactNumber("9444012345");
        System.out.println("Bank Name: " + bank17.getBankName());
        System.out.println("Branch: " + bank17.getBranch());
        System.out.println("IFSC Code: " + bank17.getIfscCode());
        System.out.println("Account Holder: " + bank17.getAccountHolder());
        System.out.println("Account Type: " + bank17.getAccountType());
        System.out.println("Balance: " + bank17.getBalance());
        System.out.println("Contact Number: " + bank17.getContactNumber());

        Bank bank18 = new Bank();
        bank18.setBankName("Bandhan Bank");
        bank18.setBranch("Guwahati Main");
        bank18.setIfscCode("BDBL0000001");
        bank18.setAccountHolder("Jatin Bora");
        bank18.setAccountType("Savings");
        bank18.setBalance(18000.00);
        bank18.setContactNumber("9954012345");
        System.out.println("Bank Name: " + bank18.getBankName());
        System.out.println("Branch: " + bank18.getBranch());
        System.out.println("IFSC Code: " + bank18.getIfscCode());
        System.out.println("Account Holder: " + bank18.getAccountHolder());
        System.out.println("Account Type: " + bank18.getAccountType());
        System.out.println("Balance: " + bank18.getBalance());
        System.out.println("Contact Number: " + bank18.getContactNumber());

        Bank bank19 = new Bank();
        bank19.setBankName("Standard Chartered");
        bank19.setBranch("Mumbai - Fort");
        bank19.setIfscCode("SCBL0036001");
        bank19.setAccountHolder("Farhan Akhtar");
        bank19.setAccountType("Wealth");
        bank19.setBalance(1500000.00);
        bank19.setContactNumber("9921012345");
        System.out.println("Bank Name: " + bank19.getBankName());
        System.out.println("Branch: " + bank19.getBranch());
        System.out.println("IFSC Code: " + bank19.getIfscCode());
        System.out.println("Account Holder: " + bank19.getAccountHolder());
        System.out.println("Account Type: " + bank19.getAccountType());
        System.out.println("Balance: " + bank19.getBalance());
        System.out.println("Contact Number: " + bank19.getContactNumber());

        Bank bank20 = new Bank();
        bank20.setBankName("IDFC First Bank");
        bank20.setBranch("Bangalore - Indiranagar");
        bank20.setIfscCode("IDFB0080123");
        bank20.setAccountHolder("Kunal Shah");
        bank20.setAccountType("Savings");
        bank20.setBalance(320000.00);
        bank20.setContactNumber("9886012345");
        System.out.println("Bank Name: " + bank20.getBankName());
        System.out.println("Branch: " + bank20.getBranch());
        System.out.println("IFSC Code: " + bank20.getIfscCode());
        System.out.println("Account Holder: " + bank20.getAccountHolder());
        System.out.println("Account Type: " + bank20.getAccountType());
        System.out.println("Balance: " + bank20.getBalance());
        System.out.println("Contact Number: " + bank20.getContactNumber());

        Bank bank21 = new Bank();
        bank21.setBankName("Karnataka Bank");
        bank21.setBranch("Mangalore Main");
        bank21.setIfscCode("KARB0000450");
        bank21.setAccountHolder("Shiva Kumar");
        bank21.setAccountType("Savings");
        bank21.setBalance(65000.00);
        bank21.setContactNumber("9448012345");
        System.out.println("Bank Name: " + bank21.getBankName());
        System.out.println("Branch: " + bank21.getBranch());
        System.out.println("IFSC Code: " + bank21.getIfscCode());
        System.out.println("Account Holder: " + bank21.getAccountHolder());
        System.out.println("Account Type: " + bank21.getAccountType());
        System.out.println("Balance: " + bank21.getBalance());
        System.out.println("Contact Number: " + bank21.getContactNumber());

        Bank bank22 = new Bank();
        bank22.setBankName("Karur Vysya Bank");
        bank22.setBranch("Karur Main");
        bank22.setIfscCode("KVBL0001101");
        bank22.setAccountHolder("Sundaram V");
        bank22.setAccountType("Savings");
        bank22.setBalance(45000.00);
        bank22.setContactNumber("9443012345");
        System.out.println("Bank Name: " + bank22.getBankName());
        System.out.println("Branch: " + bank22.getBranch());
        System.out.println("IFSC Code: " + bank22.getIfscCode());
        System.out.println("Account Holder: " + bank22.getAccountHolder());
        System.out.println("Account Type: " + bank22.getAccountType());
        System.out.println("Balance: " + bank22.getBalance());
        System.out.println("Contact Number: " + bank22.getContactNumber());

        Bank bank23 = new Bank();
        bank23.setBankName("DBS Bank");
        bank23.setBranch("Mumbai Main");
        bank23.setIfscCode("DBSS0IN0123");
        bank23.setAccountHolder("Kiara Advani");
        bank23.setAccountType("Savings");
        bank23.setBalance(21000.00);
        bank23.setContactNumber("9820011223");
        System.out.println("Bank Name: " + bank23.getBankName());
        System.out.println("Branch: " + bank23.getBranch());
        System.out.println("IFSC Code: " + bank23.getIfscCode());
        System.out.println("Account Holder: " + bank23.getAccountHolder());
        System.out.println("Account Type: " + bank23.getAccountType());
        System.out.println("Balance: " + bank23.getBalance());
        System.out.println("Contact Number: " + bank23.getContactNumber());

        Bank bank24 = new Bank();
        bank24.setBankName("State Bank of India");
        bank24.setBranch("Bhopal Main");
        bank24.setIfscCode("SBIN0000001");
        bank24.setAccountHolder("Shivraj Singh");
        bank24.setAccountType("Savings");
        bank24.setBalance(89000.00);
        bank24.setContactNumber("9425012345");
        System.out.println("Bank Name: " + bank24.getBankName());
        System.out.println("Branch: " + bank24.getBranch());
        System.out.println("IFSC Code: " + bank24.getIfscCode());
        System.out.println("Account Holder: " + bank24.getAccountHolder());
        System.out.println("Account Type: " + bank24.getAccountType());
        System.out.println("Balance: " + bank24.getBalance());
        System.out.println("Contact Number: " + bank24.getContactNumber());

        Bank bank25 = new Bank();
        bank25.setBankName("HDFC Bank");
        bank25.setBranch("Indore - Vijay Nagar");
        bank25.setIfscCode("HDFC0000123");
        bank25.setAccountHolder("Ishan Kishan");
        bank25.setAccountType("Salary");
        bank25.setBalance(125000.00);
        bank25.setContactNumber("9977012345");
        System.out.println("Bank Name: " + bank25.getBankName());
        System.out.println("Branch: " + bank25.getBranch());
        System.out.println("IFSC Code: " + bank25.getIfscCode());
        System.out.println("Account Holder: " + bank25.getAccountHolder());
        System.out.println("Account Type: " + bank25.getAccountType());
        System.out.println("Balance: " + bank25.getBalance());
        System.out.println("Contact Number: " + bank25.getContactNumber());

        Bank bank26 = new Bank();
        bank26.setBankName("ICICI Bank");
        bank26.setBranch("Jaipur - C Scheme");
        bank26.setIfscCode("ICIC0000001");
        bank26.setAccountHolder("Vasundhara Raje");
        bank26.setAccountType("Savings");
        bank26.setBalance(74000.00);
        bank26.setContactNumber("9829012345");
        System.out.println("Bank Name: " + bank26.getBankName());
        System.out.println("Branch: " + bank26.getBranch());
        System.out.println("IFSC Code: " + bank26.getIfscCode());
        System.out.println("Account Holder: " + bank26.getAccountHolder());
        System.out.println("Account Type: " + bank26.getAccountType());
        System.out.println("Balance: " + bank26.getBalance());
        System.out.println("Contact Number: " + bank26.getContactNumber());

        Bank bank27 = new Bank();
        bank27.setBankName("Axis Bank");
        bank27.setBranch("Ranchi - Main Road");
        bank27.setIfscCode("UTIB0000123");
        bank27.setAccountHolder("Sakshi Dhoni");
        bank27.setAccountType("Savings");
        bank27.setBalance(110000.00);
        bank27.setContactNumber("9931012345");
        System.out.println("Bank Name: " + bank27.getBankName());
        System.out.println("Branch: " + bank27.getBranch());
        System.out.println("IFSC Code: " + bank27.getIfscCode());
        System.out.println("Account Holder: " + bank27.getAccountHolder());
        System.out.println("Account Type: " + bank27.getAccountType());
        System.out.println("Balance: " + bank27.getBalance());
        System.out.println("Contact Number: " + bank27.getContactNumber());

        Bank bank28 = new Bank();
        bank28.setBankName("Bank of Maharashtra");
        bank28.setBranch("Pune - Shivaji Nagar");
        bank28.setIfscCode("MAHB0000001");
        bank28.setAccountHolder("Sharad Pawar");
        bank28.setAccountType("Savings");
        bank28.setBalance(30000.00);
        bank28.setContactNumber("9823012345");
        System.out.println("Bank Name: " + bank28.getBankName());
        System.out.println("Branch: " + bank28.getBranch());
        System.out.println("IFSC Code: " + bank28.getIfscCode());
        System.out.println("Account Holder: " + bank28.getAccountHolder());
        System.out.println("Account Type: " + bank28.getAccountType());
        System.out.println("Balance: " + bank28.getBalance());
        System.out.println("Contact Number: " + bank28.getContactNumber());

        Bank bank29 = new Bank();
        bank29.setBankName("Ujjivan Small Finance");
        bank29.setBranch("Bangalore South");
        bank29.setIfscCode("UJJV0001234");
        bank29.setAccountHolder("Mohan Lal");
        bank29.setAccountType("Savings");
        bank29.setBalance(5000.00);
        bank29.setContactNumber("9845011223");
        System.out.println("Bank Name: " + bank29.getBankName());
        System.out.println("Branch: " + bank29.getBranch());
        System.out.println("IFSC Code: " + bank29.getIfscCode());
        System.out.println("Account Holder: " + bank29.getAccountHolder());
        System.out.println("Account Type: " + bank29.getAccountType());
        System.out.println("Balance: " + bank29.getBalance());
        System.out.println("Contact Number: " + bank29.getContactNumber());
    }
}