class BlanketRunner {
    public static void main(String[] args) {
// default constructor
        Blanket b1 = new Blanket();
        b1.brand = "Snuggle"; b1.color = "Red"; b1.material = "Fleece"; 
		b1.length = 150.0; b1.width = 100.0; b1.weight = 1.0;
        Blanket b2 = new Blanket();
        b2.brand = "Cozy"; b2.color = "Blue"; b2.material = "Cotton"; 
		b2.length = 160.0; b2.width = 110.0; b2.weight = 1.2;
        Blanket b3 = new Blanket();
        b3.brand = "WarmUp"; b3.color = "Green"; b3.material = "Wool"; 
		b3.length = 170.0; b3.width = 120.0; b3.weight = 1.5;
        Blanket b4 = new Blanket();
        b4.brand = "SoftTouch"; b4.color = "Yellow"; 
		b4.material = "Polyester"; b4.length = 155.0; b4.width = 105.0; b4.weight = 0.9;
        Blanket b5 = new Blanket();
        b5.brand = "DreamSoft"; b5.color = "Pink"; 
		b5.material = "Microfiber"; b5.length = 165.0; b5.width = 115.0; b5.weight = 1.1;
        Blanket b6 = new Blanket();
        b6.brand = "CloudNine"; b6.color = "White"; 
		b6.material = "Silk"; b6.length = 180.0; b6.width = 130.0; b6.weight = 0.8;
        Blanket b7 = new Blanket();
        b7.brand = "HugMe"; b7.color = "Gray"; 
		
		b7.width = 95.0; b7.weight = 1.3;
        
		
        
		b8.material = "Fleece"; b8.length = 175.0; 
		b8.width = 125.0; b8.weight = 1.4;
        Blanket b9 = new Blanket();
        b9.brand = "PureComfort"; b9.color = "Navy"; 
		b9.material = "Cotton"; b9.length = 162.0; b9.width = 112.0; b9.weight = 1.6;
        Blanket b10 = new Blanket();
        b10.brand = "VelvetDream"; b10.color = "Purple"; 
		b10.material = "Velvet"; b10.length = 158.0; b10.width = 108.0; b10.weight = 1.7;
        Blanket b11 = new Blanket();
        b11.brand = "FurEver"; b11.color = "Brown"; 
		b11.material = "Faux Fur"; b11.length = 152.0; b11.width = 102.0; b11.weight = 2.0;
        Blanket b12 = new Blanket();
        b12.brand = "SilkRoad"; b12.color = "Ivory"; 
		b12.material = "Silk"; b12.length = 185.0; b12.width = 135.0; b12.weight = 0.7;
        Blanket b13 = new Blanket();
        b13.brand = "KnitWarm"; b13.color = "Beige"; 
		b13.material = "Knit"; b13.length = 168.0; b13.width = 118.0; b13.weight = 1.8;
        Blanket b14 = new Blanket();
        b14.brand = "BambooLife"; b14.color = "Teal"; 
		b14.material = "Bamboo"; b14.length = 172.0; b14.width = 122.0; b14.weight = 1.0;
        Blanket b15 = new Blanket();
        b15.brand = "LuxeWrap"; b15.color = "Coral"; 
		b15.material = "Cashmere"; b15.length = 190.0; b15.width = 140.0; b15.weight = 0.9;
        Blanket b16 = new Blanket();
        b16.brand = "SleepWell"; b16.color = "Orange"; 
		b16.material = "Polyester"; b16.length = 148.0; b16.width = 98.0; b16.weight = 1.2;
        Blanket b17 = new Blanket();
        b17.brand = "HeavyDuty"; b17.color = "Maroon"; 
		b17.material = "Denim"; b17.length = 195.0; b17.width = 145.0; b17.weight = 2.5;
        Blanket b18 = new Blanket();
        b18.brand = "MiniCozy"; b18.color = "Lime"; 
		b18.material = "Fleece"; b18.length = 100.0; b18.width = 75.0; b18.weight = 0.5;
        Blanket b19 = new Blanket();
        b19.brand = "ThermalPro"; b19.color = "Charcoal"; 
		b19.material = "Thermal"; b19.length = 182.0; b19.width = 132.0; b19.weight = 2.2;
        Blanket b20 = new Blanket();
        b20.brand = "WoolBliss"; b20.color = "Tan"; 
		b20.material = "Merino Wool"; b20.length = 178.0; b20.width = 128.0; b20.weight = 1.9;
        Blanket b21 = new Blanket();
        b21.brand = "DownFeather"; b21.color = "Cream"; 
		b21.material = "Down"; b21.length = 200.0; b21.width = 150.0; b21.weight = 0.6;
        Blanket b22 = new Blanket();
        b22.brand = "SpinWool"; b22.color = "Gold"; 
		b22.material = "Wool Blend"; b22.length = 176.0; b22.width = 126.0; b22.weight = 1.3;
        Blanket b23 = new Blanket();
        b23.brand = "CoolBreeze"; b23.color = "Cyan"; 
		b23.material = "Linen"; b23.length = 166.0; b23.width = 116.0; b23.weight = 0.8;
        Blanket b24 = new Blanket();
        b24.brand = "PolarFleece"; b24.color = "Silver"; 
		b24.material = "Polar Fleece"; b24.length = 188.0; b24.width = 138.0; b24.weight = 1.6;
        Blanket b25 = new Blanket();
        b25.brand = "HeritageLoom"; b25.color = "Indigo"; 
		b25.material = "Woven Cotton"; b25.length = 192.0; b25.width = 142.0; b25.weight = 2.1;

        System.out.println("Blanket brand : " + b1.brand + ", color : " + b1.color + ", material : " + b1.material + ", length : " + b1.length + ", width : " + b1.width + ", weight : " + b1.weight);
        System.out.println("Blanket brand : " + b2.brand + ", color : " + b2.color + ", material : " + b2.material + ", length : " + b2.length + ", width : " + b2.width + ", weight : " + b2.weight);
        System.out.println("Blanket brand : " + b3.brand + ", color : " + b3.color + ", material : " + b3.material + ", length : " + b3.length + ", width : " + b3.width + ", weight : " + b3.weight);
        System.out.println("Blanket brand : " + b4.brand + ", color : " + b4.color + ", material : " + b4.material + ", length : " + b4.length + ", width : " + b4.width + ", weight : " + b4.weight);
        System.out.println("Blanket brand : " + b5.brand + ", color : " + b5.color + ", material : " + b5.material + ", length : " + b5.length + ", width : " + b5.width + ", weight : " + b5.weight);
        System.out.println("Blanket brand : " + b6.brand + ", color : " + b6.color + ", material : " + b6.material + ", length : " + b6.length + ", width : " + b6.width + ", weight : " + b6.weight);
        System.out.println("Blanket brand : " + b7.brand + ", color : " + b7.color + ", material : " + b7.material + ", length : " + b7.length + ", width : " + b7.width + ", weight : " + b7.weight);
        System.out.println("Blanket brand : " + b8.brand + ", color : " + b8.color + ", material : " + b8.material + ", length : " + b8.length + ", width : " + b8.width + ", weight : " + b8.weight);
        System.out.println("Blanket brand : " + b9.brand + ", color : " + b9.color + ", material : " + b9.material + ", length : " + b9.length + ", width : " + b9.width + ", weight : " + b9.weight);
        System.out.println("Blanket brand : " + b10.brand + ", color : " + b10.color + ", material : " + b10.material + ", length : " + b10.length + ", width : " + b10.width + ", weight : " + b10.weight);
        System.out.println("Blanket brand : " + b11.brand + ", color : " + b11.color + ", material : " + b11.material + ", length : " + b11.length + ", width : " + b11.width + ", weight : " + b11.weight);
        System.out.println("Blanket brand : " + b12.brand + ", color : " + b12.color + ", material : " + b12.material + ", length : " + b12.length + ", width : " + b12.width + ", weight : " + b12.weight);
        System.out.println("Blanket brand : " + b13.brand + ", color : " + b13.color + ", material : " + b13.material + ", length : " + b13.length + ", width : " + b13.width + ", weight : " + b13.weight);
        System.out.println("Blanket brand : " + b14.brand + ", color : " + b14.color + ", material : " + b14.material + ", length : " + b14.length + ", width : " + b14.width + ", weight : " + b14.weight);
        System.out.println("Blanket brand : " + b15.brand + ", color : " + b15.color + ", material : " + b15.material + ", length : " + b15.length + ", width : " + b15.width + ", weight : " + b15.weight);
        System.out.println("Blanket brand : " + b16.brand + ", color : " + b16.color + ", material : " + b16.material + ", length : " + b16.length + ", width : " + b16.width + ", weight : " + b16.weight);
        System.out.println("Blanket brand : " + b17.brand + ", color : " + b17.color + ", material : " + b17.material + ", length : " + b17.length + ", width : " + b17.width + ", weight : " + b17.weight);
        System.out.println("Blanket brand : " + b18.brand + ", color : " + b18.color + ", material : " + b18.material + ", length : " + b18.length + ", width : " + b18.width + ", weight : " + b18.weight);
        System.out.println("Blanket brand : " + b19.brand + ", color : " + b19.color + ", material : " + b19.material + ", length : " + b19.length + ", width : " + b19.width + ", weight : " + b19.weight);
        System.out.println("Blanket brand : " + b20.brand + ", color : " + b20.color + ", material : " + b20.material + ", length : " + b20.length + ", width : " + b20.width + ", weight : " + b20.weight);
        System.out.println("Blanket brand : " + b21.brand + ", color : " + b21.color + ", material : " + b21.material + ", length : " + b21.length + ", width : " + b21.width + ", weight : " + b21.weight);
        System.out.println("Blanket brand : " + b22.brand + ", color : " + b22.color + ", material : " + b22.material + ", length : " + b22.length + ", width : " + b22.width + ", weight : " + b22.weight);
        System.out.println("Blanket brand : " + b23.brand + ", color : " + b23.color + ", material : " + b23.material + ", length : " + b23.length + ", width : " + b23.width + ", weight : " + b23.weight);
        System.out.println("Blanket brand : " + b24.brand + ", color : " + b24.color + ", material : " + b24.material + ", length : " + b24.length + ", width : " + b24.width + ", weight : " + b24.weight);
        System.out.println("Blanket brand : " + b25.brand + ", color : " + b25.color + ", material : " + b25.material + ", length : " + b25.length + ", width : " + b25.width + ", weight : " + b25.weight);

// parameterized constructor
        Blanket p1 = new Blanket("Snuggle", "Red", "Fleece", 150.0, 100.0, 1.0);
        Blanket p2 = new Blanket("Cozy", "Blue", "Cotton", 160.0, 110.0, 1.2);
        Blanket p3 = new Blanket("WarmUp", "Green", "Wool", 170.0, 120.0, 1.5);
        Blanket p4 = new Blanket("SoftTouch", "Yellow", "Polyester", 155.0, 105.0, 0.9);
        Blanket p5 = new Blanket("DreamSoft", "Pink", "Microfiber", 165.0, 115.0, 1.1);
        Blanket p6 = new Blanket("CloudNine", "White", "Silk", 180.0, 130.0, 0.8);
        Blanket p7 = new Blanket("HugMe", "Gray", "Acrylic", 145.0, 95.0, 1.3);
        Blanket p8 = new Blanket("NightRest", "Black", "Fleece", 175.0, 125.0, 1.4);
        Blanket p9 = new Blanket("PureComfort", "Navy", "Cotton", 162.0, 112.0, 1.6);
        Blanket p10 = new Blanket("VelvetDream", "Purple", "Velvet", 158.0, 108.0, 1.7);
        Blanket p11 = new Blanket("FurEver", "Brown", "Faux Fur", 152.0, 102.0, 2.0);
        Blanket p12 = new Blanket("SilkRoad", "Ivory", "Silk", 185.0, 135.0, 0.7);
        Blanket p13 = new Blanket("KnitWarm", "Beige", "Knit", 168.0, 118.0, 1.8);
        Blanket p14 = new Blanket("BambooLife", "Teal", "Bamboo", 172.0, 122.0, 1.0);
        Blanket p15 = new Blanket("LuxeWrap", "Coral", "Cashmere", 190.0, 140.0, 0.9);
        Blanket p16 = new Blanket("SleepWell", "Orange", "Polyester", 148.0, 98.0, 1.2);
        Blanket p17 = new Blanket("HeavyDuty", "Maroon", "Denim", 195.0, 145.0, 2.5);
        Blanket p18 = new Blanket("MiniCozy", "Lime", "Fleece", 100.0, 75.0, 0.5);
        Blanket p19 = new Blanket("ThermalPro", "Charcoal", "Thermal", 182.0, 132.0, 2.2);
        Blanket p20 = new Blanket("WoolBliss", "Tan", "Merino Wool", 178.0, 128.0, 1.9);
        Blanket p21 = new Blanket("DownFeather", "Cream", "Down", 200.0, 150.0, 0.6);
        Blanket p22 = new Blanket("SpinWool", "Gold", "Wool Blend", 176.0, 126.0, 1.3);
        Blanket p23 = new Blanket("CoolBreeze", "Cyan", "Linen", 166.0, 116.0, 0.8);
        Blanket p24 = new Blanket("PolarFleece", "Silver", "Polar Fleece", 188.0, 138.0, 1.6);
        Blanket p25 = new Blanket("HeritageLoom", "Indigo", "Woven Cotton", 192.0, 142.0, 2.1);

        System.out.println("Brand of Blanket 1 : " + p1.brand + ", color : " + p1.color + ", material : " + p1.material + ", length : " + p1.length + ", width : " + p1.width + ", weight : " + p1.weight);
        System.out.println("Brand of Blanket 2 : " + p2.brand + ", color : " + p2.color + ", material : " + p2.material + ", length : " + p2.length + ", width : " + p2.width + ", weight : " + p2.weight);
        System.out.println("Brand of Blanket 3 : " + p3.brand + ", color : " + p3.color + ", material : " + p3.material + ", length : " + p3.length + ", width : " + p3.width + ", weight : " + p3.weight);
        System.out.println("Brand of Blanket 4 : " + p4.brand + ", color : " + p4.color + ", material : " + p4.material + ", length : " + p4.length + ", width : " + p4.width + ", weight : " + p4.weight);
        System.out.println("Brand of Blanket 5 : " + p5.brand + ", color : " + p5.color + ", material : " + p5.material + ", length : " + p5.length + ", width : " + p5.width + ", weight : " + p5.weight);
        System.out.println("Brand of Blanket 6 : " + p6.brand + ", color : " + p6.color + ", material : " + p6.material + ", length : " + p6.length + ", width : " + p6.width + ", weight : " + p6.weight);
        System.out.println("Brand of Blanket 7 : " + p7.brand + ", color : " + p7.color + ", material : " + p7.material + ", length : " + p7.length + ", width : " + p7.width + ", weight : " + p7.weight);
        System.out.println("Brand of Blanket 8 : " + p8.brand + ", color : " + p8.color + ", material : " + p8.material + ", length : " + p8.length + ", width : " + p8.width + ", weight : " + p8.weight);
        System.out.println("Brand of Blanket 9 : " + p9.brand + ", color : " + p9.color + ", material : " + p9.material + ", length : " + p9.length + ", width : " + p9.width + ", weight : " + p9.weight);
        System.out.println("Brand of Blanket 10 : " + p10.brand + ", color : " + p10.color + ", material : " + p10.material + ", length : " + p10.length + ", width : " + p10.width + ", weight : " + p10.weight);
        System.out.println("Brand of Blanket 11 : " + p11.brand + ", color : " + p11.color + ", material : " + p11.material + ", length : " + p11.length + ", width : " + p11.width + ", weight : " + p11.weight);
        System.out.println("Brand of Blanket 12 : " + p12.brand + ", color : " + p12.color + ", material : " + p12.material + ", length : " + p12.length + ", width : " + p12.width + ", weight : " + p12.weight);
        System.out.println("Brand of Blanket 13 : " + p13.brand + ", color : " + p13.color + ", material : " + p13.material + ", length : " + p13.length + ", width : " + p13.width + ", weight : " + p13.weight);
        System.out.println("Brand of Blanket 14 : " + p14.brand + ", color : " + p14.color + ", material : " + p14.material + ", length : " + p14.length + ", width : " + p14.width + ", weight : " + p14.weight);
        System.out.println("Brand of Blanket 15 : " + p15.brand + ", color : " + p15.color + ", material : " + p15.material + ", length : " + p15.length + ", width : " + p15.width + ", weight : " + p15.weight);
        System.out.println("Brand of Blanket 16 : " + p16.brand + ", color : " + p16.color + ", material : " + p16.material + ", length : " + p16.length + ", width : " + p16.width + ", weight : " + p16.weight);
        System.out.println("Brand of Blanket 17 : " + p17.brand + ", color : " + p17.color + ", material : " + p17.material + ", length : " + p17.length + ", width : " + p17.width + ", weight : " + p17.weight);
        System.out.println("Brand of Blanket 18 : " + p18.brand + ", color : " + p18.color + ", material : " + p18.material + ", length : " + p18.length + ", width : " + p18.width + ", weight : " + p18.weight);
        System.out.println("Brand of Blanket 19 : " + p19.brand + ", color : " + p19.color + ", material : " + p19.material + ", length : " + p19.length + ", width : " + p19.width + ", weight : " + p19.weight);
        System.out.println("Brand of Blanket 20 : " + p20.brand + ", color : " + p20.color + ", material : " + p20.material + ", length : " + p20.length + ", width : " + p20.width + ", weight : " + p20.weight);
        System.out.println("Brand of Blanket 21 : " + p21.brand + ", color : " + p21.color + ", material : " + p21.material + ", length : " + p21.length + ", width : " + p21.width + ", weight : " + p21.weight);
        System.out.println("Brand of Blanket 22 : " + p22.brand + ", color : " + p22.color + ", material : " + p22.material + ", length : " + p22.length + ", width : " + p22.width + ", weight : " + p22.weight);
        System.out.println("Brand of Blanket 23 : " + p23.brand + ", color : " + p23.color + ", material : " + p23.material + ", length : " + p23.length + ", width : " + p23.width + ", weight : " + p23.weight);
        System.out.println("Brand of Blanket 24 : " + p24.brand + ", color : " + p24.color + ", material : " + p24.material + ", length : " + p24.length + ", width : " + p24.width + ", weight : " + p24.weight);
        System.out.println("Brand of Blanket 25 : " + p25.brand + ", color : " + p25.color + ", material : " + p25.material + ", length : " + p25.length + ", width : " + p25.width + ", weight : " + p25.weight);
    }
}