class BucketRunner {
    public static void main(String[] args) {
// default constructor
        Bucket b1 = new Bucket();
        b1.color = "Red"; 
		b1.capacity = 5.0; 
		b1.material = "Plastic"; 
		b1.height = 25.0; 
		b1.weight = 0.5;
        Bucket b2 = new Bucket();
        b2.color = "Blue"; 
		b2.capacity = 10.0; 
		b2.material = "Metal"; 
		b2.height = 30.0; 
		b2.weight = 1.0;
        Bucket b3 = new Bucket();
        b3.color = "Green"; 
		b3.capacity = 15.0; 
		b3.material = "Rubber"; 
		b3.height = 35.0; 
		b3.weight = 1.2;
        Bucket b4 = new Bucket();
        b4.color = "Yellow"; 
		b4.capacity = 8.0; 
		b4.material = "Plastic"; 
		b4.height = 28.0; 
		b4.weight = 0.6;
        Bucket b5 = new Bucket();
        b5.color = "Orange"; 
		b5.capacity = 12.0; 
		b5.material = "Steel"; 
		b5.height = 32.0; 
		b5.weight = 1.5;
        Bucket b6 = new Bucket();
        b6.color = "Black"; 
		b6.capacity = 20.0; 
		b6.material = "Metal"; 
		b6.height = 40.0; 
		b6.weight = 2.0;
        Bucket b7 = new Bucket();
        b7.color = "White"; 
		b7.capacity = 6.0; 
		b7.material = "Plastic"; 
		b7.height = 26.0; 
		b7.weight = 0.4;
        Bucket b8 = new Bucket();
        b8.color = "Gray"; 
		b8.capacity = 9.0; 
		b8.material = "Rubber"; 
		b8.height = 29.0; 
		b8.weight = 0.8;
        Bucket b9 = new Bucket();
        b9.color = "Brown"; 
		b9.capacity = 11.0; 
		b9.material = "Plastic"; 
		b9.height = 31.0; 
		b9.weight = 0.7;
        Bucket b10 = new Bucket();
        b10.color = "Pink"; 
		b10.capacity = 7.0; 
		b10.material = "Plastic"; 
		b10.height = 27.0; 
		b10.weight = 0.5;
        Bucket b11 = new Bucket();
        b11.color = "Purple"; 
		b11.capacity = 14.0; 
		b11.material = "Steel"; 
		b11.height = 34.0; 
		b11.weight = 1.8;
        Bucket b12 = new Bucket();
        b12.color = "Cyan"; 
		b12.capacity = 16.0; 
		b12.material = "Plastic"; 
		b12.height = 36.0; 
		b12.weight = 1.1;
        Bucket b13 = new Bucket();
        b13.color = "Maroon"; 
		b13.capacity = 18.0; 
		b13.material = "Metal"; 
		b13.height = 38.0; 
		b13.weight = 1.9;
        Bucket b14 = new Bucket();
        b14.color = "Navy"; 
		b14.capacity = 13.0; 
		b14.material = "Rubber"; 
		b14.height = 33.0; 
		b14.weight = 1.3;
        Bucket b15 = new Bucket();
        b15.color = "Teal"; 
		b15.capacity = 17.0; 
		b15.material = "Plastic"; 
		b15.height = 37.0; 
		b15.weight = 1.0;
        Bucket b16 = new Bucket();
        b16.color = "Lime"; 
		b16.capacity = 4.0; 
		b16.material = "Plastic"; 
		b16.height = 22.0; 
		b16.weight = 0.3;
        Bucket b17 = new Bucket();
        b17.color = "Indigo"; 
		b17.capacity = 19.0; 
		b17.material = "Steel"; 
		b17.height = 39.0; 
		b17.weight = 2.1;
        Bucket b18 = new Bucket();
        b18.color = "Violet"; 
		b18.capacity = 3.0; 
		b18.material = "Plastic"; 
		b18.height = 20.0; 
		b18.weight = 0.2;
        Bucket b19 = new Bucket();
        b19.color = "Coral"; 
		b19.capacity = 22.0; 
		b19.material = "Metal"; 
		b19.height = 42.0; 
		b19.weight = 2.5;
        Bucket b20 = new Bucket();
        b20.color = "Salmon"; 
		b20.capacity = 25.0; 
		b20.material = "Steel"; 
		b20.height = 45.0; 
		b20.weight = 2.8;
        Bucket b21 = new Bucket();
        b21.color = "Beige"; 
		b21.capacity = 2.0; 
		b21.material = "Plastic"; 
		b21.height = 18.0; 
		b21.weight = 0.2;
        Bucket b22 = new Bucket();
        b22.color = "Ivory"; 
		b22.capacity = 21.0; 
		b22.material = "Rubber"; 
		b22.height = 41.0; 
		b22.weight = 2.2;
        Bucket b23 = new Bucket();
        b23.color = "Gold"; 
		b23.capacity = 23.0; 
		b23.material = "Metal"; 
		b23.height = 43.0; 
		b23.weight = 2.6;
        Bucket b24 = new Bucket();
        b24.color = "Silver"; 
		b24.capacity = 24.0; 
		b24.material = "Steel"; 
		b24.height = 44.0; 
		b24.weight = 2.7;
        Bucket b25 = new Bucket();
        b25.color = "Bronze"; 
		b25.capacity = 26.0; 
		b25.material = "Metal"; 
		b25.height = 46.0; 
		b25.weight = 3.0;

        System.out.println("Bucket color : " + b1.color + ", capacity : " + b1.capacity + ", material : " + b1.material + ", height : " + b1.height + ", weight : " + b1.weight);
        System.out.println("Bucket color : " + b2.color + ", capacity : " + b2.capacity + ", material : " + b2.material + ", height : " + b2.height + ", weight : " + b2.weight);
        System.out.println("Bucket color : " + b3.color + ", capacity : " + b3.capacity + ", material : " + b3.material + ", height : " + b3.height + ", weight : " + b3.weight);
        System.out.println("Bucket color : " + b4.color + ", capacity : " + b4.capacity + ", material : " + b4.material + ", height : " + b4.height + ", weight : " + b4.weight);
        System.out.println("Bucket color : " + b5.color + ", capacity : " + b5.capacity + ", material : " + b5.material + ", height : " + b5.height + ", weight : " + b5.weight);
        System.out.println("Bucket color : " + b6.color + ", capacity : " + b6.capacity + ", material : " + b6.material + ", height : " + b6.height + ", weight : " + b6.weight);
        System.out.println("Bucket color : " + b7.color + ", capacity : " + b7.capacity + ", material : " + b7.material + ", height : " + b7.height + ", weight : " + b7.weight);
        System.out.println("Bucket color : " + b8.color + ", capacity : " + b8.capacity + ", material : " + b8.material + ", height : " + b8.height + ", weight : " + b8.weight);
        System.out.println("Bucket color : " + b9.color + ", capacity : " + b9.capacity + ", material : " + b9.material + ", height : " + b9.height + ", weight : " + b9.weight);
        System.out.println("Bucket color : " + b10.color + ", capacity : " + b10.capacity + ", material : " + b10.material + ", height : " + b10.height + ", weight : " + b10.weight);
        System.out.println("Bucket color : " + b11.color + ", capacity : " + b11.capacity + ", material : " + b11.material + ", height : " + b11.height + ", weight : " + b11.weight);
        System.out.println("Bucket color : " + b12.color + ", capacity : " + b12.capacity + ", material : " + b12.material + ", height : " + b12.height + ", weight : " + b12.weight);
        System.out.println("Bucket color : " + b13.color + ", capacity : " + b13.capacity + ", material : " + b13.material + ", height : " + b13.height + ", weight : " + b13.weight);
        System.out.println("Bucket color : " + b14.color + ", capacity : " + b14.capacity + ", material : " + b14.material + ", height : " + b14.height + ", weight : " + b14.weight);
        System.out.println("Bucket color : " + b15.color + ", capacity : " + b15.capacity + ", material : " + b15.material + ", height : " + b15.height + ", weight : " + b15.weight);
        System.out.println("Bucket color : " + b16.color + ", capacity : " + b16.capacity + ", material : " + b16.material + ", height : " + b16.height + ", weight : " + b16.weight);
        System.out.println("Bucket color : " + b17.color + ", capacity : " + b17.capacity + ", material : " + b17.material + ", height : " + b17.height + ", weight : " + b17.weight);
        System.out.println("Bucket color : " + b18.color + ", capacity : " + b18.capacity + ", material : " + b18.material + ", height : " + b18.height + ", weight : " + b18.weight);
        System.out.println("Bucket color : " + b19.color + ", capacity : " + b19.capacity + ", material : " + b19.material + ", height : " + b19.height + ", weight : " + b19.weight);
        System.out.println("Bucket color : " + b20.color + ", capacity : " + b20.capacity + ", material : " + b20.material + ", height : " + b20.height + ", weight : " + b20.weight);
        System.out.println("Bucket color : " + b21.color + ", capacity : " + b21.capacity + ", material : " + b21.material + ", height : " + b21.height + ", weight : " + b21.weight);
        System.out.println("Bucket color : " + b22.color + ", capacity : " + b22.capacity + ", material : " + b22.material + ", height : " + b22.height + ", weight : " + b22.weight);
        System.out.println("Bucket color : " + b23.color + ", capacity : " + b23.capacity + ", material : " + b23.material + ", height : " + b23.height + ", weight : " + b23.weight);
        System.out.println("Bucket color : " + b24.color + ", capacity : " + b24.capacity + ", material : " + b24.material + ", height : " + b24.height + ", weight : " + b24.weight);
        System.out.println("Bucket color : " + b25.color + ", capacity : " + b25.capacity + ", material : " + b25.material + ", height : " + b25.height + ", weight : " + b25.weight);

// parameterized constructor
        Bucket p1 = new Bucket("Red", 5.0, "Plastic", 25.0, 0.5);
        Bucket p2 = new Bucket("Blue", 10.0, "Metal", 30.0, 1.0);
        Bucket p3 = new Bucket("Green", 15.0, "Rubber", 35.0, 1.2);
        Bucket p4 = new Bucket("Yellow", 8.0, "Plastic", 28.0, 0.6);
        Bucket p5 = new Bucket("Orange", 12.0, "Steel", 32.0, 1.5);
        Bucket p6 = new Bucket("Black", 20.0, "Metal", 40.0, 2.0);
        Bucket p7 = new Bucket("White", 6.0, "Plastic", 26.0, 0.4);
        Bucket p8 = new Bucket("Gray", 9.0, "Rubber", 29.0, 0.8);
        Bucket p9 = new Bucket("Brown", 11.0, "Plastic", 31.0, 0.7);
        Bucket p10 = new Bucket("Pink", 7.0, "Plastic", 27.0, 0.5);
        Bucket p11 = new Bucket("Purple", 14.0, "Steel", 34.0, 1.8);
        Bucket p12 = new Bucket("Cyan", 16.0, "Plastic", 36.0, 1.1);
        Bucket p13 = new Bucket("Maroon", 18.0, "Metal", 38.0, 1.9);
        Bucket p14 = new Bucket("Navy", 13.0, "Rubber", 33.0, 1.3);
        Bucket p15 = new Bucket("Teal", 17.0, "Plastic", 37.0, 1.0);
        Bucket p16 = new Bucket("Lime", 4.0, "Plastic", 22.0, 0.3);
        Bucket p17 = new Bucket("Indigo", 19.0, "Steel", 39.0, 2.1);
        Bucket p18 = new Bucket("Violet", 3.0, "Plastic", 20.0, 0.2);
        Bucket p19 = new Bucket("Coral", 22.0, "Metal", 42.0, 2.5);
        Bucket p20 = new Bucket("Salmon", 25.0, "Steel", 45.0, 2.8);
        Bucket p21 = new Bucket("Beige", 2.0, "Plastic", 18.0, 0.2);
        Bucket p22 = new Bucket("Ivory", 21.0, "Rubber", 41.0, 2.2);
        Bucket p23 = new Bucket("Gold", 23.0, "Metal", 43.0, 2.6);
        Bucket p24 = new Bucket("Silver", 24.0, "Steel", 44.0, 2.7);
        Bucket p25 = new Bucket("Bronze", 26.0, "Metal", 46.0, 3.0);

        System.out.println("Color of Bucket 1 : " + p1.color + ", capacity : " + p1.capacity + ", material : " + p1.material + ", height : " + p1.height + ", weight : " + p1.weight);
        System.out.println("Color of Bucket 2 : " + p2.color + ", capacity : " + p2.capacity + ", material : " + p2.material + ", height : " + p2.height + ", weight : " + p2.weight);
        System.out.println("Color of Bucket 3 : " + p3.color + ", capacity : " + p3.capacity + ", material : " + p3.material + ", height : " + p3.height + ", weight : " + p3.weight);
        System.out.println("Color of Bucket 4 : " + p4.color + ", capacity : " + p4.capacity + ", material : " + p4.material + ", height : " + p4.height + ", weight : " + p4.weight);
        System.out.println("Color of Bucket 5 : " + p5.color + ", capacity : " + p5.capacity + ", material : " + p5.material + ", height : " + p5.height + ", weight : " + p5.weight);
        System.out.println("Color of Bucket 6 : " + p6.color + ", capacity : " + p6.capacity + ", material : " + p6.material + ", height : " + p6.height + ", weight : " + p6.weight);
        System.out.println("Color of Bucket 7 : " + p7.color + ", capacity : " + p7.capacity + ", material : " + p7.material + ", height : " + p7.height + ", weight : " + p7.weight);
        System.out.println("Color of Bucket 8 : " + p8.color + ", capacity : " + p8.capacity + ", material : " + p8.material + ", height : " + p8.height + ", weight : " + p8.weight);
        System.out.println("Color of Bucket 9 : " + p9.color + ", capacity : " + p9.capacity + ", material : " + p9.material + ", height : " + p9.height + ", weight : " + p9.weight);
        System.out.println("Color of Bucket 10 : " + p10.color + ", capacity : " + p10.capacity + ", material : " + p10.material + ", height : " + p10.height + ", weight : " + p10.weight);
        System.out.println("Color of Bucket 11 : " + p11.color + ", capacity : " + p11.capacity + ", material : " + p11.material + ", height : " + p11.height + ", weight : " + p11.weight);
        System.out.println("Color of Bucket 12 : " + p12.color + ", capacity : " + p12.capacity + ", material : " + p12.material + ", height : " + p12.height + ", weight : " + p12.weight);
        System.out.println("Color of Bucket 13 : " + p13.color + ", capacity : " + p13.capacity + ", material : " + p13.material + ", height : " + p13.height + ", weight : " + p13.weight);
        System.out.println("Color of Bucket 14 : " + p14.color + ", capacity : " + p14.capacity + ", material : " + p14.material + ", height : " + p14.height + ", weight : " + p14.weight);
        System.out.println("Color of Bucket 15 : " + p15.color + ", capacity : " + p15.capacity + ", material : " + p15.material + ", height : " + p15.height + ", weight : " + p15.weight);
        System.out.println("Color of Bucket 16 : " + p16.color + ", capacity : " + p16.capacity + ", material : " + p16.material + ", height : " + p16.height + ", weight : " + p16.weight);
        System.out.println("Color of Bucket 17 : " + p17.color + ", capacity : " + p17.capacity + ", material : " + p17.material + ", height : " + p17.height + ", weight : " + p17.weight);
        System.out.println("Color of Bucket 18 : " + p18.color + ", capacity : " + p18.capacity + ", material : " + p18.material + ", height : " + p18.height + ", weight : " + p18.weight);
        System.out.println("Color of Bucket 19 : " + p19.color + ", capacity : " + p19.capacity + ", material : " + p19.material + ", height : " + p19.height + ", weight : " + p19.weight);
        System.out.println("Color of Bucket 20 : " + p20.color + ", capacity : " + p20.capacity + ", material : " + p20.material + ", height : " + p20.height + ", weight : " + p20.weight);
        System.out.println("Color of Bucket 21 : " + p21.color + ", capacity : " + p21.capacity + ", material : " + p21.material + ", height : " + p21.height + ", weight : " + p21.weight);
        System.out.println("Color of Bucket 22 : " + p22.color + ", capacity : " + p22.capacity + ", material : " + p22.material + ", height : " + p22.height + ", weight : " + p22.weight);
        System.out.println("Color of Bucket 23 : " + p23.color + ", capacity : " + p23.capacity + ", material : " + p23.material + ", height : " + p23.height + ", weight : " + p23.weight);
        System.out.println("Color of Bucket 24 : " + p24.color + ", capacity : " + p24.capacity + ", material : " + p24.material + ", height : " + p24.height + ", weight : " + p24.weight);
        System.out.println("Color of Bucket 25 : " + p25.color + ", capacity : " + p25.capacity + ", material : " + p25.material + ", height : " + p25.height + ", weight : " + p25.weight);
    }
}