class CoffeeRunner {
    public static void main(String[] args) {
// default constructor
        Coffee c1 = new Coffee();
        c1.type = "Espresso"; 
		c1.price = 2.50;
        Coffee c2 = new Coffee();
        c2.type = "Latte"; 
		c2.price = 3.00;
        Coffee c3 = new Coffee();
        c3.type = "Cappuccino"; 
		c3.price = 3.50;
        Coffee c4 = new Coffee();
        c4.type = "Americano"; 
		c4.price = 2.00;
        Coffee c5 = new Coffee();
        c5.type = "Mocha"; 
		c5.price = 4.00;
        Coffee c6 = new Coffee();
        c6.type = "Macchiato"; 
		c6.price = 3.75;
        Coffee c7 = new Coffee();
        c7.type = "Flat White"; 
		c7.price = 3.25;
        Coffee c8 = new Coffee();
        c8.type = "Cold Brew"; 
		c8.price = 4.50;
        Coffee c9 = new Coffee();
        c9.type = "Iced Coffee"; 
		c9.price = 3.00;
        Coffee c10 = new Coffee();
        c10.type = "Affogato"; 
		c10.price = 5.00;
        Coffee c11 = new Coffee();
        c11.type = "Cortado"; 
		c11.price = 3.50;
        Coffee c12 = new Coffee();
        c12.type = "Lungo"; 
		c12.price = 2.75;
        Coffee c13 = new Coffee();
        c13.type = "Ristretto"; 
		c13.price = 2.50;
        Coffee c14 = new Coffee();
        c14.type = "Doppio"; 
		c14.price = 3.00;
        Coffee c15 = new Coffee();
        c15.type = "Piccolo"; 
		c15.price = 3.25;
        Coffee c16 = new Coffee();
        c16.type = "Nitro"; 
		c16.price = 5.50;
        Coffee c17 = new Coffee();
        c17.type = "Drip Coffee"; 
		c17.price = 1.50;
        Coffee c18 = new Coffee();
        c18.type = "Pour Over"; 
		c18.price = 4.00;
        Coffee c19 = new Coffee();
        c19.type = "French Press"; 
		c19.price = 3.50;
        Coffee c20 = new Coffee();
        c20.type = "Aeropress"; 
		c20.price = 3.75;
        Coffee c21 = new Coffee();
        c21.type = "Turkish Coffee"; 
		c21.price = 3.00;
        Coffee c22 = new Coffee();
        c22.type = "Vietnamese"; 
		c22.price = 4.25;
        Coffee c23 = new Coffee();
        c23.type = "Bulletproof"; 
		c23.price = 6.00;
        Coffee c24 = new Coffee();
        c24.type = "Decaf"; 
		c24.price = 2.50;
        Coffee c25 = new Coffee();
        c25.type = "Siphon"; 
		c25.price = 7.00;

        System.out.println("Coffee type : " + c1.type + ", price : " + c1.price);
        System.out.println("Coffee type : " + c2.type + ", price : " + c2.price);
        System.out.println("Coffee type : " + c3.type + ", price : " + c3.price);
        System.out.println("Coffee type : " + c4.type + ", price : " + c4.price);
        System.out.println("Coffee type : " + c5.type + ", price : " + c5.price);
        System.out.println("Coffee type : " + c6.type + ", price : " + c6.price);
        System.out.println("Coffee type : " + c7.type + ", price : " + c7.price);
        System.out.println("Coffee type : " + c8.type + ", price : " + c8.price);
        System.out.println("Coffee type : " + c9.type + ", price : " + c9.price);
        System.out.println("Coffee type : " + c10.type + ", price : " + c10.price);
        System.out.println("Coffee type : " + c11.type + ", price : " + c11.price);
        System.out.println("Coffee type : " + c12.type + ", price : " + c12.price);
        System.out.println("Coffee type : " + c13.type + ", price : " + c13.price);
        System.out.println("Coffee type : " + c14.type + ", price : " + c14.price);
        System.out.println("Coffee type : " + c15.type + ", price : " + c15.price);
        System.out.println("Coffee type : " + c16.type + ", price : " + c16.price);
        System.out.println("Coffee type : " + c17.type + ", price : " + c17.price);
        System.out.println("Coffee type : " + c18.type + ", price : " + c18.price);
        System.out.println("Coffee type : " + c19.type + ", price : " + c19.price);
        System.out.println("Coffee type : " + c20.type + ", price : " + c20.price);
        System.out.println("Coffee type : " + c21.type + ", price : " + c21.price);
        System.out.println("Coffee type : " + c22.type + ", price : " + c22.price);
        System.out.println("Coffee type : " + c23.type + ", price : " + c23.price);
        System.out.println("Coffee type : " + c24.type + ", price : " + c24.price);
        System.out.println("Coffee type : " + c25.type + ", price : " + c25.price);

// parameterized constructor
        Coffee p1 = new Coffee("Espresso", 2.50);
        Coffee p2 = new Coffee("Latte", 3.00);
        Coffee p3 = new Coffee("Cappuccino", 3.50);
        Coffee p4 = new Coffee("Americano", 2.00);
        Coffee p5 = new Coffee("Mocha", 4.00);
        Coffee p6 = new Coffee("Macchiato", 3.75);
        Coffee p7 = new Coffee("Flat White", 3.25);
        Coffee p8 = new Coffee("Cold Brew", 4.50);
        Coffee p9 = new Coffee("Iced Coffee", 3.00);
        Coffee p10 = new Coffee("Affogato", 5.00);
        Coffee p11 = new Coffee("Cortado", 3.50);
        Coffee p12 = new Coffee("Lungo", 2.75);
        Coffee p13 = new Coffee("Ristretto", 2.50);
        Coffee p14 = new Coffee("Doppio", 3.00);
        Coffee p15 = new Coffee("Piccolo", 3.25);
        Coffee p16 = new Coffee("Nitro", 5.50);
        Coffee p17 = new Coffee("Drip Coffee", 1.50);
        Coffee p18 = new Coffee("Pour Over", 4.00);
        Coffee p19 = new Coffee("French Press", 3.50);
        Coffee p20 = new Coffee("Aeropress", 3.75);
        Coffee p21 = new Coffee("Turkish Coffee", 3.00);
        Coffee p22 = new Coffee("Vietnamese", 4.25);
        Coffee p23 = new Coffee("Bulletproof", 6.00);
        Coffee p24 = new Coffee("Decaf", 2.50);
        Coffee p25 = new Coffee("Siphon", 7.00);

        System.out.println("Type of Coffee 1 : " + p1.type + ", price : " + p1.price);
        System.out.println("Type of Coffee 2 : " + p2.type + ", price : " + p2.price);
        System.out.println("Type of Coffee 3 : " + p3.type + ", price : " + p3.price);
        System.out.println("Type of Coffee 4 : " + p4.type + ", price : " + p4.price);
        System.out.println("Type of Coffee 5 : " + p5.type + ", price : " + p5.price);
        System.out.println("Type of Coffee 6 : " + p6.type + ", price : " + p6.price);
        System.out.println("Type of Coffee 7 : " + p7.type + ", price : " + p7.price);
        System.out.println("Type of Coffee 8 : " + p8.type + ", price : " + p8.price);
        System.out.println("Type of Coffee 9 : " + p9.type + ", price : " + p9.price);
        System.out.println("Type of Coffee 10 : " + p10.type + ", price : " + p10.price);
        System.out.println("Type of Coffee 11 : " + p11.type + ", price : " + p11.price);
        System.out.println("Type of Coffee 12 : " + p12.type + ", price : " + p12.price);
        System.out.println("Type of Coffee 13 : " + p13.type + ", price : " + p13.price);
        System.out.println("Type of Coffee 14 : " + p14.type + ", price : " + p14.price);
        System.out.println("Type of Coffee 15 : " + p15.type + ", price : " + p15.price);
        System.out.println("Type of Coffee 16 : " + p16.type + ", price : " + p16.price);
        System.out.println("Type of Coffee 17 : " + p17.type + ", price : " + p17.price);
        System.out.println("Type of Coffee 18 : " + p18.type + ", price : " + p18.price);
        System.out.println("Type of Coffee 19 : " + p19.type + ", price : " + p19.price);
        System.out.println("Type of Coffee 20 : " + p20.type + ", price : " + p20.price);
        System.out.println("Type of Coffee 21 : " + p21.type + ", price : " + p21.price);
        System.out.println("Type of Coffee 22 : " + p22.type + ", price : " + p22.price);
        System.out.println("Type of Coffee 23 : " + p23.type + ", price : " + p23.price);
        System.out.println("Type of Coffee 24 : " + p24.type + ", price : " + p24.price);
        System.out.println("Type of Coffee 25 : " + p25.type + ", price : " + p25.price);
    }
}