class HelmetRunner {
    public static void main(String[] args) {
// default constructor
        Helmet h1 = new Helmet();
        h1.brand = "Arai"; h1.size = "S"; h1.color = "Red";
        Helmet h2 = new Helmet();
        h2.brand = "Shoei"; h2.size = "M"; h2.color = "Black";
        Helmet h3 = new Helmet();
        h3.brand = "Bell"; h3.size = "L"; h3.color = "White";
        Helmet h4 = new Helmet();
        h4.brand = "HJC"; h4.size = "XL"; h4.color = "Blue";
        Helmet h5 = new Helmet();
        h5.brand = "AGV"; h5.size = "XXL"; h5.color = "Yellow";
        Helmet h6 = new Helmet();
        h6.brand = "Nolan"; h6.size = "S"; h6.color = "Gray";
        Helmet h7 = new Helmet();
        h7.brand = "LS2"; h7.size = "M"; h7.color = "Green";
        Helmet h8 = new Helmet();
        h8.brand = "Fox"; h8.size = "L"; h8.color = "Orange";
        Helmet h9 = new Helmet();
        h9.brand = "Troy Lee"; h9.size = "XL"; h9.color = "Purple";
        Helmet h10 = new Helmet();
        h10.brand = "O'Neal"; h10.size = "S"; h10.color = "Pink";
        Helmet h11 = new Helmet();
        h11.brand = "Scott"; h11.size = "M"; h11.color = "Navy";
        Helmet h12 = new Helmet();
        h12.brand = "Fly Racing"; h12.size = "L"; h12.color = "Teal";
        Helmet h13 = new Helmet();
        h13.brand = "Suomy"; h13.size = "XXL"; h13.color = "Maroon";
        Helmet h14 = new Helmet();
        h14.brand = "Ruroc"; h14.size = "S"; h14.color = "Silver";
        Helmet h15 = new Helmet();
        h15.brand = "Klim"; h15.size = "M"; h15.color = "Brown";
        Helmet h16 = new Helmet();
        h16.brand = "Icon"; h16.size = "L"; h16.color = "Lime";
        Helmet h17 = new Helmet();
        h17.brand = "Alpinestars"; h17.size = "XL"; h17.color = "Cyan";
        Helmet h18 = new Helmet();
        h18.brand = "Shark"; h18.size = "S"; h18.color = "Coral";
        Helmet h19 = new Helmet();
        h19.brand = "Caberg"; h19.size = "M"; h19.color = "Ivory";
        Helmet h20 = new Helmet();
        h20.brand = "MT Helmets"; h20.size = "L"; h20.color = "Gold";
        Helmet h21 = new Helmet();
        h21.brand = "Lazer"; h21.size = "XXL"; h21.color = "Beige";
        Helmet h22 = new Helmet();
        h22.brand = "Giro"; h22.size = "S"; h22.color = "Violet";
        Helmet h23 = new Helmet();
        h23.brand = "POC"; h23.size = "M"; h23.color = "Indigo";
        Helmet h24 = new Helmet();
        h24.brand = "Smith"; h24.size = "L"; h24.color = "Tan";
        Helmet h25 = new Helmet();
        h25.brand = "Specialized"; h25.size = "XL"; h25.color = "Charcoal";

        System.out.println("Helmet brand : " + h1.brand + ", size : " + h1.size + ", color : " + h1.color);
        System.out.println("Helmet brand : " + h2.brand + ", size : " + h2.size + ", color : " + h2.color);
        System.out.println("Helmet brand : " + h3.brand + ", size : " + h3.size + ", color : " + h3.color);
        System.out.println("Helmet brand : " + h4.brand + ", size : " + h4.size + ", color : " + h4.color);
        System.out.println("Helmet brand : " + h5.brand + ", size : " + h5.size + ", color : " + h5.color);
        System.out.println("Helmet brand : " + h6.brand + ", size : " + h6.size + ", color : " + h6.color);
        System.out.println("Helmet brand : " + h7.brand + ", size : " + h7.size + ", color : " + h7.color);
        System.out.println("Helmet brand : " + h8.brand + ", size : " + h8.size + ", color : " + h8.color);
        System.out.println("Helmet brand : " + h9.brand + ", size : " + h9.size + ", color : " + h9.color);
        System.out.println("Helmet brand : " + h10.brand + ", size : " + h10.size + ", color : " + h10.color);
        System.out.println("Helmet brand : " + h11.brand + ", size : " + h11.size + ", color : " + h11.color);
        System.out.println("Helmet brand : " + h12.brand + ", size : " + h12.size + ", color : " + h12.color);
        System.out.println("Helmet brand : " + h13.brand + ", size : " + h13.size + ", color : " + h13.color);
        System.out.println("Helmet brand : " + h14.brand + ", size : " + h14.size + ", color : " + h14.color);
        System.out.println("Helmet brand : " + h15.brand + ", size : " + h15.size + ", color : " + h15.color);
        System.out.println("Helmet brand : " + h16.brand + ", size : " + h16.size + ", color : " + h16.color);
        System.out.println("Helmet brand : " + h17.brand + ", size : " + h17.size + ", color : " + h17.color);
        System.out.println("Helmet brand : " + h18.brand + ", size : " + h18.size + ", color : " + h18.color);
        System.out.println("Helmet brand : " + h19.brand + ", size : " + h19.size + ", color : " + h19.color);
        System.out.println("Helmet brand : " + h20.brand + ", size : " + h20.size + ", color : " + h20.color);
        System.out.println("Helmet brand : " + h21.brand + ", size : " + h21.size + ", color : " + h21.color);
        System.out.println("Helmet brand : " + h22.brand + ", size : " + h22.size + ", color : " + h22.color);
        System.out.println("Helmet brand : " + h23.brand + ", size : " + h23.size + ", color : " + h23.color);
        System.out.println("Helmet brand : " + h24.brand + ", size : " + h24.size + ", color : " + h24.color);
        System.out.println("Helmet brand : " + h25.brand + ", size : " + h25.size + ", color : " + h25.color);

// parameterized constructor
        Helmet p1 = new Helmet("Arai", "S", "Red");
        Helmet p2 = new Helmet("Shoei", "M", "Black");
        Helmet p3 = new Helmet("Bell", "L", "White");
        Helmet p4 = new Helmet("HJC", "XL", "Blue");
        Helmet p5 = new Helmet("AGV", "XXL", "Yellow");
        Helmet p6 = new Helmet("Nolan", "S", "Gray");
        Helmet p7 = new Helmet("LS2", "M", "Green");
        Helmet p8 = new Helmet("Fox", "L", "Orange");
        Helmet p9 = new Helmet("Troy Lee", "XL", "Purple");
        Helmet p10 = new Helmet("O'Neal", "S", "Pink");
        Helmet p11 = new Helmet("Scott", "M", "Navy");
        Helmet p12 = new Helmet("Fly Racing", "L", "Teal");
        Helmet p13 = new Helmet("Suomy", "XXL", "Maroon");
        Helmet p14 = new Helmet("Ruroc", "S", "Silver");
        Helmet p15 = new Helmet("Klim", "M", "Brown");
        Helmet p16 = new Helmet("Icon", "L", "Lime");
        Helmet p17 = new Helmet("Alpinestars", "XL", "Cyan");
        Helmet p18 = new Helmet("Shark", "S", "Coral");
        Helmet p19 = new Helmet("Caberg", "M", "Ivory");
        Helmet p20 = new Helmet("MT Helmets", "L", "Gold");
        Helmet p21 = new Helmet("Lazer", "XXL", "Beige");
        Helmet p22 = new Helmet("Giro", "S", "Violet");
        Helmet p23 = new Helmet("POC", "M", "Indigo");
        Helmet p24 = new Helmet("Smith", "L", "Tan");
        Helmet p25 = new Helmet("Specialized", "XL", "Charcoal");

        System.out.println("Brand of Helmet 1 : " + p1.brand + ", size : " + p1.size + ", color : " + p1.color);
        System.out.println("Brand of Helmet 2 : " + p2.brand + ", size : " + p2.size + ", color : " + p2.color);
        System.out.println("Brand of Helmet 3 : " + p3.brand + ", size : " + p3.size + ", color : " + p3.color);
        System.out.println("Brand of Helmet 4 : " + p4.brand + ", size : " + p4.size + ", color : " + p4.color);
        System.out.println("Brand of Helmet 5 : " + p5.brand + ", size : " + p5.size + ", color : " + p5.color);
        System.out.println("Brand of Helmet 6 : " + p6.brand + ", size : " + p6.size + ", color : " + p6.color);
        System.out.println("Brand of Helmet 7 : " + p7.brand + ", size : " + p7.size + ", color : " + p7.color);
        System.out.println("Brand of Helmet 8 : " + p8.brand + ", size : " + p8.size + ", color : " + p8.color);
        System.out.println("Brand of Helmet 9 : " + p9.brand + ", size : " + p9.size + ", color : " + p9.color);
        System.out.println("Brand of Helmet 10 : " + p10.brand + ", size : " + p10.size + ", color : " + p10.color);
        System.out.println("Brand of Helmet 11 : " + p11.brand + ", size : " + p11.size + ", color : " + p11.color);
        System.out.println("Brand of Helmet 12 : " + p12.brand + ", size : " + p12.size + ", color : " + p12.color);
        System.out.println("Brand of Helmet 13 : " + p13.brand + ", size : " + p13.size + ", color : " + p13.color);
        System.out.println("Brand of Helmet 14 : " + p14.brand + ", size : " + p14.size + ", color : " + p14.color);
        System.out.println("Brand of Helmet 15 : " + p15.brand + ", size : " + p15.size + ", color : " + p15.color);
        System.out.println("Brand of Helmet 16 : " + p16.brand + ", size : " + p16.size + ", color : " + p16.color);
        System.out.println("Brand of Helmet 17 : " + p17.brand + ", size : " + p17.size + ", color : " + p17.color);
        System.out.println("Brand of Helmet 18 : " + p18.brand + ", size : " + p18.size + ", color : " + p18.color);
        System.out.println("Brand of Helmet 19 : " + p19.brand + ", size : " + p19.size + ", color : " + p19.color);
        System.out.println("Brand of Helmet 20 : " + p20.brand + ", size : " + p20.size + ", color : " + p20.color);
        System.out.println("Brand of Helmet 21 : " + p21.brand + ", size : " + p21.size + ", color : " + p21.color);
        System.out.println("Brand of Helmet 22 : " + p22.brand + ", size : " + p22.size + ", color : " + p22.color);
        System.out.println("Brand of Helmet 23 : " + p23.brand + ", size : " + p23.size + ", color : " + p23.color);
        System.out.println("Brand of Helmet 24 : " + p24.brand + ", size : " + p24.size + ", color : " + p24.color);
        System.out.println("Brand of Helmet 25 : " + p25.brand + ", size : " + p25.size + ", color : " + p25.color);
    }
}