class JacketRunner {
    public static void main(String[] args) {
// default constructor
        Jacket j1 = new Jacket();
        j1.brand = "Nike"; j1.color = "Red"; 
		j1.size = "S"; j1.price = 49.99; j1.material = "Polyester";
        Jacket j2 = new Jacket();
        j2.brand = "Adidas"; j2.color = "Blue"; 
		j2.size = "M"; j2.price = 59.99; j2.material = "Cotton";
        Jacket j3 = new Jacket();
        j3.brand = "Puma"; j3.color = "Green"; j3.size = "L"; 
		j3.price = 69.99; j3.material = "Nylon";
        Jacket j4 = new Jacket();
        j4.brand = "Reebok"; j4.color = "Black"; 
		j4.size = "XL"; j4.price = 79.99; j4.material = "Fleece";
        Jacket j5 = new Jacket();
        j5.brand = "Zara"; j5.color = "White"; 
		j5.size = "XXL"; j5.price = 89.99; j5.material = "Wool";
        Jacket j6 = new Jacket();
        j6.brand = "H&M"; j6.color = "Gray"; j6.size = "S"; 
		j6.price = 39.99; j6.material = "Polyester";
        Jacket j7 = new Jacket();
        j7.brand = "Levi's"; j7.color = "Brown"; 
		j7.size = "M"; j7.price = 99.99; j7.material = "Denim";
        Jacket j8 = new Jacket();
        j8.brand = "Gucci"; j8.color = "Beige"; 
		j8.size = "L"; j8.price = 499.99; j8.material = "Leather";
        Jacket j9 = new Jacket();
        j9.brand = "Tommy"; j9.color = "Navy"; 
		j9.size = "XL"; j9.price = 129.99; j9.material = "Cotton";
        Jacket j10 = new Jacket();
        j10.brand = "Calvin Klein"; j10.color = "Black"; 
		j10.size = "S"; j10.price = 149.99; j10.material = "Silk";
        Jacket j11 = new Jacket();
        j11.brand = "North Face"; j11.color = "Orange"; 
		j11.size = "M"; j11.price = 199.99; j11.material = "Gore-Tex";
        Jacket j12 = new Jacket();
        j12.brand = "Columbia"; j12.color = "Teal"; 
		j12.size = "L"; j12.price = 159.99; j12.material = "Nylon";
        Jacket j13 = new Jacket();
        j13.brand = "Patagonia"; j13.color = "Purple"; 
		j13.size = "XXL"; j13.price = 179.99; j13.material = "Fleece";
        Jacket j14 = new Jacket();
        j14.brand = "Under Armour"; j14.color = "Yellow"; 
		j14.size = "S"; j14.price = 89.99; j14.material = "Polyester";
        Jacket j15 = new Jacket();
        j15.brand = "Asics"; j15.color = "Coral"; j15.size = "M"; 
		j15.price = 109.99; j15.material = "Spandex";
        Jacket j16 = new Jacket();
        j16.brand = "Fila"; j16.color = "Maroon"; j16.size = "L"; 
		j16.price = 79.99; j16.material = "Cotton";
        Jacket j17 = new Jacket();
        j17.brand = "Skechers"; j17.color = "Lime"; j17.size = "XL"; 
		j17.price = 69.99; j17.material = "Polyester";
        Jacket j18 = new Jacket();
        j18.brand = "New Balance"; j18.color = "Cyan"; 
		j18.size = "S"; j18.price = 119.99; j18.material = "Nylon";
        Jacket j19 = new Jacket();
        j19.brand = "Decathlon"; j19.color = "Pink"; j19.size = "M"; 
		j19.price = 49.99; j19.material = "Polyester";
        Jacket j20 = new Jacket();
        j20.brand = "Armani"; j20.color = "Ivory"; 
		j20.size = "L"; j20.price = 299.99; j20.material = "Silk";
        Jacket j21 = new Jacket();
        j21.brand = "Polo"; j21.color = "Khaki"; 
		j21.size = "XXL"; j21.price = 189.99; j21.material = "Cotton";
        Jacket j22 = new Jacket();
        j22.brand = "Boss"; j22.color = "Charcoal"; 
		j22.size = "S"; j22.price = 249.99; j22.material = "Wool";
        Jacket j23 = new Jacket();
        j23.brand = "Versace"; j23.color = "Gold"; j23.size = "M"; 
		j23.price = 599.99; j23.material = "Leather";
        Jacket j24 = new Jacket();
        j24.brand = "Burberry"; j24.color = "Tan"; j24.size = "L"; 
		j24.price = 799.99; j24.material = "Trench";
        Jacket j25 = new Jacket();
        j25.brand = "Prada"; j25.color = "Silver"; 
		j25.size = "XL"; j25.price = 999.99; j25.material = "Leather";

        System.out.println("Jacket brand : " + j1.brand + ", color : " + j1.color + ", size : " + j1.size + ", price : " + j1.price + ", material : " + j1.material);
        System.out.println("Jacket brand : " + j2.brand + ", color : " + j2.color + ", size : " + j2.size + ", price : " + j2.price + ", material : " + j2.material);
        System.out.println("Jacket brand : " + j3.brand + ", color : " + j3.color + ", size : " + j3.size + ", price : " + j3.price + ", material : " + j3.material);
        System.out.println("Jacket brand : " + j4.brand + ", color : " + j4.color + ", size : " + j4.size + ", price : " + j4.price + ", material : " + j4.material);
        System.out.println("Jacket brand : " + j5.brand + ", color : " + j5.color + ", size : " + j5.size + ", price : " + j5.price + ", material : " + j5.material);
        System.out.println("Jacket brand : " + j6.brand + ", color : " + j6.color + ", size : " + j6.size + ", price : " + j6.price + ", material : " + j6.material);
        System.out.println("Jacket brand : " + j7.brand + ", color : " + j7.color + ", size : " + j7.size + ", price : " + j7.price + ", material : " + j7.material);
        System.out.println("Jacket brand : " + j8.brand + ", color : " + j8.color + ", size : " + j8.size + ", price : " + j8.price + ", material : " + j8.material);
        System.out.println("Jacket brand : " + j9.brand + ", color : " + j9.color + ", size : " + j9.size + ", price : " + j9.price + ", material : " + j9.material);
        System.out.println("Jacket brand : " + j10.brand + ", color : " + j10.color + ", size : " + j10.size + ", price : " + j10.price + ", material : " + j10.material);
        System.out.println("Jacket brand : " + j11.brand + ", color : " + j11.color + ", size : " + j11.size + ", price : " + j11.price + ", material : " + j11.material);
        System.out.println("Jacket brand : " + j12.brand + ", color : " + j12.color + ", size : " + j12.size + ", price : " + j12.price + ", material : " + j12.material);
        System.out.println("Jacket brand : " + j13.brand + ", color : " + j13.color + ", size : " + j13.size + ", price : " + j13.price + ", material : " + j13.material);
        System.out.println("Jacket brand : " + j14.brand + ", color : " + j14.color + ", size : " + j14.size + ", price : " + j14.price + ", material : " + j14.material);
        System.out.println("Jacket brand : " + j15.brand + ", color : " + j15.color + ", size : " + j15.size + ", price : " + j15.price + ", material : " + j15.material);
        System.out.println("Jacket brand : " + j16.brand + ", color : " + j16.color + ", size : " + j16.size + ", price : " + j16.price + ", material : " + j16.material);
        System.out.println("Jacket brand : " + j17.brand + ", color : " + j17.color + ", size : " + j17.size + ", price : " + j17.price + ", material : " + j17.material);
        System.out.println("Jacket brand : " + j18.brand + ", color : " + j18.color + ", size : " + j18.size + ", price : " + j18.price + ", material : " + j18.material);
        System.out.println("Jacket brand : " + j19.brand + ", color : " + j19.color + ", size : " + j19.size + ", price : " + j19.price + ", material : " + j19.material);
        System.out.println("Jacket brand : " + j20.brand + ", color : " + j20.color + ", size : " + j20.size + ", price : " + j20.price + ", material : " + j20.material);
        System.out.println("Jacket brand : " + j21.brand + ", color : " + j21.color + ", size : " + j21.size + ", price : " + j21.price + ", material : " + j21.material);
        System.out.println("Jacket brand : " + j22.brand + ", color : " + j22.color + ", size : " + j22.size + ", price : " + j22.price + ", material : " + j22.material);
        System.out.println("Jacket brand : " + j23.brand + ", color : " + j23.color + ", size : " + j23.size + ", price : " + j23.price + ", material : " + j23.material);
        System.out.println("Jacket brand : " + j24.brand + ", color : " + j24.color + ", size : " + j24.size + ", price : " + j24.price + ", material : " + j24.material);
        System.out.println("Jacket brand : " + j25.brand + ", color : " + j25.color + ", size : " + j25.size + ", price : " + j25.price + ", material : " + j25.material);

// parameterized constructor
        Jacket p1 = new Jacket("Nike", "Red", "S", 49.99, "Polyester");
        Jacket p2 = new Jacket("Adidas", "Blue", "M", 59.99, "Cotton");
        Jacket p3 = new Jacket("Puma", "Green", "L", 69.99, "Nylon");
        Jacket p4 = new Jacket("Reebok", "Black", "XL", 79.99, "Fleece");
        Jacket p5 = new Jacket("Zara", "White", "XXL", 89.99, "Wool");
        Jacket p6 = new Jacket("H&M", "Gray", "S", 39.99, "Polyester");
        Jacket p7 = new Jacket("Levi's", "Brown", "M", 99.99, "Denim");
        Jacket p8 = new Jacket("Gucci", "Beige", "L", 499.99, "Leather");
        Jacket p9 = new Jacket("Tommy", "Navy", "XL", 129.99, "Cotton");
        Jacket p10 = new Jacket("Calvin Klein", "Black", "S", 149.99, "Silk");
        Jacket p11 = new Jacket("North Face", "Orange", "M", 199.99, "Gore-Tex");
        Jacket p12 = new Jacket("Columbia", "Teal", "L", 159.99, "Nylon");
        Jacket p13 = new Jacket("Patagonia", "Purple", "XXL", 179.99, "Fleece");
        Jacket p14 = new Jacket("Under Armour", "Yellow", "S", 89.99, "Polyester");
        Jacket p15 = new Jacket("Asics", "Coral", "M", 109.99, "Spandex");
        Jacket p16 = new Jacket("Fila", "Maroon", "L", 79.99, "Cotton");
        Jacket p17 = new Jacket("Skechers", "Lime", "XL", 69.99, "Polyester");
        Jacket p18 = new Jacket("New Balance", "Cyan", "S", 119.99, "Nylon");
        Jacket p19 = new Jacket("Decathlon", "Pink", "M", 49.99, "Polyester");
        Jacket p20 = new Jacket("Armani", "Ivory", "L", 299.99, "Silk");
        Jacket p21 = new Jacket("Polo", "Khaki", "XXL", 189.99, "Cotton");
        Jacket p22 = new Jacket("Boss", "Charcoal", "S", 249.99, "Wool");
        Jacket p23 = new Jacket("Versace", "Gold", "M", 599.99, "Leather");
        Jacket p24 = new Jacket("Burberry", "Tan", "L", 799.99, "Trench");
        Jacket p25 = new Jacket("Prada", "Silver", "XL", 999.99, "Leather");

        System.out.println("Brand of Jacket 1 : " + p1.brand + ", color : " + p1.color + ", size : " + p1.size + ", price : " + p1.price + ", material : " + p1.material);
        System.out.println("Brand of Jacket 2 : " + p2.brand + ", color : " + p2.color + ", size : " + p2.size + ", price : " + p2.price + ", material : " + p2.material);
        System.out.println("Brand of Jacket 3 : " + p3.brand + ", color : " + p3.color + ", size : " + p3.size + ", price : " + p3.price + ", material : " + p3.material);
        System.out.println("Brand of Jacket 4 : " + p4.brand + ", color : " + p4.color + ", size : " + p4.size + ", price : " + p4.price + ", material : " + p4.material);
        System.out.println("Brand of Jacket 5 : " + p5.brand + ", color : " + p5.color + ", size : " + p5.size + ", price : " + p5.price + ", material : " + p5.material);
        System.out.println("Brand of Jacket 6 : " + p6.brand + ", color : " + p6.color + ", size : " + p6.size + ", price : " + p6.price + ", material : " + p6.material);
        System.out.println("Brand of Jacket 7 : " + p7.brand + ", color : " + p7.color + ", size : " + p7.size + ", price : " + p7.price + ", material : " + p7.material);
        System.out.println("Brand of Jacket 8 : " + p8.brand + ", color : " + p8.color + ", size : " + p8.size + ", price : " + p8.price + ", material : " + p8.material);
        System.out.println("Brand of Jacket 9 : " + p9.brand + ", color : " + p9.color + ", size : " + p9.size + ", price : " + p9.price + ", material : " + p9.material);
        System.out.println("Brand of Jacket 10 : " + p10.brand + ", color : " + p10.color + ", size : " + p10.size + ", price : " + p10.price + ", material : " + p10.material);
        System.out.println("Brand of Jacket 11 : " + p11.brand + ", color : " + p11.color + ", size : " + p11.size + ", price : " + p11.price + ", material : " + p11.material);
        System.out.println("Brand of Jacket 12 : " + p12.brand + ", color : " + p12.color + ", size : " + p12.size + ", price : " + p12.price + ", material : " + p12.material);
        System.out.println("Brand of Jacket 13 : " + p13.brand + ", color : " + p13.color + ", size : " + p13.size + ", price : " + p13.price + ", material : " + p13.material);
        System.out.println("Brand of Jacket 14 : " + p14.brand + ", color : " + p14.color + ", size : " + p14.size + ", price : " + p14.price + ", material : " + p14.material);
        System.out.println("Brand of Jacket 15 : " + p15.brand + ", color : " + p15.color + ", size : " + p15.size + ", price : " + p15.price + ", material : " + p15.material);
        System.out.println("Brand of Jacket 16 : " + p16.brand + ", color : " + p16.color + ", size : " + p16.size + ", price : " + p16.price + ", material : " + p16.material);
        System.out.println("Brand of Jacket 17 : " + p17.brand + ", color : " + p17.color + ", size : " + p17.size + ", price : " + p17.price + ", material : " + p17.material);
        System.out.println("Brand of Jacket 18 : " + p18.brand + ", color : " + p18.color + ", size : " + p18.size + ", price : " + p18.price + ", material : " + p18.material);
        System.out.println("Brand of Jacket 19 : " + p19.brand + ", color : " + p19.color + ", size : " + p19.size + ", price : " + p19.price + ", material : " + p19.material);
        System.out.println("Brand of Jacket 20 : " + p20.brand + ", color : " + p20.color + ", size : " + p20.size + ", price : " + p20.price + ", material : " + p20.material);
        System.out.println("Brand of Jacket 21 : " + p21.brand + ", color : " + p21.color + ", size : " + p21.size + ", price : " + p21.price + ", material : " + p21.material);
        System.out.println("Brand of Jacket 22 : " + p22.brand + ", color : " + p22.color + ", size : " + p22.size + ", price : " + p22.price + ", material : " + p22.material);
        System.out.println("Brand of Jacket 23 : " + p23.brand + ", color : " + p23.color + ", size : " + p23.size + ", price : " + p23.price + ", material : " + p23.material);
        System.out.println("Brand of Jacket 24 : " + p24.brand + ", color : " + p24.color + ", size : " + p24.size + ", price : " + p24.price + ", material : " + p24.material);
        System.out.println("Brand of Jacket 25 : " + p25.brand + ", color : " + p25.color + ", size : " + p25.size + ", price : " + p25.price + ", material : " + p25.material);
    }
}