class NutritionTableExecutor {
    public static void main(String[] args) {
        NutritionTable nutrition1 = new NutritionTable();
        nutrition1.setFoodItem("Paneer Tikka");
        nutrition1.setServingSize("100g");
        nutrition1.setCalories(265.0);
        nutrition1.setProtein(18.0);
        nutrition1.setCarbohydrates(4.0);
        nutrition1.setFats(20.0);
        nutrition1.setVitamins("B12, Calcium");
        System.out.println("Food Item: " + nutrition1.getFoodItem());
        System.out.println("Serving Size: " + nutrition1.getServingSize());
        System.out.println("Calories: " + nutrition1.getCalories());
        System.out.println("Protein: " + nutrition1.getProtein());
        System.out.println("Carbohydrates: " + nutrition1.getCarbohydrates());
        System.out.println("Fats: " + nutrition1.getFats());
        System.out.println("Vitamins: " + nutrition1.getVitamins());

        NutritionTable nutrition2 = new NutritionTable();
        nutrition2.setFoodItem("Moong Dal Tadka");
        nutrition2.setServingSize("1 Cup");
        nutrition2.setCalories(150.0);
        nutrition2.setProtein(7.0);
        nutrition2.setCarbohydrates(20.0);
        nutrition2.setFats(4.0);
        nutrition2.setVitamins("Folate, Iron");
        System.out.println("Food Item: " + nutrition2.getFoodItem());
        System.out.println("Serving Size: " + nutrition2.getServingSize());
        System.out.println("Calories: " + nutrition2.getCalories());
        System.out.println("Protein: " + nutrition2.getProtein());
        System.out.println("Carbohydrates: " + nutrition2.getCarbohydrates());
        System.out.println("Fats: " + nutrition2.getFats());
        System.out.println("Vitamins: " + nutrition2.getVitamins());

        NutritionTable nutrition3 = new NutritionTable();
        nutrition3.setFoodItem("Masala Dosa");
        nutrition3.setServingSize("1 Plate");
        nutrition3.setCalories(387.0);
        nutrition3.setProtein(4.0);
        nutrition3.setCarbohydrates(55.0);
        nutrition3.setFats(17.0);
        nutrition3.setVitamins("B6, Potassium");
        System.out.println("Food Item: " + nutrition3.getFoodItem());
        System.out.println("Serving Size: " + nutrition3.getServingSize());
        System.out.println("Calories: " + nutrition3.getCalories());
        System.out.println("Protein: " + nutrition3.getProtein());
        System.out.println("Carbohydrates: " + nutrition3.getCarbohydrates());
        System.out.println("Fats: " + nutrition3.getFats());
        System.out.println("Vitamins: " + nutrition3.getVitamins());

        NutritionTable nutrition4 = new NutritionTable();
        nutrition4.setFoodItem("Butter Chicken");
        nutrition4.setServingSize("150g");
        nutrition4.setCalories(350.0);
        nutrition4.setProtein(25.0);
        nutrition4.setCarbohydrates(8.0);
        nutrition4.setFats(22.0);
        nutrition4.setVitamins("B12, A");
        System.out.println("Food Item: " + nutrition4.getFoodItem());
        System.out.println("Serving Size: " + nutrition4.getServingSize());
        System.out.println("Calories: " + nutrition4.getCalories());
        System.out.println("Protein: " + nutrition4.getProtein());
        System.out.println("Carbohydrates: " + nutrition4.getCarbohydrates());
        System.out.println("Fats: " + nutrition4.getFats());
        System.out.println("Vitamins: " + nutrition4.getVitamins());

        NutritionTable nutrition5 = new NutritionTable();
        nutrition5.setFoodItem("Steamed Idli");
        nutrition5.setServingSize("2 Pieces");
        nutrition5.setCalories(116.0);
        nutrition5.setProtein(3.5);
        nutrition5.setCarbohydrates(25.0);
        nutrition5.setFats(0.4);
        nutrition5.setVitamins("B1, B3");
        System.out.println("Food Item: " + nutrition5.getFoodItem());
        System.out.println("Serving Size: " + nutrition5.getServingSize());
        System.out.println("Calories: " + nutrition5.getCalories());
        System.out.println("Protein: " + nutrition5.getProtein());
        System.out.println("Carbohydrates: " + nutrition5.getCarbohydrates());
        System.out.println("Fats: " + nutrition5.getFats());
        System.out.println("Vitamins: " + nutrition5.getVitamins());

        NutritionTable nutrition6 = new NutritionTable();
        nutrition6.setFoodItem("Palak Paneer");
        nutrition6.setServingSize("1 Bowl");
        nutrition6.setCalories(190.0);
        nutrition6.setProtein(9.0);
        nutrition6.setCarbohydrates(6.0);
        nutrition6.setFats(15.0);
        nutrition6.setVitamins("A, K, Iron");
        System.out.println("Food Item: " + nutrition6.getFoodItem());
        System.out.println("Serving Size: " + nutrition6.getServingSize());
        System.out.println("Calories: " + nutrition6.getCalories());
        System.out.println("Protein: " + nutrition6.getProtein());
        System.out.println("Carbohydrates: " + nutrition6.getCarbohydrates());
        System.out.println("Fats: " + nutrition6.getFats());
        System.out.println("Vitamins: " + nutrition6.getVitamins());

        NutritionTable nutrition7 = new NutritionTable();
        nutrition7.setFoodItem("Whole Wheat Roti");
        nutrition7.setServingSize("1 Piece");
        nutrition7.setCalories(71.0);
        nutrition7.setProtein(3.0);
        nutrition7.setCarbohydrates(15.0);
        nutrition7.setFats(0.4);
        nutrition7.setVitamins("Fiber, Selenium");
        System.out.println("Food Item: " + nutrition7.getFoodItem());
        System.out.println("Serving Size: " + nutrition7.getServingSize());
        System.out.println("Calories: " + nutrition7.getCalories());
        System.out.println("Protein: " + nutrition7.getProtein());
        System.out.println("Carbohydrates: " + nutrition7.getCarbohydrates());
        System.out.println("Fats: " + nutrition7.getFats());
        System.out.println("Vitamins: " + nutrition7.getVitamins());

        NutritionTable nutrition8 = new NutritionTable();
        nutrition8.setFoodItem("Alu Gobi");
        nutrition8.setServingSize("100g");
        nutrition8.setCalories(110.0);
        nutrition8.setProtein(2.0);
        nutrition8.setCarbohydrates(16.0);
        nutrition8.setFats(5.0);
        nutrition8.setVitamins("C, K");
        System.out.println("Food Item: " + nutrition8.getFoodItem());
        System.out.println("Serving Size: " + nutrition8.getServingSize());
        System.out.println("Calories: " + nutrition8.getCalories());
        System.out.println("Protein: " + nutrition8.getProtein());
        System.out.println("Carbohydrates: " + nutrition8.getCarbohydrates());
        System.out.println("Fats: " + nutrition8.getFats());
        System.out.println("Vitamins: " + nutrition8.getVitamins());

        NutritionTable nutrition9 = new NutritionTable();
        nutrition9.setFoodItem("Basmati Rice");
        nutrition9.setServingSize("1 Cup Cooked");
        nutrition9.setCalories(210.0);
        nutrition9.setProtein(4.4);
        nutrition9.setCarbohydrates(45.0);
        nutrition9.setFats(0.5);
        nutrition9.setVitamins("B1, Magnesium");
        System.out.println("Food Item: " + nutrition9.getFoodItem());
        System.out.println("Serving Size: " + nutrition9.getServingSize());
        System.out.println("Calories: " + nutrition9.getCalories());
        System.out.println("Protein: " + nutrition9.getProtein());
        System.out.println("Carbohydrates: " + nutrition9.getCarbohydrates());
        System.out.println("Fats: " + nutrition9.getFats());
        System.out.println("Vitamins: " + nutrition9.getVitamins());

        NutritionTable nutrition10 = new NutritionTable();
        nutrition10.setFoodItem("Gulab Jamun");
        nutrition10.setServingSize("1 Piece");
        nutrition10.setCalories(150.0);
        nutrition10.setProtein(2.0);
        nutrition10.setCarbohydrates(20.0);
        nutrition10.setFats(7.0);
        nutrition10.setVitamins("Calcium");
        System.out.println("Food Item: " + nutrition10.getFoodItem());
        System.out.println("Serving Size: " + nutrition10.getServingSize());
        System.out.println("Calories: " + nutrition10.getCalories());
        System.out.println("Protein: " + nutrition10.getProtein());
        System.out.println("Carbohydrates: " + nutrition10.getCarbohydrates());
        System.out.println("Fats: " + nutrition10.getFats());
        System.out.println("Vitamins: " + nutrition10.getVitamins());

        NutritionTable nutrition11 = new NutritionTable();
        nutrition11.setFoodItem("Samosa");
        nutrition11.setServingSize("1 Piece");
        nutrition11.setCalories(262.0);
        nutrition11.setProtein(3.5);
        nutrition11.setCarbohydrates(24.0);
        nutrition11.setFats(17.0);
        nutrition11.setVitamins("B6");
        System.out.println("Food Item: " + nutrition11.getFoodItem());
        System.out.println("Serving Size: " + nutrition11.getServingSize());
        System.out.println("Calories: " + nutrition11.getCalories());
        System.out.println("Protein: " + nutrition11.getProtein());
        System.out.println("Carbohydrates: " + nutrition11.getCarbohydrates());
        System.out.println("Fats: " + nutrition11.getFats());
        System.out.println("Vitamins: " + nutrition11.getVitamins());

        NutritionTable nutrition12 = new NutritionTable();
        nutrition12.setFoodItem("Chicken Biryani");
        nutrition12.setServingSize("1 Plate");
        nutrition12.setCalories(480.0);
        nutrition12.setProtein(22.0);
        nutrition12.setCarbohydrates(55.0);
        nutrition12.setFats(18.0);
        nutrition12.setVitamins("B12, Zinc");
        System.out.println("Food Item: " + nutrition12.getFoodItem());
        System.out.println("Serving Size: " + nutrition12.getServingSize());
        System.out.println("Calories: " + nutrition12.getCalories());
        System.out.println("Protein: " + nutrition12.getProtein());
        System.out.println("Carbohydrates: " + nutrition12.getCarbohydrates());
        System.out.println("Fats: " + nutrition12.getFats());
        System.out.println("Vitamins: " + nutrition12.getVitamins());

        NutritionTable nutrition13 = new NutritionTable();
        nutrition13.setFoodItem("Greek Yogurt");
        nutrition13.setServingSize("100g");
        nutrition13.setCalories(59.0);
        nutrition13.setProtein(10.0);
        nutrition13.setCarbohydrates(3.6);
        nutrition13.setFats(0.4);
        nutrition13.setVitamins("B12, Calcium");
        System.out.println("Food Item: " + nutrition13.getFoodItem());
        System.out.println("Serving Size: " + nutrition13.getServingSize());
        System.out.println("Calories: " + nutrition13.getCalories());
        System.out.println("Protein: " + nutrition13.getProtein());
        System.out.println("Carbohydrates: " + nutrition13.getCarbohydrates());
        System.out.println("Fats: " + nutrition13.getFats());
        System.out.println("Vitamins: " + nutrition13.getVitamins());

        NutritionTable nutrition14 = new NutritionTable();
        nutrition14.setFoodItem("Boiled Egg");
        nutrition14.setServingSize("1 Large");
        nutrition14.setCalories(78.0);
        nutrition14.setProtein(6.0);
        nutrition14.setCarbohydrates(0.6);
        nutrition14.setFats(5.0);
        nutrition14.setVitamins("D, B2, Selenium");
        System.out.println("Food Item: " + nutrition14.getFoodItem());
        System.out.println("Serving Size: " + nutrition14.getServingSize());
        System.out.println("Calories: " + nutrition14.getCalories());
        System.out.println("Protein: " + nutrition14.getProtein());
        System.out.println("Carbohydrates: " + nutrition14.getCarbohydrates());
        System.out.println("Fats: " + nutrition14.getFats());
        System.out.println("Vitamins: " + nutrition14.getVitamins());

        NutritionTable nutrition15 = new NutritionTable();
        nutrition15.setFoodItem("Masala Chai");
        nutrition15.setServingSize("1 Cup");
        nutrition15.setCalories(60.0);
        nutrition15.setProtein(2.0);
        nutrition15.setCarbohydrates(8.0);
        nutrition15.setFats(2.5);
        nutrition15.setVitamins("Antioxidants");
        System.out.println("Food Item: " + nutrition15.getFoodItem());
        System.out.println("Serving Size: " + nutrition15.getServingSize());
        System.out.println("Calories: " + nutrition15.getCalories());
        System.out.println("Protein: " + nutrition15.getProtein());
        System.out.println("Carbohydrates: " + nutrition15.getCarbohydrates());
        System.out.println("Fats: " + nutrition15.getFats());
        System.out.println("Vitamins: " + nutrition15.getVitamins());

        NutritionTable nutrition16 = new NutritionTable();
        nutrition16.setFoodItem("Chole Bhature");
        nutrition16.setServingSize("1 Plate");
        nutrition16.setCalories(450.0);
        nutrition16.setProtein(12.0);
        nutrition16.setCarbohydrates(65.0);
        nutrition16.setFats(18.0);
        nutrition16.setVitamins("Iron, Fiber");
        System.out.println("Food Item: " + nutrition16.getFoodItem());
        System.out.println("Serving Size: " + nutrition16.getServingSize());
        System.out.println("Calories: " + nutrition16.getCalories());
        System.out.println("Protein: " + nutrition16.getProtein());
        System.out.println("Carbohydrates: " + nutrition16.getCarbohydrates());
        System.out.println("Fats: " + nutrition16.getFats());
        System.out.println("Vitamins: " + nutrition16.getVitamins());

        NutritionTable nutrition17 = new NutritionTable();
        nutrition17.setFoodItem("Raw Almonds");
        nutrition17.setServingSize("28g");
        nutrition17.setCalories(164.0);
        nutrition17.setProtein(6.0);
        nutrition17.setCarbohydrates(6.1);
        nutrition17.setFats(14.0);
        nutrition17.setVitamins("E, Magnesium");
        System.out.println("Food Item: " + nutrition17.getFoodItem());
        System.out.println("Serving Size: " + nutrition17.getServingSize());
        System.out.println("Calories: " + nutrition17.getCalories());
        System.out.println("Protein: " + nutrition17.getProtein());
        System.out.println("Carbohydrates: " + nutrition17.getCarbohydrates());
        System.out.println("Fats: " + nutrition17.getFats());
        System.out.println("Vitamins: " + nutrition17.getVitamins());

        NutritionTable nutrition18 = new NutritionTable();
        nutrition18.setFoodItem("Banana");
        nutrition18.setServingSize("1 Medium");
        nutrition18.setCalories(105.0);
        nutrition18.setProtein(1.3);
        nutrition18.setCarbohydrates(27.0);
        nutrition18.setFats(0.3);
        nutrition18.setVitamins("C, B6, Potassium");
        System.out.println("Food Item: " + nutrition18.getFoodItem());
        System.out.println("Serving Size: " + nutrition18.getServingSize());
        System.out.println("Calories: " + nutrition18.getCalories());
        System.out.println("Protein: " + nutrition18.getProtein());
        System.out.println("Carbohydrates: " + nutrition18.getCarbohydrates());
        System.out.println("Fats: " + nutrition18.getFats());
        System.out.println("Vitamins: " + nutrition18.getVitamins());

        NutritionTable nutrition19 = new NutritionTable();
        nutrition19.setFoodItem("Upma");
        nutrition19.setServingSize("1 Bowl");
        nutrition19.setCalories(210.0);
        nutrition19.setProtein(5.0);
        nutrition19.setCarbohydrates(38.0);
        nutrition19.setFats(4.0);
        nutrition19.setVitamins("B-Complex");
        System.out.println("Food Item: " + nutrition19.getFoodItem());
        System.out.println("Serving Size: " + nutrition19.getServingSize());
        System.out.println("Calories: " + nutrition19.getCalories());
        System.out.println("Protein: " + nutrition19.getProtein());
        System.out.println("Carbohydrates: " + nutrition19.getCarbohydrates());
        System.out.println("Fats: " + nutrition19.getFats());
        System.out.println("Vitamins: " + nutrition19.getVitamins());

        NutritionTable nutrition20 = new NutritionTable();
        nutrition20.setFoodItem("Cucumber");
        nutrition20.setServingSize("100g");
        nutrition20.setCalories(15.0);
        nutrition20.setProtein(0.7);
        nutrition20.setCarbohydrates(3.6);
        nutrition20.setFats(0.1);
        nutrition20.setVitamins("K, C");
        System.out.println("Food Item: " + nutrition20.getFoodItem());
        System.out.println("Serving Size: " + nutrition20.getServingSize());
        System.out.println("Calories: " + nutrition20.getCalories());
        System.out.println("Protein: " + nutrition20.getProtein());
        System.out.println("Carbohydrates: " + nutrition20.getCarbohydrates());
        System.out.println("Fats: " + nutrition20.getFats());
        System.out.println("Vitamins: " + nutrition20.getVitamins());

        NutritionTable nutrition21 = new NutritionTable();
        nutrition21.setFoodItem("Chicken Tikka");
        nutrition21.setServingSize("100g");
        nutrition21.setCalories(150.0);
        nutrition21.setProtein(24.0);
        nutrition21.setCarbohydrates(2.0);
        nutrition21.setFats(5.0);
        nutrition21.setVitamins("B6, Niacin");
        System.out.println("Food Item: " + nutrition21.getFoodItem());
        System.out.println("Serving Size: " + nutrition21.getServingSize());
        System.out.println("Calories: " + nutrition21.getCalories());
        System.out.println("Protein: " + nutrition21.getProtein());
        System.out.println("Carbohydrates: " + nutrition21.getCarbohydrates());
        System.out.println("Fats: " + nutrition21.getFats());
        System.out.println("Vitamins: " + nutrition21.getVitamins());

        NutritionTable nutrition22 = new NutritionTable();
        nutrition22.setFoodItem("Apple");
        nutrition22.setServingSize("1 Large");
        nutrition22.setCalories(116.0);
        nutrition22.setProtein(0.6);
        nutrition22.setCarbohydrates(30.0);
        nutrition22.setFats(0.4);
        nutrition22.setVitamins("C, Fiber");
        System.out.println("Food Item: " + nutrition22.getFoodItem());
        System.out.println("Serving Size: " + nutrition22.getServingSize());
        System.out.println("Calories: " + nutrition22.getCalories());
        System.out.println("Protein: " + nutrition22.getProtein());
        System.out.println("Carbohydrates: " + nutrition22.getCarbohydrates());
        System.out.println("Fats: " + nutrition22.getFats());
        System.out.println("Vitamins: " + nutrition22.getVitamins());

        NutritionTable nutrition23 = new NutritionTable();
        nutrition23.setFoodItem("Lentil Soup");
        nutrition23.setServingSize("1 Bowl");
        nutrition23.setCalories(180.0);
        nutrition23.setProtein(10.0);
        nutrition23.setCarbohydrates(28.0);
        nutrition23.setFats(3.0);
        nutrition23.setVitamins("Iron, Folate");
        System.out.println("Food Item: " + nutrition23.getFoodItem());
        System.out.println("Serving Size: " + nutrition23.getServingSize());
        System.out.println("Calories: " + nutrition23.getCalories());
        System.out.println("Protein: " + nutrition23.getProtein());
        System.out.println("Carbohydrates: " + nutrition23.getCarbohydrates());
        System.out.println("Fats: " + nutrition23.getFats());
        System.out.println("Vitamins: " + nutrition23.getVitamins());

        NutritionTable nutrition24 = new NutritionTable();
        nutrition24.setFoodItem("Oats");
        nutrition24.setServingSize("40g");
        nutrition24.setCalories(154.0);
        nutrition24.setProtein(5.0);
        nutrition24.setCarbohydrates(27.0);
        nutrition24.setFats(2.6);
        nutrition24.setVitamins("B1, Iron");
        System.out.println("Food Item: " + nutrition24.getFoodItem());
        System.out.println("Serving Size: " + nutrition24.getServingSize());
        System.out.println("Calories: " + nutrition24.getCalories());
        System.out.println("Protein: " + nutrition24.getProtein());
        System.out.println("Carbohydrates: " + nutrition24.getCarbohydrates());
        System.out.println("Fats: " + nutrition24.getFats());
        System.out.println("Vitamins: " + nutrition24.getVitamins());

        NutritionTable nutrition25 = new NutritionTable();
        nutrition25.setFoodItem("Avocado");
        nutrition25.setServingSize("100g");
        nutrition25.setCalories(160.0);
        nutrition25.setProtein(2.0);
        nutrition25.setCarbohydrates(8.5);
        nutrition25.setFats(14.7);
        nutrition25.setVitamins("K, E, C");
        System.out.println("Food Item: " + nutrition25.getFoodItem());
        System.out.println("Serving Size: " + nutrition25.getServingSize());
        System.out.println("Calories: " + nutrition25.getCalories());
        System.out.println("Protein: " + nutrition25.getProtein());
        System.out.println("Carbohydrates: " + nutrition25.getCarbohydrates());
        System.out.println("Fats: " + nutrition25.getFats());
        System.out.println("Vitamins: " + nutrition25.getVitamins());

        NutritionTable nutrition26 = new NutritionTable();
        nutrition26.setFoodItem("Salmon");
        nutrition26.setServingSize("100g");
        nutrition26.setCalories(208.0);
        nutrition26.setProtein(20.0);
        nutrition26.setCarbohydrates(0.0);
        nutrition26.setFats(13.0);
        nutrition26.setVitamins("D, B12, Omega-3");
        System.out.println("Food Item: " + nutrition26.getFoodItem());
        System.out.println("Serving Size: " + nutrition26.getServingSize());
        System.out.println("Calories: " + nutrition26.getCalories());
        System.out.println("Protein: " + nutrition26.getProtein());
        System.out.println("Carbohydrates: " + nutrition26.getCarbohydrates());
        System.out.println("Fats: " + nutrition26.getFats());
        System.out.println("Vitamins: " + nutrition26.getVitamins());

        NutritionTable nutrition27 = new NutritionTable();
        nutrition27.setFoodItem("Sweet Potato");
        nutrition27.setServingSize("100g");
        nutrition27.setCalories(86.0);
        nutrition27.setProtein(1.6);
        nutrition27.setCarbohydrates(20.0);
        nutrition27.setFats(0.1);
        nutrition27.setVitamins("A, C");
        System.out.println("Food Item: " + nutrition27.getFoodItem());
        System.out.println("Serving Size: " + nutrition27.getServingSize());
        System.out.println("Calories: " + nutrition27.getCalories());
        System.out.println("Protein: " + nutrition27.getProtein());
        System.out.println("Carbohydrates: " + nutrition27.getCarbohydrates());
        System.out.println("Fats: " + nutrition27.getFats());
        System.out.println("Vitamins: " + nutrition27.getVitamins());

        NutritionTable nutrition28 = new NutritionTable();
        nutrition28.setFoodItem("Spinach");
        nutrition28.setServingSize("100g Raw");
        nutrition28.setCalories(23.0);
        nutrition28.setProtein(2.9);
        nutrition28.setCarbohydrates(3.6);
        nutrition28.setFats(0.4);
        nutrition28.setVitamins("A, C, K, Iron");
        System.out.println("Food Item: " + nutrition28.getFoodItem());
        System.out.println("Serving Size: " + nutrition28.getServingSize());
        System.out.println("Calories: " + nutrition28.getCalories());
        System.out.println("Protein: " + nutrition28.getProtein());
        System.out.println("Carbohydrates: " + nutrition28.getCarbohydrates());
        System.out.println("Fats: " + nutrition28.getFats());
        System.out.println("Vitamins: " + nutrition28.getVitamins());

        NutritionTable nutrition29 = new NutritionTable();
        nutrition29.setFoodItem("Quinoa");
        nutrition29.setServingSize("1 Cup Cooked");
        nutrition29.setCalories(222.0);
        nutrition29.setProtein(8.1);
        nutrition29.setCarbohydrates(39.0);
        nutrition29.setFats(3.6);
        nutrition29.setVitamins("B6, Magnesium");
        System.out.println("Food Item: " + nutrition29.getFoodItem());
        System.out.println("Serving Size: " + nutrition29.getServingSize());
        System.out.println("Calories: " + nutrition29.getCalories());
        System.out.println("Protein: " + nutrition29.getProtein());
        System.out.println("Carbohydrates: " + nutrition29.getCarbohydrates());
        System.out.println("Fats: " + nutrition29.getFats());
        System.out.println("Vitamins: " + nutrition29.getVitamins());
    }
}