class PlayerExecutor {
    public static void main(String[] args) {
        Player player1 = new Player();
        player1.setPlayerName("Virat Kohli");
        player1.setSport("Cricket");
        player1.setAge(37);
        player1.setTeamName("India");
        player1.setMatchesPlayed(500);
        player1.setRole("Batsman");
        player1.setNationality("Indian");
        System.out.println("Player Name: " + player1.getPlayerName());
        System.out.println("Sport: " + player1.getSport());
        System.out.println("Age: " + player1.getAge());
        System.out.println("Team Name: " + player1.getTeamName());
        System.out.println("Matches Played: " + player1.getMatchesPlayed());
        System.out.println("Role: " + player1.getRole());
        System.out.println("Nationality: " + player1.getNationality());

        Player player2 = new Player();
        player2.setPlayerName("Sunil Chhetri");
        player2.setSport("Football");
        player2.setAge(41);
        player2.setTeamName("Bengaluru FC");
        player2.setMatchesPlayed(150);
        player2.setRole("Forward");
        player2.setNationality("Indian");
        System.out.println("Player Name: " + player2.getPlayerName());
        System.out.println("Sport: " + player2.getSport());
        System.out.println("Age: " + player2.getAge());
        System.out.println("Team Name: " + player2.getTeamName());
        System.out.println("Matches Played: " + player2.getMatchesPlayed());
        System.out.println("Role: " + player2.getRole());
        System.out.println("Nationality: " + player2.getNationality());

        Player player3 = new Player();
        player3.setPlayerName("P.V. Sindhu");
        player3.setSport("Badminton");
        player3.setAge(30);
        player3.setTeamName("India");
        player3.setMatchesPlayed(300);
        player3.setRole("Single Player");
        player3.setNationality("Indian");
        System.out.println("Player Name: " + player3.getPlayerName());
        System.out.println("Sport: " + player3.getSport());
        System.out.println("Age: " + player3.getAge());
        System.out.println("Team Name: " + player3.getTeamName());
        System.out.println("Matches Played: " + player3.getMatchesPlayed());
        System.out.println("Role: " + player3.getRole());
        System.out.println("Nationality: " + player3.getNationality());

        Player player4 = new Player();
        player4.setPlayerName("Rohit Sharma");
        player4.setSport("Cricket");
        player4.setAge(38);
        player4.setTeamName("Mumbai Indians");
        player4.setMatchesPlayed(450);
        player4.setRole("Opening Batsman");
        player4.setNationality("Indian");
        System.out.println("Player Name: " + player4.getPlayerName());
        System.out.println("Sport: " + player4.getSport());
        System.out.println("Age: " + player4.getAge());
        System.out.println("Team Name: " + player4.getTeamName());
        System.out.println("Matches Played: " + player4.getMatchesPlayed());
        System.out.println("Role: " + player4.getRole());
        System.out.println("Nationality: " + player4.getNationality());

        Player player5 = new Player();
        player5.setPlayerName("Neeraj Chopra");
        player5.setSport("Javelin Throw");
        player5.setAge(28);
        player5.setTeamName("India Athletics");
        player5.setMatchesPlayed(45);
        player5.setRole("Athlete");
        player5.setNationality("Indian");
        System.out.println("Player Name: " + player5.getPlayerName());
        System.out.println("Sport: " + player5.getSport());
        System.out.println("Age: " + player5.getAge());
        System.out.println("Team Name: " + player5.getTeamName());
        System.out.println("Matches Played: " + player5.getMatchesPlayed());
        System.out.println("Role: " + player5.getRole());
        System.out.println("Nationality: " + player5.getNationality());

        Player player6 = new Player();
        player6.setPlayerName("Saina Nehwal");
        player6.setSport("Badminton");
        player6.setAge(36);
        player6.setTeamName("India");
        player6.setMatchesPlayed(420);
        player6.setRole("Single Player");
        player6.setNationality("Indian");
        System.out.println("Player Name: " + player6.getPlayerName());
        System.out.println("Sport: " + player6.getSport());
        System.out.println("Age: " + player6.getAge());
        System.out.println("Team Name: " + player6.getTeamName());
        System.out.println("Matches Played: " + player6.getMatchesPlayed());
        System.out.println("Role: " + player6.getRole());
        System.out.println("Nationality: " + player6.getNationality());

        Player player7 = new Player();
        player7.setPlayerName("Manpreet Singh");
        player7.setSport("Hockey");
        player7.setAge(33);
        player7.setTeamName("India National Hockey");
        player7.setMatchesPlayed(280);
        player7.setRole("Midfielder");
        player7.setNationality("Indian");
        System.out.println("Player Name: " + player7.getPlayerName());
        System.out.println("Sport: " + player7.getSport());
        System.out.println("Age: " + player7.getAge());
        System.out.println("Team Name: " + player7.getTeamName());
        System.out.println("Matches Played: " + player7.getMatchesPlayed());
        System.out.println("Role: " + player7.getRole());
        System.out.println("Nationality: " + player7.getNationality());

        Player player8 = new Player();
        player8.setPlayerName("Viswanathan Anand");
        player8.setSport("Chess");
        player8.setAge(56);
        player8.setTeamName("India");
        player8.setMatchesPlayed(1200);
        player8.setRole("Grandmaster");
        player8.setNationality("Indian");
        System.out.println("Player Name: " + player8.getPlayerName());
        System.out.println("Sport: " + player8.getSport());
        System.out.println("Age: " + player8.getAge());
        System.out.println("Team Name: " + player8.getTeamName());
        System.out.println("Matches Played: " + player8.getMatchesPlayed());
        System.out.println("Role: " + player8.getRole());
        System.out.println("Nationality: " + player8.getNationality());

        Player player9 = new Player();
        player9.setPlayerName("Mary Kom");
        player9.setSport("Boxing");
        player9.setAge(43);
        player9.setTeamName("India Boxing");
        player9.setMatchesPlayed(110);
        player9.setRole("Flyweight");
        player9.setNationality("Indian");
        System.out.println("Player Name: " + player9.getPlayerName());
        System.out.println("Sport: " + player9.getSport());
        System.out.println("Age: " + player9.getAge());
        System.out.println("Team Name: " + player9.getTeamName());
        System.out.println("Matches Played: " + player9.getMatchesPlayed());
        System.out.println("Role: " + player9.getRole());
        System.out.println("Nationality: " + player9.getNationality());

        Player player10 = new Player();
        player10.setPlayerName("Jasprit Bumrah");
        player10.setSport("Cricket");
        player10.setAge(32);
        player10.setTeamName("India");
        player10.setMatchesPlayed(180);
        player10.setRole("Fast Bowler");
        player10.setNationality("Indian");
        System.out.println("Player Name: " + player10.getPlayerName());
        System.out.println("Sport: " + player10.getSport());
        System.out.println("Age: " + player10.getAge());
        System.out.println("Team Name: " + player10.getTeamName());
        System.out.println("Matches Played: " + player10.getMatchesPlayed());
        System.out.println("Role: " + player10.getRole());
        System.out.println("Nationality: " + player10.getNationality());

        Player player11 = new Player();
        player11.setPlayerName("Ravindra Jadeja");
        player11.setSport("Cricket");
        player11.setAge(37);
        player11.setTeamName("Chennai Super Kings");
        player11.setMatchesPlayed(320);
        player11.setRole("All Rounder");
        player11.setNationality("Indian");
        System.out.println("Player Name: " + player11.getPlayerName());
        System.out.println("Sport: " + player11.getSport());
        System.out.println("Age: " + player11.getAge());
        System.out.println("Team Name: " + player11.getTeamName());
        System.out.println("Matches Played: " + player11.getMatchesPlayed());
        System.out.println("Role: " + player11.getRole());
        System.out.println("Nationality: " + player11.getNationality());

        Player player12 = new Player();
        player12.setPlayerName("Bajrang Punia");
        player12.setSport("Wrestling");
        player12.setAge(32);
        player12.setTeamName("India Wrestling");
        player12.setMatchesPlayed(85);
        player12.setRole("Freestyle Wrestler");
        player12.setNationality("Indian");
        System.out.println("Player Name: " + player12.getPlayerName());
        System.out.println("Sport: " + player12.getSport());
        System.out.println("Age: " + player12.getAge());
        System.out.println("Team Name: " + player12.getTeamName());
        System.out.println("Matches Played: " + player12.getMatchesPlayed());
        System.out.println("Role: " + player12.getRole());
        System.out.println("Nationality: " + player12.getNationality());

        Player player13 = new Player();
        player13.setPlayerName("Mithali Raj");
        player13.setSport("Cricket");
        player13.setAge(43);
        player13.setTeamName("India Women");
        player13.setMatchesPlayed(332);
        player13.setRole("Batsman");
        player13.setNationality("Indian");
        System.out.println("Player Name: " + player13.getPlayerName());
        System.out.println("Sport: " + player13.getSport());
        System.out.println("Age: " + player13.getAge());
        System.out.println("Team Name: " + player13.getTeamName());
        System.out.println("Matches Played: " + player13.getMatchesPlayed());
        System.out.println("Role: " + player13.getRole());
        System.out.println("Nationality: " + player13.getNationality());

        Player player14 = new Player();
        player14.setPlayerName("Harmanpreet Kaur");
        player14.setSport("Cricket");
        player14.setAge(37);
        player14.setTeamName("India Women");
        player14.setMatchesPlayed(280);
        player14.setRole("All Rounder");
        player14.setNationality("Indian");
        System.out.println("Player Name: " + player14.getPlayerName());
        System.out.println("Sport: " + player14.getSport());
        System.out.println("Age: " + player14.getAge());
        System.out.println("Team Name: " + player14.getTeamName());
        System.out.println("Matches Played: " + player14.getMatchesPlayed());
        System.out.println("Role: " + player14.getRole());
        System.out.println("Nationality: " + player14.getNationality());

        Player player15 = new Player();
        player15.setPlayerName("Anirban Lahiri");
        player15.setSport("Golf");
        player15.setAge(38);
        player15.setTeamName("India Golf");
        player15.setMatchesPlayed(210);
        player15.setRole("Professional Golfer");
        player15.setNationality("Indian");
        System.out.println("Player Name: " + player15.getPlayerName());
        System.out.println("Sport: " + player15.getSport());
        System.out.println("Age: " + player15.getAge());
        System.out.println("Team Name: " + player15.getTeamName());
        System.out.println("Matches Played: " + player15.getMatchesPlayed());
        System.out.println("Role: " + player15.getRole());
        System.out.println("Nationality: " + player15.getNationality());

        Player player16 = new Player();
        player16.setPlayerName("Kidambi Srikanth");
        player16.setSport("Badminton");
        player16.setAge(33);
        player16.setTeamName("India");
        player16.setMatchesPlayed(340);
        player16.setRole("Single Player");
        player16.setNationality("Indian");
        System.out.println("Player Name: " + player16.getPlayerName());
        System.out.println("Sport: " + player16.getSport());
        System.out.println("Age: " + player16.getAge());
        System.out.println("Team Name: " + player16.getTeamName());
        System.out.println("Matches Played: " + player16.getMatchesPlayed());
        System.out.println("Role: " + player16.getRole());
        System.out.println("Nationality: " + player16.getNationality());

        Player player17 = new Player();
        player17.setPlayerName("Sania Mirza");
        player17.setSport("Tennis");
        player17.setAge(39);
        player17.setTeamName("India");
        player17.setMatchesPlayed(560);
        player17.setRole("Doubles Specialist");
        player17.setNationality("Indian");
        System.out.println("Player Name: " + player17.getPlayerName());
        System.out.println("Sport: " + player17.getSport());
        System.out.println("Age: " + player17.getAge());
        System.out.println("Team Name: " + player17.getTeamName());
        System.out.println("Matches Played: " + player17.getMatchesPlayed());
        System.out.println("Role: " + player17.getRole());
        System.out.println("Nationality: " + player17.getNationality());

        Player player18 = new Player();
        player18.setPlayerName("Shubman Gill");
        player18.setSport("Cricket");
        player18.setAge(26);
        player18.setTeamName("Gujarat Titans");
        player18.setMatchesPlayed(95);
        player18.setRole("Opening Batsman");
        player18.setNationality("Indian");
        System.out.println("Player Name: " + player18.getPlayerName());
        System.out.println("Sport: " + player18.getSport());
        System.out.println("Age: " + player18.getAge());
        System.out.println("Team Name: " + player18.getTeamName());
        System.out.println("Matches Played: " + player18.getMatchesPlayed());
        System.out.println("Role: " + player18.getRole());
        System.out.println("Nationality: " + player18.getNationality());

        Player player19 = new Player();
        player19.setPlayerName("Rishabh Pant");
        player19.setSport("Cricket");
        player19.setAge(28);
        player19.setTeamName("Delhi Capitals");
        player19.setMatchesPlayed(130);
        player19.setRole("Wicketkeeper Batsman");
        player19.setNationality("Indian");
        System.out.println("Player Name: " + player19.getPlayerName());
        System.out.println("Sport: " + player19.getSport());
        System.out.println("Age: " + player19.getAge());
        System.out.println("Team Name: " + player19.getTeamName());
        System.out.println("Matches Played: " + player19.getMatchesPlayed());
        System.out.println("Role: " + player19.getRole());
        System.out.println("Nationality: " + player19.getNationality());

        Player player20 = new Player();
        player20.setPlayerName("Lakshya Sen");
        player20.setSport("Badminton");
        player20.setAge(24);
        player20.setTeamName("India");
        player20.setMatchesPlayed(120);
        player20.setRole("Single Player");
        player20.setNationality("Indian");
        System.out.println("Player Name: " + player20.getPlayerName());
        System.out.println("Sport: " + player20.getSport());
        System.out.println("Age: " + player20.getAge());
        System.out.println("Team Name: " + player20.getTeamName());
        System.out.println("Matches Played: " + player20.getMatchesPlayed());
        System.out.println("Role: " + player20.getRole());
        System.out.println("Nationality: " + player20.getNationality());

        Player player21 = new Player();
        player21.setPlayerName("Lovelina Borgohain");
        player21.setSport("Boxing");
        player21.setAge(28);
        player21.setTeamName("India Boxing");
        player21.setMatchesPlayed(65);
        player21.setRole("Welterweight");
        player21.setNationality("Indian");
        System.out.println("Player Name: " + player21.getPlayerName());
        System.out.println("Sport: " + player21.getSport());
        System.out.println("Age: " + player21.getAge());
        System.out.println("Team Name: " + player21.getTeamName());
        System.out.println("Matches Played: " + player21.getMatchesPlayed());
        System.out.println("Role: " + player21.getRole());
        System.out.println("Nationality: " + player21.getNationality());

        Player player22 = new Player();
        player22.setPlayerName("Mirabai Chanu");
        player22.setSport("Weightlifting");
        player22.setAge(31);
        player22.setTeamName("India National");
        player22.setMatchesPlayed(55);
        player22.setRole("49kg Category");
        player22.setNationality("Indian");
        System.out.println("Player Name: " + player22.getPlayerName());
        System.out.println("Sport: " + player22.getSport());
        System.out.println("Age: " + player22.getAge());
        System.out.println("Team Name: " + player22.getTeamName());
        System.out.println("Matches Played: " + player22.getMatchesPlayed());
        System.out.println("Role: " + player22.getRole());
        System.out.println("Nationality: " + player22.getNationality());

        Player player23 = new Player();
        player23.setPlayerName("Savita Punia");
        player23.setSport("Hockey");
        player23.setAge(35);
        player23.setTeamName("India Women Hockey");
        player23.setMatchesPlayed(210);
        player23.setRole("Goalkeeper");
        player23.setNationality("Indian");
        System.out.println("Player Name: " + player23.getPlayerName());
        System.out.println("Sport: " + player23.getSport());
        System.out.println("Age: " + player23.getAge());
        System.out.println("Team Name: " + player23.getTeamName());
        System.out.println("Matches Played: " + player23.getMatchesPlayed());
        System.out.println("Role: " + player23.getRole());
        System.out.println("Nationality: " + player23.getNationality());

        Player player24 = new Player();
        player24.setPlayerName("Yuzvendra Chahal");
        player24.setSport("Cricket");
        player24.setAge(35);
        player24.setTeamName("Rajasthan Royals");
        player24.setMatchesPlayed(160);
        player24.setRole("Leg Spinner");
        player24.setNationality("Indian");
        System.out.println("Player Name: " + player24.getPlayerName());
        System.out.println("Sport: " + player24.getSport());
        System.out.println("Age: " + player24.getAge());
        System.out.println("Team Name: " + player24.getTeamName());
        System.out.println("Matches Played: " + player24.getMatchesPlayed());
        System.out.println("Role: " + player24.getRole());
        System.out.println("Nationality: " + player24.getNationality());

        Player player25 = new Player();
        player25.setPlayerName("Sandeep Singh");
        player25.setSport("Hockey");
        player25.setAge(40);
        player25.setTeamName("India");
        player25.setMatchesPlayed(186);
        player25.setRole("Drag Flicker");
        player25.setNationality("Indian");
        System.out.println("Player Name: " + player25.getPlayerName());
        System.out.println("Sport: " + player25.getSport());
        System.out.println("Age: " + player25.getAge());
        System.out.println("Team Name: " + player25.getTeamName());
        System.out.println("Matches Played: " + player25.getMatchesPlayed());
        System.out.println("Role: " + player25.getRole());
        System.out.println("Nationality: " + player25.getNationality());

        Player player26 = new Player();
        player26.setPlayerName("R Praggnanandhaa");
        player26.setSport("Chess");
        player26.setAge(20);
        player26.setTeamName("India");
        player26.setMatchesPlayed(400);
        player26.setRole("Grandmaster");
        player26.setNationality("Indian");
        System.out.println("Player Name: " + player26.getPlayerName());
        System.out.println("Sport: " + player26.getSport());
        System.out.println("Age: " + player26.getAge());
        System.out.println("Team Name: " + player26.getTeamName());
        System.out.println("Matches Played: " + player26.getMatchesPlayed());
        System.out.println("Role: " + player26.getRole());
        System.out.println("Nationality: " + player26.getNationality());

        Player player27 = new Player();
        player27.setPlayerName("Smriti Mandhana");
        player27.setSport("Cricket");
        player27.setAge(29);
        player27.setTeamName("India Women");
        player27.setMatchesPlayed(210);
        player27.setRole("Opening Batsman");
        player27.setNationality("Indian");
        System.out.println("Player Name: " + player27.getPlayerName());
        System.out.println("Sport: " + player27.getSport());
        System.out.println("Age: " + player27.getAge());
        System.out.println("Team Name: " + player27.getTeamName());
        System.out.println("Matches Played: " + player27.getMatchesPlayed());
        System.out.println("Role: " + player27.getRole());
        System.out.println("Nationality: " + player27.getNationality());

        Player player28 = new Player();
        player28.setPlayerName("Sathiyan Gnanasekaran");
        player28.setSport("Table Tennis");
        player28.setAge(33);
        player28.setTeamName("India");
        player28.setMatchesPlayed(155);
        player28.setRole("Professional Player");
        player28.setNationality("Indian");
        System.out.println("Player Name: " + player28.getPlayerName());
        System.out.println("Sport: " + player28.getSport());
        System.out.println("Age: " + player28.getAge());
        System.out.println("Team Name: " + player28.getTeamName());
        System.out.println("Matches Played: " + player28.getMatchesPlayed());
        System.out.println("Role: " + player28.getRole());
        System.out.println("Nationality: " + player28.getNationality());

        Player player29 = new Player();
        player29.setPlayerName("Hima Das");
        player29.setSport("Sprinting");
        player29.setAge(26);
        player29.setTeamName("India Athletics");
        player29.setMatchesPlayed(40);
        player29.setRole("Sprinter");
        player29.setNationality("Indian");
        System.out.println("Player Name: " + player29.getPlayerName());
        System.out.println("Sport: " + player29.getSport());
        System.out.println("Age: " + player29.getAge());
        System.out.println("Team Name: " + player29.getTeamName());
        System.out.println("Matches Played: " + player29.getMatchesPlayed());
        System.out.println("Role: " + player29.getRole());
        System.out.println("Nationality: " + player29.getNationality());
    }
}