class PocketRunner {
    public static void main(String[] args) {
// default constructor
        Pocket p1 = new Pocket();
        p1.type = "Side Pocket"; p1.width = 10.0; p1.depth = 12.0;
        Pocket p2 = new Pocket();
        p2.type = "Back Pocket"; p2.width = 11.0; p2.depth = 13.0;
        Pocket p3 = new Pocket();
        p3.type = "Chest Pocket"; p3.width = 8.0; p3.depth = 9.0;
        Pocket p4 = new Pocket();
        p4.type = "Hip Pocket"; p4.width = 12.0; p4.depth = 14.0;
        Pocket p5 = new Pocket();
        p5.type = "Cargo Pocket"; p5.width = 15.0; p5.depth = 18.0;
        Pocket p6 = new Pocket();
        p6.type = "Coin Pocket"; p6.width = 5.0; p6.depth = 6.0;
        Pocket p7 = new Pocket();
        p7.type = "Welt Pocket"; p7.width = 9.0; p7.depth = 10.0;
        Pocket p8 = new Pocket();
        p8.type = "Patch Pocket"; p8.width = 13.0; p8.depth = 15.0;
        Pocket p9 = new Pocket();
        p9.type = "Jetted Pocket"; p9.width = 10.0; p9.depth = 11.0;
        Pocket p10 = new Pocket();
        p10.type = "Slash Pocket"; p10.width = 11.0; p10.depth = 12.0;
        Pocket p11 = new Pocket();
        p11.type = "Ticket Pocket"; p11.width = 7.0; p11.depth = 8.0;
        Pocket p12 = new Pocket();
        p12.type = "Kangaroo Pocket"; p12.width = 20.0; p12.depth = 15.0;
        Pocket p13 = new Pocket();
        p13.type = "Hidden Pocket"; p13.width = 9.0; p13.depth = 10.0;
        Pocket p14 = new Pocket();
        p14.type = "Zippered Pocket"; p14.width = 12.0; p14.depth = 13.0;
        Pocket p15 = new Pocket();
        p15.type = "Flap Pocket"; p15.width = 11.0; p15.depth = 12.0;
        Pocket p16 = new Pocket();
        p16.type = "Bellows Pocket"; p16.width = 14.0; p16.depth = 16.0;
        Pocket p17 = new Pocket();
        p17.type = "Inseam Pocket"; p17.width = 10.0; p17.depth = 14.0;
        Pocket p18 = new Pocket();
        p18.type = "Handwarmer Pocket"; p18.width = 16.0; p18.depth = 14.0;
        Pocket p19 = new Pocket();
        p19.type = "Phone Pocket"; p19.width = 8.0; p19.depth = 16.0;
        Pocket p20 = new Pocket();
        p20.type = "Breast Pocket"; p20.width = 9.0; p20.depth = 11.0;
        Pocket p21 = new Pocket();
        p21.type = "Watch Pocket"; p21.width = 6.0; p21.depth = 7.0;
        Pocket p22 = new Pocket();
        p22.type = "Key Pocket"; p22.width = 5.0; p22.depth = 8.0;
        Pocket p23 = new Pocket();
        p23.type = "Napoleon Pocket"; p23.width = 10.0; p23.depth = 12.0;
        Pocket p24 = new Pocket();
        p24.type = "Fob Pocket"; p24.width = 5.0; p24.depth = 6.0;
        Pocket p25 = new Pocket();
        p25.type = "Media Pocket"; p25.width = 9.0; p25.depth = 15.0;

        System.out.println("Pocket type : " + p1.type + ", width : " + p1.width + ", depth : " + p1.depth);
        System.out.println("Pocket type : " + p2.type + ", width : " + p2.width + ", depth : " + p2.depth);
        System.out.println("Pocket type : " + p3.type + ", width : " + p3.width + ", depth : " + p3.depth);
        System.out.println("Pocket type : " + p4.type + ", width : " + p4.width + ", depth : " + p4.depth);
        System.out.println("Pocket type : " + p5.type + ", width : " + p5.width + ", depth : " + p5.depth);
        System.out.println("Pocket type : " + p6.type + ", width : " + p6.width + ", depth : " + p6.depth);
        System.out.println("Pocket type : " + p7.type + ", width : " + p7.width + ", depth : " + p7.depth);
        System.out.println("Pocket type : " + p8.type + ", width : " + p8.width + ", depth : " + p8.depth);
        System.out.println("Pocket type : " + p9.type + ", width : " + p9.width + ", depth : " + p9.depth);
        System.out.println("Pocket type : " + p10.type + ", width : " + p10.width + ", depth : " + p10.depth);
        System.out.println("Pocket type : " + p11.type + ", width : " + p11.width + ", depth : " + p11.depth);
        System.out.println("Pocket type : " + p12.type + ", width : " + p12.width + ", depth : " + p12.depth);
        System.out.println("Pocket type : " + p13.type + ", width : " + p13.width + ", depth : " + p13.depth);
        System.out.println("Pocket type : " + p14.type + ", width : " + p14.width + ", depth : " + p14.depth);
        System.out.println("Pocket type : " + p15.type + ", width : " + p15.width + ", depth : " + p15.depth);
        System.out.println("Pocket type : " + p16.type + ", width : " + p16.width + ", depth : " + p16.depth);
        System.out.println("Pocket type : " + p17.type + ", width : " + p17.width + ", depth : " + p17.depth);
        System.out.println("Pocket type : " + p18.type + ", width : " + p18.width + ", depth : " + p18.depth);
        System.out.println("Pocket type : " + p19.type + ", width : " + p19.width + ", depth : " + p19.depth);
        System.out.println("Pocket type : " + p20.type + ", width : " + p20.width + ", depth : " + p20.depth);
        System.out.println("Pocket type : " + p21.type + ", width : " + p21.width + ", depth : " + p21.depth);
        System.out.println("Pocket type : " + p22.type + ", width : " + p22.width + ", depth : " + p22.depth);
        System.out.println("Pocket type : " + p23.type + ", width : " + p23.width + ", depth : " + p23.depth);
        System.out.println("Pocket type : " + p24.type + ", width : " + p24.width + ", depth : " + p24.depth);
        System.out.println("Pocket type : " + p25.type + ", width : " + p25.width + ", depth : " + p25.depth);

// parameterized constructor
        Pocket q1 = new Pocket("Side Pocket", 10.0, 12.0);
        Pocket q2 = new Pocket("Back Pocket", 11.0, 13.0);
        Pocket q3 = new Pocket("Chest Pocket", 8.0, 9.0);
        Pocket q4 = new Pocket("Hip Pocket", 12.0, 14.0);
        Pocket q5 = new Pocket("Cargo Pocket", 15.0, 18.0);
        Pocket q6 = new Pocket("Coin Pocket", 5.0, 6.0);
        Pocket q7 = new Pocket("Welt Pocket", 9.0, 10.0);
        Pocket q8 = new Pocket("Patch Pocket", 13.0, 15.0);
        Pocket q9 = new Pocket("Jetted Pocket", 10.0, 11.0);
        Pocket q10 = new Pocket("Slash Pocket", 11.0, 12.0);
        Pocket q11 = new Pocket("Ticket Pocket", 7.0, 8.0);
        Pocket q12 = new Pocket("Kangaroo Pocket", 20.0, 15.0);
        Pocket q13 = new Pocket("Hidden Pocket", 9.0, 10.0);
        Pocket q14 = new Pocket("Zippered Pocket", 12.0, 13.0);
        Pocket q15 = new Pocket("Flap Pocket", 11.0, 12.0);
        Pocket q16 = new Pocket("Bellows Pocket", 14.0, 16.0);
        Pocket q17 = new Pocket("Inseam Pocket", 10.0, 14.0);
        Pocket q18 = new Pocket("Handwarmer Pocket", 16.0, 14.0);
        Pocket q19 = new Pocket("Phone Pocket", 8.0, 16.0);
        Pocket q20 = new Pocket("Breast Pocket", 9.0, 11.0);
        Pocket q21 = new Pocket("Watch Pocket", 6.0, 7.0);
        Pocket q22 = new Pocket("Key Pocket", 5.0, 8.0);
        Pocket q23 = new Pocket("Napoleon Pocket", 10.0, 12.0);
        Pocket q24 = new Pocket("Fob Pocket", 5.0, 6.0);
        Pocket q25 = new Pocket("Media Pocket", 9.0, 15.0);

        System.out.println("Type of Pocket 1 : " + q1.type + ", width : " + q1.width + ", depth : " + q1.depth);
        System.out.println("Type of Pocket 2 : " + q2.type + ", width : " + q2.width + ", depth : " + q2.depth);
        System.out.println("Type of Pocket 3 : " + q3.type + ", width : " + q3.width + ", depth : " + q3.depth);
        System.out.println("Type of Pocket 4 : " + q4.type + ", width : " + q4.width + ", depth : " + q4.depth);
        System.out.println("Type of Pocket 5 : " + q5.type + ", width : " + q5.width + ", depth : " + q5.depth);
        System.out.println("Type of Pocket 6 : " + q6.type + ", width : " + q6.width + ", depth : " + q6.depth);
        System.out.println("Type of Pocket 7 : " + q7.type + ", width : " + q7.width + ", depth : " + q7.depth);
        System.out.println("Type of Pocket 8 : " + q8.type + ", width : " + q8.width + ", depth : " + q8.depth);
        System.out.println("Type of Pocket 9 : " + q9.type + ", width : " + q9.width + ", depth : " + q9.depth);
        System.out.println("Type of Pocket 10 : " + q10.type + ", width : " + q10.width + ", depth : " + q10.depth);
        System.out.println("Type of Pocket 11 : " + q11.type + ", width : " + q11.width + ", depth : " + q11.depth);
        System.out.println("Type of Pocket 12 : " + q12.type + ", width : " + q12.width + ", depth : " + q12.depth);
        System.out.println("Type of Pocket 13 : " + q13.type + ", width : " + q13.width + ", depth : " + q13.depth);
        System.out.println("Type of Pocket 14 : " + q14.type + ", width : " + q14.width + ", depth : " + q14.depth);
        System.out.println("Type of Pocket 15 : " + q15.type + ", width : " + q15.width + ", depth : " + q15.depth);
        System.out.println("Type of Pocket 16 : " + q16.type + ", width : " + q16.width + ", depth : " + q16.depth);
        System.out.println("Type of Pocket 17 : " + q17.type + ", width : " + q17.width + ", depth : " + q17.depth);
        System.out.println("Type of Pocket 18 : " + q18.type + ", width : " + q18.width + ", depth : " + q18.depth);
        System.out.println("Type of Pocket 19 : " + q19.type + ", width : " + q19.width + ", depth : " + q19.depth);
        System.out.println("Type of Pocket 20 : " + q20.type + ", width : " + q20.width + ", depth : " + q20.depth);
        System.out.println("Type of Pocket 21 : " + q21.type + ", width : " + q21.width + ", depth : " + q21.depth);
        System.out.println("Type of Pocket 22 : " + q22.type + ", width : " + q22.width + ", depth : " + q22.depth);
        System.out.println("Type of Pocket 23 : " + q23.type + ", width : " + q23.width + ", depth : " + q23.depth);
        System.out.println("Type of Pocket 24 : " + q24.type + ", width : " + q24.width + ", depth : " + q24.depth);
        System.out.println("Type of Pocket 25 : " + q25.type + ", width : " + q25.width + ", depth : " + q25.depth);
    }
}