class SubscriptionDetailsExecutor {
    public static void main(String[] args) {
        SubscriptionDetails s1 = new SubscriptionDetails();
        s1.setSubscriptionId("001");
        s1.setPlanName("Hotstar Premium");
        s1.setSubscriberName("Aman Verma");
        s1.setPrice(1499.00);
        s1.setStartDate("01-01-2026");
        s1.setExpiryDate("31-12-2026");
        s1.setStatus("Active");
        System.out.println("ID: " + s1.getSubscriptionId());
        System.out.println("Plan: " + s1.getPlanName());
        System.out.println("Name: " + s1.getSubscriberName());
        System.out.println("Price: " + s1.getPrice());
        System.out.println("Start: " + s1.getStartDate());
        System.out.println("Expiry: " + s1.getExpiryDate());
        System.out.println("Status: " + s1.getStatus());

        SubscriptionDetails s2 = new SubscriptionDetails();
        s2.setSubscriptionId("002");
        s2.setPlanName("Netflix Gold");
        s2.setSubscriberName("Priya Das");
        s2.setPrice(649.00);
        s2.setStartDate("15-02-2026");
        s2.setExpiryDate("15-03-2026");
        s2.setStatus("Active");
        System.out.println("ID: " + s2.getSubscriptionId());
        System.out.println("Plan: " + s2.getPlanName());
        System.out.println("Name: " + s2.getSubscriberName());
        System.out.println("Price: " + s2.getPrice());
        System.out.println("Start: " + s2.getStartDate());
        System.out.println("Expiry: " + s2.getExpiryDate());
        System.out.println("Status: " + s2.getStatus());

        SubscriptionDetails s3 = new SubscriptionDetails();
        s3.setSubscriptionId("003");
        s3.setPlanName("JioFiber 100Mbps");
        s3.setSubscriberName("Rohan Joshi");
        s3.setPrice(824.00);
        s3.setStartDate("10-03-2026");
        s3.setExpiryDate("10-04-2026");
        s3.setStatus("Active");
        System.out.println("ID: " + s3.getSubscriptionId());
        System.out.println("Plan: " + s3.getPlanName());
        System.out.println("Name: " + s3.getSubscriberName());
        System.out.println("Price: " + s3.getPrice());
        System.out.println("Start: " + s3.getStartDate());
        System.out.println("Expiry: " + s3.getExpiryDate());
        System.out.println("Status: " + s3.getStatus());

        SubscriptionDetails s4 = new SubscriptionDetails();
        s4.setSubscriptionId("004");
        s4.setPlanName("Amazon Prime");
        s4.setSubscriberName("Sneha Kapoor");
        s4.setPrice(1499.00);
        s4.setStartDate("20-01-2026");
        s4.setExpiryDate("20-01-2027");
        s4.setStatus("Active");
        System.out.println("ID: " + s4.getSubscriptionId());
        System.out.println("Plan: " + s4.getPlanName());
        System.out.println("Name: " + s4.getSubscriberName());
        System.out.println("Price: " + s4.getPrice());
        System.out.println("Start: " + s4.getStartDate());
        System.out.println("Expiry: " + s4.getExpiryDate());
        System.out.println("Status: " + s4.getStatus());

        SubscriptionDetails s5 = new SubscriptionDetails();
        s5.setSubscriptionId("005");
        s5.setPlanName("Zomato Gold");
        s5.setSubscriberName("Vikram Singh");
        s5.setPrice(299.00);
        s5.setStartDate("05-03-2026");
        s5.setExpiryDate("05-06-2026");
        s5.setStatus("Active");
        System.out.println("ID: " + s5.getSubscriptionId());
        System.out.println("Plan: " + s5.getPlanName());
        System.out.println("Name: " + s5.getSubscriberName());
        System.out.println("Price: " + s5.getPrice());
        System.out.println("Start: " + s5.getStartDate());
        System.out.println("Expiry: " + s5.getExpiryDate());
        System.out.println("Status: " + s5.getStatus());

        SubscriptionDetails s6 = new SubscriptionDetails();
        s6.setSubscriptionId("006");
        s6.setPlanName("SonyLiv Yearly");
        s6.setSubscriberName("Ishita Iyer");
        s6.setPrice(999.00);
        s6.setStartDate("12-12-2025");
        s6.setExpiryDate("11-12-2026");
        s6.setStatus("Active");
        System.out.println("ID: " + s6.getSubscriptionId());
        System.out.println("Plan: " + s6.getPlanName());
        System.out.println("Name: " + s6.getSubscriberName());
        System.out.println("Price: " + s6.getPrice());
        System.out.println("Start: " + s6.getStartDate());
        System.out.println("Expiry: " + s6.getExpiryDate());
        System.out.println("Status: " + s6.getStatus());

        SubscriptionDetails s7 = new SubscriptionDetails();
        s7.setSubscriptionId("007");
        s7.setPlanName("Zee5 Premium");
        s7.setSubscriberName("Arjun Reddy");
        s7.setPrice(499.00);
        s7.setStartDate("01-02-2026");
        s7.setExpiryDate("31-01-2027");
        s7.setStatus("Active");
        System.out.println("ID: " + s7.getSubscriptionId());
        System.out.println("Plan: " + s7.getPlanName());
        System.out.println("Name: " + s7.getSubscriberName());
        System.out.println("Price: " + s7.getPrice());
        System.out.println("Start: " + s7.getStartDate());
        System.out.println("Expiry: " + s7.getExpiryDate());
        System.out.println("Status: " + s7.getStatus());

        SubscriptionDetails s8 = new SubscriptionDetails();
        s8.setSubscriptionId("008");
        s8.setPlanName("Youtube Premium");
        s8.setSubscriberName("Kavya Madhav");
        s8.setPrice(129.00);
        s8.setStartDate("25-03-2026");
        s8.setExpiryDate("25-04-2026");
        s8.setStatus("Active");
        System.out.println("ID: " + s8.getSubscriptionId());
        System.out.println("Plan: " + s8.getPlanName());
        System.out.println("Name: " + s8.getSubscriberName());
        System.out.println("Price: " + s8.getPrice());
        System.out.println("Start: " + s8.getStartDate());
        System.out.println("Expiry: " + s8.getExpiryDate());
        System.out.println("Status: " + s8.getStatus());

        SubscriptionDetails s9 = new SubscriptionDetails();
        s9.setSubscriptionId("009");
        s9.setPlanName("Airtel Xstream");
        s9.setSubscriberName("Manish Pandey");
        s9.setPrice(149.00);
        s9.setStartDate("18-03-2026");
        s9.setExpiryDate("17-04-2026");
        s9.setStatus("Active");
        System.out.println("ID: " + s9.getSubscriptionId());
        System.out.println("Plan: " + s9.getPlanName());
        System.out.println("Name: " + s9.getSubscriberName());
        System.out.println("Price: " + s9.getPrice());
        System.out.println("Start: " + s9.getStartDate());
        System.out.println("Expiry: " + s9.getExpiryDate());
        System.out.println("Status: " + s9.getStatus());

        SubscriptionDetails s10 = new SubscriptionDetails();
        s10.setSubscriptionId("010");
        s10.setPlanName("AltBalaji Lite");
        s10.setSubscriberName("Riya Sen");
        s10.setPrice(300.00);
        s10.setStartDate("01-01-2026");
        s10.setExpiryDate("31-12-2026");
        s10.setStatus("Expired");
        System.out.println("ID: " + s10.getSubscriptionId());
        System.out.println("Plan: " + s10.getPlanName());
        System.out.println("Name: " + s10.getSubscriberName());
        System.out.println("Price: " + s10.getPrice());
        System.out.println("Start: " + s10.getStartDate());
        System.out.println("Expiry: " + s10.getExpiryDate());
        System.out.println("Status: " + s10.getStatus());

        SubscriptionDetails s11 = new SubscriptionDetails();
        s11.setSubscriptionId("011");
        s11.setPlanName("Cult.fit Pass");
        s11.setSubscriberName("Sidharth M");
        s11.setPrice(12000.00);
        s11.setStartDate("10-01-2026");
        s11.setExpiryDate("09-01-2027");
        s11.setStatus("Active");
        System.out.println("ID: " + s11.getSubscriptionId());
        System.out.println("Plan: " + s11.getPlanName());
        System.out.println("Name: " + s11.getSubscriberName());
        System.out.println("Price: " + s11.getPrice());
        System.out.println("Start: " + s11.getStartDate());
        System.out.println("Expiry: " + s11.getExpiryDate());
        System.out.println("Status: " + s11.getStatus());

        SubscriptionDetails s12 = new SubscriptionDetails();
        s12.setSubscriptionId("012");
        s12.setPlanName("Economic Times");
        s12.setSubscriberName("Rahul Jain");
        s12.setPrice(2499.00);
        s12.setStartDate("01-04-2026");
        s12.setExpiryDate("31-03-2027");
        s12.setStatus("Active");
        System.out.println("ID: " + s12.getSubscriptionId());
        System.out.println("Plan: " + s12.getPlanName());
        System.out.println("Name: " + s12.getSubscriberName());
        System.out.println("Price: " + s12.getPrice());
        System.out.println("Start: " + s12.getStartDate());
        System.out.println("Expiry: " + s12.getExpiryDate());
        System.out.println("Status: " + s12.getStatus());

        SubscriptionDetails s13 = new SubscriptionDetails();
        s13.setSubscriptionId("013");
        s13.setPlanName("Gaana Plus");
        s13.setSubscriberName("Neha Kakkar");
        s13.setPrice(399.00);
        s13.setStartDate("14-02-2026");
        s13.setExpiryDate("13-02-2027");
        s13.setStatus("Active");
        System.out.println("ID: " + s13.getSubscriptionId());
        System.out.println("Plan: " + s13.getPlanName());
        System.out.println("Name: " + s13.getSubscriberName());
        System.out.println("Price: " + s13.getPrice());
        System.out.println("Start: " + s13.getStartDate());
        System.out.println("Expiry: " + s13.getExpiryDate());
        System.out.println("Status: " + s13.getStatus());

        SubscriptionDetails s14 = new SubscriptionDetails();
        s14.setSubscriptionId("014");
        s14.setPlanName("Spotify Duo");
        s14.setSubscriberName("Arijit Singh");
        s14.setPrice(149.00);
        s14.setStartDate("01-03-2026");
        s14.setExpiryDate("31-03-2026");
        s14.setStatus("Active");
        System.out.println("ID: " + s14.getSubscriptionId());
        System.out.println("Plan: " + s14.getPlanName());
        System.out.println("Name: " + s14.getSubscriberName());
        System.out.println("Price: " + s14.getPrice());
        System.out.println("Start: " + s14.getStartDate());
        System.out.println("Expiry: " + s14.getExpiryDate());
        System.out.println("Status: " + s14.getStatus());

        SubscriptionDetails s15 = new SubscriptionDetails();
        s15.setSubscriptionId("015");
        s15.setPlanName("Swiggy One");
        s15.setSubscriberName("Ranveer Brar");
        s15.setPrice(899.00);
        s15.setStartDate("20-03-2026");
        s15.setExpiryDate("19-06-2026");
        s15.setStatus("Active");
        System.out.println("ID: " + s15.getSubscriptionId());
        System.out.println("Plan: " + s15.getPlanName());
        System.out.println("Name: " + s15.getSubscriberName());
        System.out.println("Price: " + s15.getPrice());
        System.out.println("Start: " + s15.getStartDate());
        System.out.println("Expiry: " + s15.getExpiryDate());
        System.out.println("Status: " + s15.getStatus());

        SubscriptionDetails s16 = new SubscriptionDetails();
        s16.setSubscriptionId("016");
        s16.setPlanName("TATA Sky Binge");
        s16.setSubscriberName("Karan Johar");
        s16.setPrice(299.00);
        s16.setStartDate("01-04-2026");
        s16.setExpiryDate("30-04-2026");
        s16.setStatus("Active");
        System.out.println("ID: " + s16.getSubscriptionId());
        System.out.println("Plan: " + s16.getPlanName());
        System.out.println("Name: " + s16.getSubscriberName());
        System.out.println("Price: " + s16.getPrice());
        System.out.println("Start: " + s16.getStartDate());
        System.out.println("Expiry: " + s16.getExpiryDate());
        System.out.println("Status: " + s16.getStatus());

        SubscriptionDetails s17 = new SubscriptionDetails();
        s17.setSubscriptionId("017");
        s17.setPlanName("Apple One");
        s17.setSubscriberName("Ratan Tata");
        s17.setPrice(365.00);
        s17.setStartDate("01-01-2026");
        s17.setExpiryDate("31-01-2026");
        s17.setStatus("Active");
        System.out.println("ID: " + s17.getSubscriptionId());
        System.out.println("Plan: " + s17.getPlanName());
        System.out.println("Name: " + s17.getSubscriberName());
        System.out.println("Price: " + s17.getPrice());
        System.out.println("Start: " + s17.getStartDate());
        System.out.println("Expiry: " + s17.getExpiryDate());
        System.out.println("Status: " + s17.getStatus());

        SubscriptionDetails s18 = new SubscriptionDetails();
        s18.setSubscriptionId("018");
        s18.setPlanName("Discovery+");
        s18.setSubscriberName("Bear Grylls");
        s18.setPrice(399.00);
        s18.setStartDate("10-02-2026");
        s18.setExpiryDate("09-02-2027");
        s18.setStatus("Active");
        System.out.println("ID: " + s18.getSubscriptionId());
        System.out.println("Plan: " + s18.getPlanName());
        System.out.println("Name: " + s18.getSubscriberName());
        System.out.println("Price: " + s18.getPrice());
        System.out.println("Start: " + s18.getStartDate());
        System.out.println("Expiry: " + s18.getExpiryDate());
        System.out.println("Status: " + s18.getStatus());

        SubscriptionDetails s19 = new SubscriptionDetails();
        s19.setSubscriptionId("019");
        s19.setPlanName("Mubi India");
        s19.setSubscriberName("Nawazuddin S");
        s19.setPrice(499.00);
        s19.setStartDate("01-03-2026");
        s19.setExpiryDate("31-03-2026");
        s19.setStatus("Active");
        System.out.println("ID: " + s19.getSubscriptionId());
        System.out.println("Plan: " + s19.getPlanName());
        System.out.println("Name: " + s19.getSubscriberName());
        System.out.println("Price: " + s19.getPrice());
        System.out.println("Start: " + s19.getStartDate());
        System.out.println("Expiry: " + s19.getExpiryDate());
        System.out.println("Status: " + s19.getStatus());

        SubscriptionDetails s20 = new SubscriptionDetails();
        s20.setSubscriptionId("020");
        s20.setPlanName("Pharmeasy Plus");
        s20.setSubscriberName("Dr. Trehan");
        s20.setPrice(599.00);
        s20.setStartDate("15-03-2026");
        s20.setExpiryDate("14-09-2026");
        s20.setStatus("Active");
        System.out.println("ID: " + s20.getSubscriptionId());
        System.out.println("Plan: " + s20.getPlanName());
        System.out.println("Name: " + s20.getSubscriberName());
        System.out.println("Price: " + s20.getPrice());
        System.out.println("Start: " + s20.getStartDate());
        System.out.println("Expiry: " + s20.getExpiryDate());
        System.out.println("Status: " + s20.getStatus());

        SubscriptionDetails s21 = new SubscriptionDetails();
        s21.setSubscriptionId("021");
        s21.setPlanName("Microsoft 365");
        s21.setSubscriberName("Satya Nadella");
        s21.setPrice(4899.00);
        s21.setStartDate("01-01-2026");
        s21.setExpiryDate("31-12-2026");
        s21.setStatus("Active");
        System.out.println("ID: " + s21.getSubscriptionId());
        System.out.println("Plan: " + s21.getPlanName());
        System.out.println("Name: " + s21.getSubscriberName());
        System.out.println("Price: " + s21.getPrice());
        System.out.println("Start: " + s21.getStartDate());
        System.out.println("Expiry: " + s21.getExpiryDate());
        System.out.println("Status: " + s21.getStatus());

        SubscriptionDetails s22 = new SubscriptionDetails();
        s22.setSubscriptionId("022");
        s22.setPlanName("LinkedIn Premium");
        s22.setSubscriberName("Kunhal Shah");
        s22.setPrice(1600.00);
        s22.setStartDate("12-02-2026");
        s22.setExpiryDate("11-03-2026");
        s22.setStatus("Active");
        System.out.println("ID: " + s22.getSubscriptionId());
        System.out.println("Plan: " + s22.getPlanName());
        System.out.println("Name: " + s22.getSubscriberName());
        System.out.println("Price: " + s22.getPrice());
        System.out.println("Start: " + s22.getStartDate());
        System.out.println("Expiry: " + s22.getExpiryDate());
        System.out.println("Status: " + s22.getStatus());

        SubscriptionDetails s23 = new SubscriptionDetails();
        s23.setSubscriptionId("023");
        s23.setPlanName("Skillshare");
        s23.setSubscriberName("Varun Mayya");
        s23.setPrice(3000.00);
        s23.setStartDate("20-03-2026");
        s23.setExpiryDate("19-03-2027");
        s23.setStatus("Active");
        System.out.println("ID: " + s23.getSubscriptionId());
        System.out.println("Plan: " + s23.getPlanName());
        System.out.println("Name: " + s23.getSubscriberName());
        System.out.println("Price: " + s23.getPrice());
        System.out.println("Start: " + s23.getStartDate());
        System.out.println("Expiry: " + s23.getExpiryDate());
        System.out.println("Status: " + s23.getStatus());

        SubscriptionDetails s24 = new SubscriptionDetails();
        s24.setSubscriptionId("024");
        s24.setPlanName("Udemy Business");
        s24.setSubscriberName("TCS Employee");
        s24.setPrice(0.00);
        s24.setStartDate("01-01-2026");
        s24.setExpiryDate("31-12-2026");
        s24.setStatus("Active");
        System.out.println("ID: " + s24.getSubscriptionId());
        System.out.println("Plan: " + s24.getPlanName());
        System.out.println("Name: " + s24.getSubscriberName());
        System.out.println("Price: " + s24.getPrice());
        System.out.println("Start: " + s24.getStartDate());
        System.out.println("Expiry: " + s24.getExpiryDate());
        System.out.println("Status: " + s24.getStatus());

        SubscriptionDetails s25 = new SubscriptionDetails();
        s25.setSubscriptionId("025");
        s25.setPlanName("HBR India");
        s25.setSubscriberName("Vijay Shekhar");
        s25.setPrice(5000.00);
        s25.setStartDate("15-01-2026");
        s25.setExpiryDate("14-01-2027");
        s25.setStatus("Active");
        System.out.println("ID: " + s25.getSubscriptionId());
        System.out.println("Plan: " + s25.getPlanName());
        System.out.println("Name: " + s25.getSubscriberName());
        System.out.println("Price: " + s25.getPrice());
        System.out.println("Start: " + s25.getStartDate());
        System.out.println("Expiry: " + s25.getExpiryDate());
        System.out.println("Status: " + s25.getStatus());

        SubscriptionDetails s26 = new SubscriptionDetails();
        s26.setSubscriptionId("026");
        s26.setPlanName("Canva Pro");
        s26.setSubscriberName("Ankur Warikoo");
        s26.setPrice(3999.00);
        s26.setStartDate("10-02-2026");
        s26.setExpiryDate("09-02-2027");
        s26.setStatus("Active");
        System.out.println("ID: " + s26.getSubscriptionId());
        System.out.println("Plan: " + s26.getPlanName());
        System.out.println("Name: " + s26.getSubscriberName());
        System.out.println("Price: " + s26.getPrice());
        System.out.println("Start: " + s26.getStartDate());
        System.out.println("Expiry: " + s26.getExpiryDate());
        System.out.println("Status: " + s26.getStatus());

        SubscriptionDetails s27 = new SubscriptionDetails();
        s27.setSubscriptionId("027");
        s27.setPlanName("Midjourney AI");
        s27.setSubscriberName("Snehil Khanor");
        s27.setPrice(2500.00);
        s27.setStartDate("20-03-2026");
        s27.setExpiryDate("19-04-2026");
        s27.setStatus("Active");
        System.out.println("ID: " + s27.getSubscriptionId());
        System.out.println("Plan: " + s27.getPlanName());
        System.out.println("Name: " + s27.getSubscriberName());
        System.out.println("Price: " + s27.getPrice());
        System.out.println("Start: " + s27.getStartDate());
        System.out.println("Expiry: " + s27.getExpiryDate());
        System.out.println("Status: " + s27.getStatus());

        SubscriptionDetails s28 = new SubscriptionDetails();
        s28.setSubscriptionId("028");
        s28.setPlanName("ChatGPT Plus");
        s28.setSubscriberName("Tanmay Bhat");
        s28.setPrice(1650.00);
        s28.setStartDate("01-04-2026");
        s28.setExpiryDate("30-04-2026");
        s28.setStatus("Active");
        System.out.println("ID: " + s28.getSubscriptionId());
        System.out.println("Plan: " + s28.getPlanName());
        System.out.println("Name: " + s28.getSubscriberName());
        System.out.println("Price: " + s28.getPrice());
        System.out.println("Start: " + s28.getStartDate());
        System.out.println("Expiry: " + s28.getExpiryDate());
        System.out.println("Status: " + s28.getStatus());

        SubscriptionDetails s29 = new SubscriptionDetails();
        s29.setSubscriptionId("029");
        s29.setPlanName("Disney+ Annual");
        s29.setSubscriberName("Rajesh Hamal");
        s29.setPrice(1499.00);
        s29.setStartDate("01-01-2026");
        s29.setExpiryDate("31-12-2026");
        s29.setStatus("Active");
        System.out.println("ID: " + s29.getSubscriptionId());
        System.out.println("Plan: " + s29.getPlanName());
        System.out.println("Name: " + s29.getSubscriberName());
        System.out.println("Price: " + s29.getPrice());
        System.out.println("Start: " + s29.getStartDate());
        System.out.println("Expiry: " + s29.getExpiryDate());
        System.out.println("Status: " + s29.getStatus());
    }
}