class UserAccountExecutor {
    public static void main(String[] args) {
	
        UserAccount user1 = new UserAccount();
        user1.setUserId(1);
        user1.setUserName("Aarav Sharma");
        user1.setEmail("aarav.sharma@gmail.com");
        user1.setMobileNumber("9876543210");
        user1.setState("Maharashtra");
        user1.setAccountStatus("Active");
        user1.setLastLogin("01-04-2026");
        System.out.println("User ID: " + user1.getUserId());
        System.out.println("User Name: " + user1.getUserName());
        System.out.println("Email: " + user1.getEmail());
        System.out.println("Mobile: " + user1.getMobileNumber());
        System.out.println("State: " + user1.getState());
        System.out.println("Status: " + user1.getAccountStatus());
        System.out.println("Last Login: " + user1.getLastLogin());

        UserAccount user2 = new UserAccount();
        user2.setUserId(2);
        user2.setUserName("Vihaan Iyer");
        user2.setEmail("vihaan.iyer@yahoo.com");
        user2.setMobileNumber("9123456789");
        user2.setState("Tamil Nadu");
        user2.setAccountStatus("Inactive");
        user2.setLastLogin("15-03-2026");
        System.out.println("User ID: " + user2.getUserId());
        System.out.println("User Name: " + user2.getUserName());
        System.out.println("Email: " + user2.getEmail());
        System.out.println("Mobile: " + user2.getMobileNumber());
        System.out.println("State: " + user2.getState());
        System.out.println("Status: " + user2.getAccountStatus());
        System.out.println("Last Login: " + user2.getLastLogin());

        UserAccount user3 = new UserAccount();
        user3.setUserId(3);
        user3.setUserName("Aditi Gupta");
        user3.setEmail("aditi.gupta@outlook.com");
        user3.setMobileNumber("9988776655");
        user3.setState("Uttar Pradesh");
        user3.setAccountStatus("Active");
        user3.setLastLogin("28-03-2026");
        System.out.println("User ID: " + user3.getUserId());
        System.out.println("User Name: " + user3.getUserName());
        System.out.println("Email: " + user3.getEmail());
        System.out.println("Mobile: " + user3.getMobileNumber());
        System.out.println("State: " + user3.getState());
        System.out.println("Status: " + user3.getAccountStatus());
        System.out.println("Last Login: " + user3.getLastLogin());

        UserAccount user4 = new UserAccount();
        user4.setUserId(4);
        user4.setUserName("Reyansh Patel");
        user4.setEmail("reyansh@gmail.com");
        user4.setMobileNumber("8877665544");
        user4.setState("Gujarat");
        user4.setAccountStatus("Blocked");
        user4.setLastLogin("-02-2026");
        System.out.println("User ID: " + user4.getUserId());
        System.out.println("User Name: " + user4.getUserName());
        System.out.println("Email: " + user4.getEmail());
        System.out.println("Mobile: " + user4.getMobileNumber());
        System.out.println("State: " + user4.getState());
        System.out.println("Status: " + user4.getAccountStatus());
        System.out.println("Last Login: " + user4.getLastLogin());

        UserAccount user5 = new UserAccount();
        user5.setUserId(5);
        user5.setUserName("Ananya Singh");
        user5.setEmail("ananya@gmail.com");
        user5.setMobileNumber("7766554433");
        user5.setState("Punjab");
        user5.setAccountStatus("Active");
        user5.setLastLogin("30-03-2026");
        System.out.println("User ID: " + user5.getUserId());
        System.out.println("User Name: " + user5.getUserName());
        System.out.println("Email: " + user5.getEmail());
        System.out.println("Mobile: " + user5.getMobileNumber());
        System.out.println("State: " + user5.getState());
        System.out.println("Status: " + user5.getAccountStatus());
        System.out.println("Last Login: " + user5.getLastLogin());

        UserAccount user6 = new UserAccount();
        user6.setUserId(6);
        user6.setUserName("Sai Kiran");
        user6.setEmail("kiran.sai@gmail.com");
        user6.setMobileNumber("9440123456");
        user6.setState("Andhra Pradesh");
        user6.setAccountStatus("Active");
        user6.setLastLogin("25-03-2026");
        System.out.println("User ID: " + user6.getUserId());
        System.out.println("User Name: " + user6.getUserName());
        System.out.println("Email: " + user6.getEmail());
        System.out.println("Mobile: " + user6.getMobileNumber());
        System.out.println("State: " + user6.getState());
        System.out.println("Status: " + user6.getAccountStatus());
        System.out.println("Last Login: " + user6.getLastLogin());

        UserAccount user7 = new UserAccount();
        user7.setUserId(7);
        user7.setUserName("Ishaan Deshmukh");
        user7.setEmail("ishaan@gmail.com");
        user7.setMobileNumber("8123450000");
        user7.setState("Karnataka");
        user7.setAccountStatus("Active");
        user7.setLastLogin("20-03-2026");
        System.out.println("User ID: " + user7.getUserId());
        System.out.println("User Name: " + user7.getUserName());
        System.out.println("Email: " + user7.getEmail());
        System.out.println("Mobile: " + user7.getMobileNumber());
        System.out.println("State: " + user7.getState());
        System.out.println("Status: " + user7.getAccountStatus());
        System.out.println("Last Login: " + user7.getLastLogin());

        UserAccount user8 = new UserAccount();
        user8.setUserId(8);
        user8.setUserName("Meera Nair");
        user8.setEmail("meera@gmail.com");
        user8.setMobileNumber("7012345678");
        user8.setState("Kerala");
        user8.setAccountStatus("Active");
        user8.setLastLogin("29-03-2026");
        System.out.println("User ID: " + user8.getUserId());
        System.out.println("User Name: " + user8.getUserName());
        System.out.println("Email: " + user8.getEmail());
        System.out.println("Mobile: " + user8.getMobileNumber());
        System.out.println("State: " + user8.getState());
        System.out.println("Status: " + user8.getAccountStatus());
        System.out.println("Last Login: " + user8.getLastLogin());

        UserAccount user9 = new UserAccount();
        user9.setUserId(9);
        user9.setUserName("Arjun Reddy");
        user9.setEmail("arjun.reddy@gmail.com");
        user9.setMobileNumber("9900112233");
        user9.setState("Telangana");
        user9.setAccountStatus("Inactive");
        user9.setLastLogin("05-01-2026");
        System.out.println("User ID: " + user9.getUserId());
        System.out.println("User Name: " + user9.getUserName());
        System.out.println("Email: " + user9.getEmail());
        System.out.println("Mobile: " + user9.getMobileNumber());
        System.out.println("State: " + user9.getState());
        System.out.println("Status: " + user9.getAccountStatus());
        System.out.println("Last Login: " + user9.getLastLogin());

        UserAccount user10 = new UserAccount();
        user10.setUserId(10);
        user10.setUserName("Siddharth Das");
        user10.setEmail("sid.das@gmail.com");
        user10.setMobileNumber("9123451122");
        user10.setState("West Bengal");
        user10.setAccountStatus("Active");
        user10.setLastLogin("27-03-2026");
        System.out.println("User ID: " + user10.getUserId());
        System.out.println("User Name: " + user10.getUserName());
        System.out.println("Email: " + user10.getEmail());
        System.out.println("Mobile: " + user10.getMobileNumber());
        System.out.println("State: " + user10.getState());
        System.out.println("Status: " + user10.getAccountStatus());
        System.out.println("Last Login: " + user10.getLastLogin());

        UserAccount user11 = new UserAccount();
        user11.setUserId(11);
        user11.setUserName("Diya Bose");
        user11.setEmail("diya.b@gmail.com");
        user11.setMobileNumber("8899001122");
        user11.setState("West Bengal");
        user11.setAccountStatus("Active");
        user11.setLastLogin("22-03-2026");
        System.out.println("User ID: " + user11.getUserId());
        System.out.println("User Name: " + user11.getUserName());
        System.out.println("Email: " + user11.getEmail());
        System.out.println("Mobile: " + user11.getMobileNumber());
        System.out.println("State: " + user11.getState());
        System.out.println("Status: " + user11.getAccountStatus());
        System.out.println("Last Login: " + user11.getLastLogin());

        UserAccount user12 = new UserAccount();
        user12.setUserId(12);
        user12.setUserName("Kabir Khan");
        user12.setEmail("kabir.khan@gmail.com");
        user12.setMobileNumber("9000800070");
        user12.setState("Delhi");
        user12.setAccountStatus("Active");
        user12.setLastLogin("18-03-2026");
        System.out.println("User ID: " + user12.getUserId());
        System.out.println("User Name: " + user12.getUserName());
        System.out.println("Email: " + user12.getEmail());
        System.out.println("Mobile: " + user12.getMobileNumber());
        System.out.println("State: " + user12.getState());
        System.out.println("Status: " + user12.getAccountStatus());
        System.out.println("Last Login: " + user12.getLastLogin());

        UserAccount user13 = new UserAccount();
        user13.setUserId(13);
        user13.setUserName("Kiara Malhotra");
        user13.setEmail("kiara.m@gmail.com");
        user13.setMobileNumber("9222333444");
        user13.setState("Haryana");
        user13.setAccountStatus("Active");
        user13.setLastLogin("15-03-2026");
        System.out.println("User ID: " + user13.getUserId());
        System.out.println("User Name: " + user13.getUserName());
        System.out.println("Email: " + user13.getEmail());
        System.out.println("Mobile: " + user13.getMobileNumber());
        System.out.println("State: " + user13.getState());
        System.out.println("Status: " + user13.getAccountStatus());
        System.out.println("Last Login: " + user13.getLastLogin());

        UserAccount user14 = new UserAccount();
        user14.setUserId(14);
        user14.setUserName("Ranveer Singh");
        user14.setEmail("ranveer.s@gmail.com");
        user14.setMobileNumber("9333444555");
        user14.setState("Rajasthan");
        user14.setAccountStatus("Active");
        user14.setLastLogin("-03-2026");
        System.out.println("User ID: " + user14.getUserId());
        System.out.println("User Name: " + user14.getUserName());
        System.out.println("Email: " + user14.getEmail());
        System.out.println("Mobile: " + user14.getMobileNumber());
        System.out.println("State: " + user14.getState());
        System.out.println("Status: " + user14.getAccountStatus());
        System.out.println("Last Login: " + user14.getLastLogin());

        UserAccount user15 = new UserAccount();
        user15.setUserId(15);
        user15.setUserName("Sara Ali");
        user15.setEmail("sara.ali@gmail.com");
        user15.setMobileNumber("9444555666");
        user15.setState("Madhya Pradesh");
        user15.setAccountStatus("Active");
        user15.setLastLogin("05-03-2026");
         System.out.println("User ID: " + user15.getUserId());
        System.out.println("User Name: " + user15.getUserName());
        System.out.println("Email: " + user15.getEmail());
        System.out.println("Mobile: " + user15.getMobileNumber());
        System.out.println("State: " + user15.getState());
        System.out.println("Status: " + user15.getAccountStatus());
        System.out.println("Last Login: " + user15.getLastLogin());

        UserAccount user16 = new UserAccount();
        user16.setUserId(16);
        user16.setUserName("Pranav Joshi");
        user16.setEmail("pranav.j@gmail.com");
        user16.setMobileNumber("9555666777");
        user16.setState("Uttarakhand");
        user16.setAccountStatus("Active");
        user16.setLastLogin("01-03-2026");
        System.out.println("User ID: " + user16.getUserId());
        System.out.println("User Name: " + user16.getUserName());
        System.out.println("Email: " + user16.getEmail());
        System.out.println("Mobile: " + user16.getMobileNumber());
        System.out.println("State: " + user16.getState());
        System.out.println("Status: " + user16.getAccountStatus());
        System.out.println("Last Login: " + user16.getLastLogin());

        UserAccount user17 = new UserAccount();
        user17.setUserId(17);
        user17.setUserName("Tanvi Hegde");
        user17.setEmail("tanvi.h@gmail.com");
        user17.setMobileNumber("9666777888");
        user17.setState("Goa");
        user17.setAccountStatus("Active");
        user17.setLastLogin("25-02-2026");
        System.out.println("User ID: " + user17.getUserId());
        System.out.println("User Name: " + user17.getUserName());
        System.out.println("Email: " + user17.getEmail());
        System.out.println("Mobile: " + user17.getMobileNumber());
        System.out.println("State: " + user17.getState());
        System.out.println("Status: " + user17.getAccountStatus());
        System.out.println("Last Login: " + user17.getLastLogin());

        UserAccount user18 = new UserAccount();
        user18.setUserId(18);
        user18.setUserName("Advait Rao");
        user18.setEmail("advait.rao@gmail.com");
        user18.setMobileNumber("9777888999");
        user18.setState("Odisha");
        user18.setAccountStatus("Active");
        user18.setLastLogin("20-02-2026");
        System.out.println("User ID: " + user18.getUserId());
        System.out.println("User Name: " + user18.getUserName());
        System.out.println("Email: " + user18.getEmail());
        System.out.println("Mobile: " + user18.getMobileNumber());
        System.out.println("State: " + user18.getState());
        System.out.println("Status: " + user18.getAccountStatus());
        System.out.println("Last Login: " + user18.getLastLogin());

        UserAccount user19 = new UserAccount();
        user19.setUserId(19);
        user19.setUserName("Navya Nanda");
        user19.setEmail("navya@gmail.com");
        user19.setMobileNumber("9888999000");
        user19.setState("Assam");
        user19.setAccountStatus("Active");
        user19.setLastLogin("15-02-2026");
        System.out.println("User ID: " + user19.getUserId());
        System.out.println("User Name: " + user19.getUserName());
        System.out.println("Email: " + user19.getEmail());
        System.out.println("Mobile: " + user19.getMobileNumber());
        System.out.println("State: " + user19.getState());
        System.out.println("Status: " + user19.getAccountStatus());
        System.out.println("Last Login: " + user19.getLastLogin());

        UserAccount user20 = new UserAccount();
        user20.setUserId(20);
        user20.setUserName("Aryan Raj");
        user20.setEmail("aryan.raj@gmail.com");
        user20.setMobileNumber("9999000111");
        user20.setState("Bihar");
        user20.setAccountStatus("Active");
        user20.setLastLogin("-02-2026");
        System.out.println("User ID: " + user20.getUserId());
        System.out.println("User Name: " + user20.getUserName());
        System.out.println("Email: " + user20.getEmail());
        System.out.println("Mobile: " + user20.getMobileNumber());
        System.out.println("State: " + user20.getState());
        System.out.println("Status: " + user20.getAccountStatus());
        System.out.println("Last Login: " + user20.getLastLogin());

        UserAccount user21 = new UserAccount();
        user21.setUserId(21);
        user21.setUserName("Kavya Madhavan");
        user21.setEmail("kavya@gmail.com");
        user21.setMobileNumber("9111222333");
        user21.setState("Kerala");
        user21.setAccountStatus("Active");
        user21.setLastLogin("05-02-2026");
        System.out.println("User ID: " + user21.getUserId());
        System.out.println("User Name: " + user21.getUserName());
        System.out.println("Email: " + user21.getEmail());
        System.out.println("Mobile: " + user21.getMobileNumber());
        System.out.println("State: " + user21.getState());
        System.out.println("Status: " + user21.getAccountStatus());
        System.out.println("Last Login: " + user21.getLastLogin());

        UserAccount user22 = new UserAccount();
        user22.setUserId(22);
        user22.setUserName("Yash Vardhan");
        user22.setEmail("yash@gmail.com");
        user22.setMobileNumber("9222333444");
        user22.setState("Jharkhand");
        user22.setAccountStatus("Active");
        user22.setLastLogin("01-02-2026");
        System.out.println("User ID: " + user22.getUserId());
        System.out.println("User Name: " + user22.getUserName());
        System.out.println("Email: " + user22.getEmail());
        System.out.println("Mobile: " + user22.getMobileNumber());
        System.out.println("State: " + user22.getState());
        System.out.println("Status: " + user22.getAccountStatus());
        System.out.println("Last Login: " + user22.getLastLogin());

        UserAccount user23 = new UserAccount();
        user23.setUserId(23);
        user23.setUserName("Zoya Hussain");
        user23.setEmail("zoya@gmail.com");
        user23.setMobileNumber("9333444555");
        user23.setState("Sikkim");
        user23.setAccountStatus("Active");
        user23.setLastLogin("25-01-2026");
        System.out.println("User ID: " + user23.getUserId());
        System.out.println("User Name: " + user23.getUserName());
        System.out.println("Email: " + user23.getEmail());
        System.out.println("Mobile: " + user23.getMobileNumber());
        System.out.println("State: " + user23.getState());
        System.out.println("Status: " + user23.getAccountStatus());
        System.out.println("Last Login: " + user23.getLastLogin());

        UserAccount user24 = new UserAccount();
        user24.setUserId(24);
        user24.setUserName("Hrithik Roshan");
        user24.setEmail("hrithik@gmail.com");
        user24.setMobileNumber("9444555666");
        user24.setState("Himachal Pradesh");
        user24.setAccountStatus("Active");
        user24.setLastLogin("20-01-2026");
        System.out.println("User ID: " + user24.getUserId());
        System.out.println("User Name: " + user24.getUserName());
        System.out.println("Email: " + user24.getEmail());
        System.out.println("Mobile: " + user24.getMobileNumber());
        System.out.println("State: " + user24.getState());
        System.out.println("Status: " + user24.getAccountStatus());
        System.out.println("Last Login: " + user24.getLastLogin());

        UserAccount user25 = new UserAccount();
        user25.setUserId(25);
        user25.setUserName("Shraddha Kapoor");
        user25.setEmail("shraddha@gmail.com");
        user25.setMobileNumber("9555666777");
        user25.setState("Chhattisgarh");
        user25.setAccountStatus("Active");
        user25.setLastLogin("15-01-2026");
        System.out.println("User ID: " + user25.getUserId());
        System.out.println("User Name: " + user25.getUserName());
        System.out.println("Email: " + user25.getEmail());
        System.out.println("Mobile: " + user25.getMobileNumber());
        System.out.println("State: " + user25.getState());
        System.out.println("Status: " + user25.getAccountStatus());
        System.out.println("Last Login: " + user25.getLastLogin());

        UserAccount user26 = new UserAccount();
        user26.setUserId(26);
        user26.setUserName("Varun Dhawan");
        user26.setEmail("varun@gmail.com");
        user26.setMobileNumber("9666777888");
        user26.setState("Arunachal Pradesh");
        user26.setAccountStatus("Active");
        user26.setLastLogin("-01-2026");
        System.out.println("User ID: " + user26.getUserId());
        System.out.println("User Name: " + user26.getUserName());
        System.out.println("Email: " + user26.getEmail());
        System.out.println("Mobile: " + user26.getMobileNumber());
        System.out.println("State: " + user26.getState());
        System.out.println("Status: " + user26.getAccountStatus());
        System.out.println("Last Login: " + user26.getLastLogin());

        UserAccount user27 = new UserAccount();
        user27.setUserId(27);
        user27.setUserName("Alia Bhatt");
        user27.setEmail("alia@gmail.com");
        user27.setMobileNumber("9777888999");
        user27.setState("Manipur");
        user27.setAccountStatus("Active");
        user27.setLastLogin("05-01-2026");
        System.out.println("User ID: " + user27.getUserId());
        System.out.println("User Name: " + user27.getUserName());
        System.out.println("Email: " + user27.getEmail());
        System.out.println("Mobile: " + user27.getMobileNumber());
        System.out.println("State: " + user27.getState());
        System.out.println("Status: " + user27.getAccountStatus());
        System.out.println("Last Login: " + user27.getLastLogin());

        UserAccount user28 = new UserAccount();
        user28.setUserId(28);
        user28.setUserName("Kartik Aaryan");
        user28.setEmail("kartik@gmail.com");
        user28.setMobileNumber("9888999000");
        user28.setState("Nagaland");
        user28.setAccountStatus("Active");
        user28.setLastLogin("01-01-2026");
        System.out.println("User ID: " + user28.getUserId());
        System.out.println("User Name: " + user28.getUserName());
        System.out.println("Email: " + user28.getEmail());
        System.out.println("Mobile: " + user28.getMobileNumber());
        System.out.println("State: " + user28.getState());
        System.out.println("Status: " + user28.getAccountStatus());
        System.out.println("Last Login: " + user28.getLastLogin());

        UserAccount user29 = new UserAccount();
        user29.setUserId(29);
        user29.setUserName("Janhvi Kapoor");
        user29.setEmail("janhvi@gmail.com");
        user29.setMobileNumber("9999000111");
        user29.setState("Meghalaya");
        user29.setAccountStatus("Active");
        user29.setLastLogin("25-12-2025");
        System.out.println("User ID: " + user29.getUserId());
        System.out.println("User Name: " + user29.getUserName());
        System.out.println("Email: " + user29.getEmail());
        System.out.println("Mobile: " + user29.getMobileNumber());
        System.out.println("State: " + user29.getState());
        System.out.println("Status: " + user29.getAccountStatus());
        System.out.println("Last Login: " + user29.getLastLogin());
    }
}